### ISSUE TITLE
Customize README.md

### ISSUE THREAD

**Issue by garrett** [oVirt/ovirt-site#1]
The readme file should be customized to be specifically for oVirt.

* [x] The title of `README.md` should reflect oVirt.
* [x] If directions do not work or need to be expanded upon, those should also be updated too.

**Comment by thatdocslady** [comment]
Replaced the content with oVirt-specific info, PR merged: https://github.com/oVirt/ovirt-site/pull/46

**Comment by thatdocslady** [comment]
@garrett what do you mean by "title should reflect ovirt"? I was sure that the standard GH practice is to keep README.md as the default root file...

**Comment by garrett** [comment]
`README.md` has "oVirt.org Project Website" at the top for the title of the file. :wink: 

And you really overhauled the README overall. The instructions look really nice now!
