### ISSUE TITLE
Engine Development Environment page

### ISSUE THREAD

**Issue by ghost** [oVirt/ovirt-site#1002]
### Problem
For installing wildfly you need more than latest ovirt release snapshot repository. Same for js-dependencies. 

### Sugestion
There should be link for master snapshot too. So adding another yum install link into Prerequisites - Set Up the Snapshot Repository could do. 

##### Edit
There can also be some kind of warning that building the engine (precisely webadmin) need a lot of RAM memory.

**Comment by sandrobonazzola** [comment]
js-dependencies is not needed anymore. all needed repos are made available by ovirt-release rpms and wildfly is included in snapshot repositories. Please reopen if there are still issues around this.
