### ISSUE TITLE
incorrect filter syntax for ovirt-engine-notifier

### ISSUE THREAD

**Issue by germanovm** [oVirt/ovirt-site#1018]
### Description of the problem
[1] shows examples which prevent ovirt-engine-notifier.service from starting because the filters shown have wrong syntax.

These two examples below throw this:

ovirt-engine-notifier.py: Validation result:
ovirt-engine-notifier.py: stderr: Cannot parse filters
ovirt ovirt-engine-notifier.py: Validation failed returncode is 1:
ovirt-engine-notifier: ERROR run:554 Error: Configuration is invalid

FILTER="include:*ERROR(snmp:) ${FILTER}"
FILTER="include:*ALERT(snmp:) ${FILTER}"

But the syntax is:

FILTER=[PATTERN ...]
PATTERN=include|exclude:event[:severity][(subscriber)]

They are missing the ':' between event and severity. Should be like this:

FILTER="include:*:ERROR(snmp:) ${FILTER}"
FILTER="include:*:ALERT(snmp:) ${FILTER}"

[1] http://www.ovirt.org/documentation/admin-guide/chap-Event_Notifications/

**Comment by mykaul** [comment]
Thanks @germanovm - I believe upstream docs is (strangely) derived from downstream, so we'll need to fix it there and upload (or finally move from upstream to downstream, which is wip).

**Comment by sandrobonazzola** [comment]
Fixed by PR #1643
