### ISSUE TITLE
'httpd' wierd behaviour

### ISSUE THREAD

**Issue by didib** [oVirt/ovirt-site#1025]
### Description of the problem

In [1], 'httpd' appears only once, and is surrounded by angle brackets, '```<httpd>```'.

In the page source code [2], as well as in github's rendering of it, it appears three times, none surrounded.

Something causes two occurrences to disappear and one to be surrounded. Not sure what. Please fix :-)

Thanks!

[1] https://www.ovirt.org/documentation/how-to/migrate-pki-to-sha256/
[2] https://github.com/oVirt/ovirt-site/blob/master/source/documentation/how-to/migrate-pki-to-sha256.html.md

**Comment by didib** [comment]
@duck-rh @JohnMarksRH @garrett any idea?

**Comment by duck-rh** [comment]
Could someone review the linked patch please?

Also please stop pinging Garrett, he is not working on this project anymore, you can ping me instead.

**Comment by didib** [comment]
Reviewed. Sorry, Garrett.
