### ISSUE TITLE
Piwik Stats for Ovirt.org

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#1026]
### Description of the problem

Looking at the stats, there seems to be a discrepancy between the **Actions >> Page Titles** & **Actions >> Page URL** reports. In both instances I am looking at "all visits" for May 2017.
### Steps to reproduce

For example:
Pages titles:
https://stats.phx.ovirt.org/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday&segment=pageUrl%3D%3Dhttps%253A%252F%252Fwww.ovirt.org%252F&updated=2#?idSite=1&period=month&date=2017-05-18&category=General_Actions&subcategory=Actions_SubmenuPageTitles&segment=&popover=

The report shows that the page **Console Client Resources — oVirt** had 2065 page view in May 2017

Compare with Page URL:
https://stats.phx.ovirt.org/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=month&date=2017-05-10&category=General_Actions&subcategory=General_Pages

The report shows that the URL **console-client-resources** (Under admin-guide >> virt) has 563 page views in May 2017.

I would have expected these two searches to yield the same results.

**Comment by duck-rh** [comment]
I thought the start date being different it could explain part of it but no.

The URL page seems to display all the links people tried, even it does not exist, like _/pipermail/users/2015-January/030995.html_ or _/mom_, and as we don't have a 404 page per say but any wrong page displaying a search page so we get all the noise.

So what I can say is we have a lot of _page url not defined_ whereas _page title not defined_ is so low it must be hidden into _Others_. So this probably means measurement is blocked (by adblockers) much more for reporting URLs than reporting title.

**Comment by JohnMarksRH** [comment]
@duck-rh So would you conclude that the page title results presents more reliable data?
And, do we have adblockers software installed on the oVirt site?

**Comment by duck-rh** [comment]
I'm not sure, they don't seem affected the same way.

No the ad blockers are on the client side, like AdBlock plugin for FF for eg.

**Comment by JohnMarksRH** [comment]
@duck-rh Is there anyone else we can ask about this?

**Comment by duck-rh** [comment]
I guess community managers being interesting in these numbers they know better. Maybe @bproffitt would still do the favor to help oVirt?

**Comment by bproffitt** [comment]
I am not familiar with how PiWik gathers stats. But if adblockers are killing the URL reports, then go with the title reports.

Though my next question is, what are the adblockers blocking? We don't have ads on ovirt.org. Or dynamic content.

**Comment by JohnMarksRH** [comment]
Same as Brian. We don't have any ads on the site. Who else can we ask?

**Comment by JohnMarksRH** [comment]
@duck-rh Incidentally, an update for Piwik is available.

**Comment by duck-rh** [comment]
Well, you can see these kind of reports on the web: https://github.com/piwik/piwik/issues/7364

So it's the piwik code itself which is considered a privacy issue and blocked by adblockers.

**Comment by sandrobonazzola** [comment]
@duck-rh any update on this issue?

**Comment by sandrobonazzola** [comment]
closing this as it's not related to ovirt website itself but to piwik. please reopen if I got it wrong.
