### ISSUE TITLE
Why hosted engine is safe ?

### ISSUE THREAD

**Issue by fbacchella** [oVirt/ovirt-site#1036]
I don't use hosted engine because I'm afraid of reliability of it.

What about bootstrap in case of failure ? Missed upgrade ? Database corruption ?

I'm might be wrong but I'm afraid of that.

So a blog entry explaining why it's a safe option, perhaps some basic check and step to recover in case of big problem can help increase usage of this deployment method.

**Comment by mykaul** [comment]
@MarSik @doron-fediuck

**Comment by gregsheremeta** [comment]
Perhaps the updated Self-Hosted Engine Guide's information about backup helps.
https://www.ovirt.org/documentation/self-hosted/Self-Hosted_Engine_Guide.html

**Comment by fbacchella** [comment]
There is nothing is the documentation about a complete shutdown, like a data center power loss. What to check ? How the engine will be restarted. Without explicit documentation about that case, I can't have a look at self-hosted engine.

**Comment by MarSik** [comment]
Missed upgrade and database corruption are scenarios that you have to handle with bare metal engine as well. The backup documentation is a good place to start for those. Hosted engine tools allow you to connect to the serial console and do a manual investigation or fixing.

Hosted engine VM is started by the ovirt-ha-agent process which is managed by systemd and is [autostarted](https://github.com/oVirt/ovirt-hosted-engine-ha/blob/master/initscripts/ovirt-ha-agent.service.in#L21). So the engine recovers properly even when a cluster is cold booted.

**Comment by gregsheremeta** [comment]
> There is nothing is the documentation about a complete shutdown, like a data center power loss. What to check ? How the engine will be restarted. Without explicit documentation about that case, I can't have a look at self-hosted engine.

[This](https://www.ovirt.org/documentation/self-hosted/chap-Introduction.html) might help too:
"Additionally, the Engine is configured to be highly available. If the host running the Engine virtual machine goes into maintenance mode, or fails unexpectedly, the virtual machine will be migrated automatically to another host in the environment. A minimum of two self-hosted Engine hosts are required to support the high availability feature."

If you have more specific questions, please send an email to users@ovirt.org
