### ISSUE TITLE
Move Twitter closer to top of Home Page

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#1043]
### Description of the problem

The Twitter feed on the home page provides a lot of useful information, including upcoming events. However, is a long way down the page and easily missed. Can we please move it up the page and place it where the empty "Upcoming events" section is located. 
"Upcoming Events" can be removed.

I would do it myself but I don't want to mess up the code.

Thank you

**Comment by sandrobonazzola** [comment]
@eldan can you please handle this?

**Comment by duck-rh** [comment]
The twitter feed does not provide a calendar of events, so this is not the same feature.

Also if you ditch away the calendar, then I guess you won't update the events anymore, which means community.redhat.com will not reflect these events anymore.

So I'm not against change, but we clearly need to understand what we're getting rid of and if that's really beneficial to the project. Moving the feed up the page is a good idea though.

**Comment by gregsheremeta** [comment]
we'll be removing twitter feed, actually.
