### ISSUE TITLE
Obsolete videos on documentation main page

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#1045]
### Description of the problem

https://www.ovirt.org/documentation/ has two videos in the head of the page.
The first one shows a 3.1 all-in-one installation, the second one shows creating VMs in a 3.1 environment.
We are now at 4.1 and developing 4.2, videos should be updated with some more recent recordings.

### Help needed from (use @mention to request assistance)
@mykaul

**Comment by mykaul** [comment]
Perhaps have a link to the oVirt youtube channel?
@doron-fediuck  ?

**Comment by sandrobonazzola** [comment]
Videos have been removed.
