### ISSUE TITLE
Wrong link on "oVirt Upgrade Guide"

### ISSUE THREAD

**Issue by karlacio** [oVirt/ovirt-site#1062]
### Description of the problem
On
http://www.ovirt.org/documentation/upgrade-guide/upgrade-guide/#ovirt-upgrade-guide
the link for 3rd chapter "Upgrading to oVirt 4.0" points to the same url of first chapter.

**Comment by tjyang** [comment]
@karlacio , can this issue be closed, LGTM now.

**Comment by sandrobonazzola** [comment]
Thanks, closing.
