### ISSUE TITLE
Spice HTML5 not working

### ISSUE THREAD

**Issue by praburaj1985** [oVirt/ovirt-site#1065]
### Description of the problem
Spice HTML5 not working while am opening the VM guest from the ovirt and am getting a grey screen 

![image](https://user-images.githubusercontent.com/22237394/28019510-d1f8f96c-659e-11e7-86cd-6e38b2a0e9b2.png)

### Steps to reproduce

1.

2.

3.

**Comment by mykaul** [comment]
Issues reported here are for the oVirt *site* (www.ovirt.org), not for the project itself. Please send this issues to the users mailing list (users@ovirt.org).
Thanks,
Y.
