### ISSUE TITLE
Implement Collapsible Menu on Feature Page

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#1091]
### Issue
[Feature Page](http://www.ovirt.org/develop/release-management/features/) is very long

### Solution: Collapsible menu
According to @duck-rh it should be easy to implement a collapsible menu using JS, JQuery. 

### Help needed from: 
@duck @doron-fediuck @mykaul 
Can you suggest someone to implement?

**Comment by gregsheremeta** [comment]
> Can you suggest someone to implement?

me

**Comment by gregsheremeta** [comment]
wont-fix
