### ISSUE TITLE
Organize Feature Page

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#1092]
[Feature page](http://www.ovirt.org/develop/release-management/features/) needs to be organized in a way that will turn it into a more user-friendly resource.

1. The suggestion is to organize **all** features under team categories:
*Gluster * Infra * Integration * Network * Node * SLA * Storage * UX * Virt

Let's get ride of "engine" "uncategorized", etc.

2. In addition, let's add links to main features under their respective release. For example:
http://www.ovirt.org/develop/release-management/releases/3.5/feature/

To make life easier, I have shared a spreadsheet with you:
https://docs.google.com/spreadsheets/d/1c7Di6xz0N0j0rPFRzogBhErJj7rnTCatAZeMOoIbCgU/edit#gid=259246300

If you can complete the spreadsheet, I will push the changes via GitHub.

**Comment by gregsheremeta** [comment]
I cleaned this up.
