### ISSUE TITLE
"Jobs" section

### ISSUE THREAD

**Issue by dankenigsberg** [oVirt/ovirt-site#115]
oVirt is always looking for talented contributors. Red Hat may be able to hire some of them. Please add a "Jobs" tab to the main page, where we can list the descriptions of Linux-savvy Python and enterprise Java developers that we are looking for.

**Comment by tigert** [comment]
We need to draft the content for this first, so it can be linked to, adding the link is very easy.

This actually relates to the whole "getting involved in the oVirt community" message so maybe it should be somehow tied together with that? While we may hire some contributors to let them focus on oVirt full-time, it really involves a lot of the same things every contributor learns when he/she gets involved, so I think these should not be two separate things.

**Comment by bproffitt** [comment]
Dan: Were we going to add jobs just from Red Hat? Or anyone else? How will they be maintained?

**Comment by sandrobonazzola** [comment]
Just my 2 cents here: other than searching for people to work on oVirt project, communities are collecting job offers requiring oVirt knowledge. As an example, Italian community is publicizing on Facebook every known job offer involving oVirt.

oVirt project wise, we have Job category in our Google+ community at https://plus.google.com/communities/109346090491400112913/stream/0c2351d6-340e-4d8c-b074-1e06939d33e2

**Comment by sandrobonazzola** [comment]
Since I replied yesterday to someone searching for a job in oVirt area, here's a good link for those searching: https://www.linkedin.com/jobs/search?keywords=oVirt&location=&locationId=&trk=jobs_jserp_search_button_execute&searchOrigin=JSERP&applyLogin=

**Comment by sandrobonazzola** [comment]
closing this, community resolved this by pushing work advertise to linkedin, facebook and twitter.
