### ISSUE TITLE
Obsolete wiki headers are being reintroduced

### ISSUE THREAD

**Issue by duck-rh** [oVirt/ovirt-site#1175]
### Description of the problem

The following pages are affected:

- source/develop/release-management/features/network/lldp.html.md
- source/develop/release-management/features/network/unrestricted-network-names.html.md
- source/develop/release-management/features/metrics/metrics-store-installation.html.md

I also blocked #1096 but other PRs may be impacted.

Has the contributors' documentation been updated?

**Comment by duck-rh** [comment]
Before closing, once #1382 is merged, I would also appreciate if someone could check and, if needed, update the contributor's documentation.

**Comment by sandrobonazzola** [comment]
#1382 has been merged. @rollandf can you address @duck-rh request?

**Comment by sandrobonazzola** [comment]
@rollandf any update?

**Comment by duck-rh** [comment]
@sandrobonazzola I think we can close this one and follow-up on #1289
