### ISSUE TITLE
Inaccurate ovirt engine picture in architecture page

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#122]
In the new architecture page (http://www.ovirt.org/documentation/architecture/architecture/), overall architecture picture shows that engine supports active-active high availability.

According to Yaniv Kaul(ykaul at redhat.com) in mailing list,

> This is inaccurate - the engine is not highly available in A/A
> architecture. I'd appreciate if you could file an issue for it so we'll fix
> this page.

(copy-paste from https://bugzilla.redhat.com/show_bug.cgi?id=1315120 )

**Comment by sandrobonazzola** [comment]
@rollandf any update on this?

**Comment by rollandf** [comment]
@sandrobonazzola I am not working on this issue.

**Comment by sandrobonazzola** [comment]
@mykaul anyone working on this?

**Comment by gregsheremeta** [comment]
the page (now here) is clearly marked as outdated.
