### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by duck-rh** [oVirt/ovirt-site#1228]
Quack,

Using webcheck I found various errors in the website. The full output needed some filtering but if anyone is interested I can hand-over the full report.

Here you'll find a link of broken links (URL on one line followed by the discovered problems on the next line):

[webcheck_ovirt_badlinks.txt](https://github.com/oVirt/ovirt-site/files/1316977/webcheck_ovirt_badlinks.txt)

**Comment by mykaul** [comment]
On Wed, Sep 20, 2017 at 11:03 AM, Marc Dequènes (Duck) <
notifications@github.com> wrote:

> Quack,
>
> Using webcheck I found various errors in the website. The full output
> needed some filtering but if anyone is interested I can hand-over the full
> report.
>

Thanks.


> Here you'll find a link of broken links (URL on one line followed by the
> discovered problems on the next line):
>
> webcheck_ovirt_badlinks.txt
> <https://github.com/oVirt/ovirt-site/files/1316977/webcheck_ovirt_badlinks.txt>
>

Is this showing the page that has broken links, or the broken links
themselves (and how do we find the origin?)
Y.

**Comment by duck-rh** [comment]
The URL (first line in the couple) is the broken link. I think the impacted pages are also available, let me have a look.

**Comment by duck-rh** [comment]
Here it is:
[webcheck_ovirt_badlinks.txt](https://github.com/oVirt/ovirt-site/files/1317420/webcheck_ovirt_badlinks.txt)

Not sure how to format this better.

**Comment by eedri** [comment]
Have you got a chance to review the report I sent to infra list, created by linkchecker? 
Attaching here as well.  ( HTML format, I filtered the .png links because there were over 12K of broken ones, w/o them the list is around 2300 ). 
[ovirt.org-no-png-broken-links.html.gz](https://github.com/oVirt/ovirt-site/files/1329892/ovirt.org-no-png-broken-links.html.gz)

**Comment by eedri** [comment]
Each broken link has it's parent as well, so you can know what is broken.

**Comment by duck-rh** [comment]
Thanks @eedri 

I think reporting here is better, as most people involved in the website probably don't follow the infra list closely. But we might want to tell them to drop by more often and we can discuss tooling difficulties, site cleanups… I try to follow changes and reply to questions here, but I might miss things.

**Comment by sandrobonazzola** [comment]
@duck-rh can you please re-run the check and provide updated list?

**Comment by duck-rh** [comment]
@sandrobonazzola I opened #1991 because some links displeased webcheck and they were broken anyway. Please note the way to escape brackets when writing examples. Do you have any place for editing policy/advice where we could put this?

I regenerated the report and tried to filter out as many false positive as possible:
[webcheck_ovirt_badlinks.txt](https://github.com/oVirt/ovirt-site/files/3166026/webcheck_ovirt_badlinks.txt)

\\_o<

**Comment by darkfiberiru** [comment]
@sandrobonazzola Here is an update list https://gist.github.com/darkfiberiru/b059c372e690ead5364d73190916a401
with references to where each link is in each file.

**Comment by darkfiberiru** [comment]
I may try to cleanup if I have some time. I already fixed one I believe here #2085

**Comment by darkfiberiru** [comment]
@duck-rh  Please see above for a current check I ran on the site and first fix. Though I'm not 100% sure on fix

**Comment by duck-rh** [comment]
@darkfiberiru I saw the fix after my reply, sorry. I just don't know the content and was not sure either, so I cannot review it. maybe @sandrobonazzola ?

**Comment by sandrobonazzola** [comment]
@duck-rh have we still got broken links? can you provide an updated list?

**Comment by duck-rh** [comment]
There is progress but still many. Certain problems seems to be related to site reorganization without looking for _reverse dependencies_.
[webcheck_ovirt_badlinks.txt](https://github.com/oVirt/ovirt-site/files/4004798/webcheck_ovirt_badlinks.txt)

**Comment by duck-rh** [comment]
@sandrobonazzola could you pingme when all the desired RHV docs are imported so I can update the list of broken links please?

**Comment by sandrobonazzola** [comment]
All internal links have been fixed, automation is in place now to prevent it to get broken again.
There are still a few external links to be fixed but at least the site is consistent.
