### ISSUE TITLE
old.ovirt.org indexed

### ISSUE THREAD

**Issue by didib** [oVirt/ovirt-site#124]
Now noticed that a google search returned also results from old.ovirt.org.

If we intend to drop it by end of current month, which btw seems
pretty immature to me - perhaps wait half a year or so, we better stop
google from searching and/or returning results from it. robots.txt
should have been enough if done beforehand, not sure what tools exist
now. Adding one won't hurt anyway. Obviously google has specific tools
for webmasters, we probably want if possible something general for
many search engines.

Already reported to infra mailing list [1], as most of not all of the above is hardly relevant to the new site. Opening also this issue per Mikey's request.

[1] http://lists.ovirt.org/pipermail/infra/2016-March/013636.html

**Comment by sandrobonazzola** [comment]
old.ovirt.org is offline, I think we can close this issue.
