### ISSUE TITLE
The wiki is *GONE*

### ISSUE THREAD

**Issue by duck-rh** [oVirt/ovirt-site#1289]
The old wiki_* headers were removed in all pages but people are creating new pages with such headers.

So this is a double mistake because these headers were aimed at tracking which page came from the old wiki, which newly created pages clearly are not.

So the goal of this BR is:
* teach people to stop using these headers
* cleanup the new pages containing them

**Comment by nirs** [comment]
Teaching people to stop using these headers is hard, but we can add a test for new features pages, failing the build if unwanted headers are found.

The old feature pages that should contain the headers can be blacklisted from this test.

**Comment by sandrobonazzola** [comment]
@nirs any update on adding a test for this?

**Comment by sandrobonazzola** [comment]
@duck-rh , @nirs any progress on this?

**Comment by duck-rh** [comment]
@sandrobonazzola I totally forgot about it, I made a PR to make amends :-)

@nirs thanks for the idea
