### ISSUE TITLE
No breadcumbs

### ISSUE THREAD

**Issue by david-caro** [oVirt/ovirt-site#13]
the only way to navigate back is hitting the back button, in the wiki you have some hirachized breadcumbs links that help navigating topics

**Comment by thatdocslady** [comment]
@david-caro are you referring to the Table of Contents that you sometimes see (like here http://www.ovirt.org/OVirt_3.6_Release_Management#Key_Proposed_Changes)?

@garrett can we solve this with a sidebar like in the feature pages? or some other suggestion?

**Comment by garrett** [comment]
A sidebar seems odd for this type of thing. I guess I can look into overriding pages in a layout to see if they're more than a level deep and add some breadcrumb navigation if so?

**Comment by thatdocslady** [comment]
@garrett sounds good, I think whatever we choose to implement as long as it's fairly simple to maintain and doesn't look out of place will help here, the sidebar was just an idea because we already use it elsewhere.

**Comment by garrett** [comment]
Well, maintenance would be set it and forget it. It would basically pull apart the URL and link to each piece if depth > 1 or > 2 (whatever works best). And there should probably be an option to disable it from rendering on a page by page basis.

**Comment by garrett** [comment]
Here's a screenshot (with the debugging bar turned off, which will be the case when the site goes to production):

![screen shot 2015-12-18 at 11 59 03](https://cloud.githubusercontent.com/assets/10246/11895413/c4d3e314-a57e-11e5-84ef-1e3ca8f4b2f2.png)

The breadcrubs bar intentionally does not show up at pages of 0 or 1 in depth, but for everything after. That is, it will not show up for the home page or top-level pages in navigation (as it would be redundant), but it should be there for for everything else below. (Thankfully I made that auto-indexing enhancement recently, which makes the breadcrumbs much more useful.)

**Comment by thatdocslady** [comment]
@garrett this is perfect! @david-caro what do you think? this is similar breadcrumb setup to many documentation libraries, and will basically replace the auto-generated wiki-style table of content (except for pages that already have a sidebar).
