### ISSUE TITLE
Blog breadcrumb partially hidden by top bar

### ISSUE THREAD

**Issue by jniederm** [oVirt/ovirt-site#1305]
### Description of the problem
![image](https://user-images.githubusercontent.com/5278760/32325702-4fa920b8-bfd0-11e7-974f-c0307d84fb7c.png)

### Steps to reproduce

1. Open any blog, e.g. https://www.ovirt.org/blog/2017/05/higher-performance-for-python-sdk/

**Comment by rollandf** [comment]
Fixed by #1343
