### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by MarSik** [oVirt/ovirt-site#1348]
### Description of the problem

There is a broken link on https://www.ovirt.org/documentation/vmm-guide/Virtual_Machine_Management_Guide/ pointing to https://www.ovirt.org/documentation/vmm-guide/Virtual_Machine_Management_Guide/appe-Reference_Settings_in_Administration_Portal_and_User_Portal_Windows

**Comment by sandrobonazzola** [comment]
Fixed by PR #1456
