### ISSUE TITLE
slide-decks.html.md - broken links

### ISSUE THREAD

**Issue by scrat14** [oVirt/ovirt-site#135]
Links to documents in ovirt.org slide decks page are broken, as they point to documents uploaded to old images/ or wp-content/upload folders, which aren't available anymore.
Are these ODPs and PDFs migrated to the new site - can't find them in git repository...

**Comment by sandrobonazzola** [comment]
Mikey we need a decision on where we need to store slides.

**Comment by garrett** [comment]
Related to #77

**Comment by gregsheremeta** [comment]
closing old issues
