### ISSUE TITLE
MAC address pool setting referenced at the wrong place (DC)

### ISSUE THREAD

**Issue by jan-zmeskal** [oVirt/ovirt-site#1363]
### Description of the problem
In Data Centers chapter of documentation, there is a section [Creating a New Data Center](https://ovirt.org/documentation/admin-guide/chap-Data_Centers/#creating-a-new-data-center). 
Step 5 tells users that MAC address pool can be configured from New Data Center page, but this configuration is available when editing Cluster, not Data Center.

**Comment by sandrobonazzola** [comment]
@jan-zmeskal referenced page doesn't exist anymore, can you please check documentation again and provide feedback if we can close this issue?

**Comment by jan-zmeskal** [comment]
MAC address pool is now correctly referenced in creating a new cluster chapter: https://ovirt.org/documentation/administration_guide/#Creating_a_New_Cluster
Therefore closing
