### ISSUE TITLE
Admin guide markup corrupts 1/3 of guide

### ISSUE THREAD

**Issue by darrylb123** [oVirt/ovirt-site#138]
The markup after 'Installing Guest Agents and Drivers' corrupts the remainder of the document. Looks like there is some html that is not parsed by the markdown engine and breaks everything afterwards.

This is the raw code where it breaks. I notice it renders properly on github just not on the web site.

<dl>
<dt>
Installing the agents and drivers on Red Hat Enterprise Linux guests

<dd>
All of the drivers are included in the base channel for RHN-registered Red Hat Enterprise Linux virtual machines. They can be installed using the `yum install rhevm-guest-agent` command. Your RHEL guest must be subscribed to the `Red Hat Enterprise Virt Agent` channel to install the agents. In Red Hat Enterprise Linux 5, this channel is labeled `rhel-x86_64-rhev-agent-5-server`. In Red Hat Enterprise Linux 6, the channel is labeled `rhel-x86_64-rhev-agent-6-server`.

<dt>
Installing the agents and drivers on Windows guests

<dd>
The guest tools ISO is `ovirt-guest-tools-iso.rpm`, an RPM file installed on oVirt. After installing oVirt, the guest tools ISO can be found at `/usr/share/rhev-guest-tools-iso/ovirt-tools-setup.iso`. When setting up oVirt, if you have created a local storage share for an ISO storage domain, the ISO file is automatically copied to the ISO storage domain. In this case the ISO image is automatically attached to Windows guests when they are created. Otherwise, the ISO must be manually attached to Windows guests for the tools and agents to be installed. Updated versions of the ISO file must be manually attached to running Windows virtual machines to install updated versions of the tools and drivers. If the APT service is enabled on virtual machines, the updated ISO files will be automatically attached.

</dl>
##### Automating Guest Additions on Windows Guests with oVirt Application Provisioning Tool(APT)

oVirt Application Provisioning Tool (APT) is a Windows service that can be installed in Windows virtual machines and templates. Attach the guest tools ISO file to your Windows virtual machine and **ovirt-Application Provisioning.exe** automatically runs to install the APT service.

When the APT service is installed on a virtual machine, attached ISO files are automatically scanned. When the service recognizes a valid oVirt guest tools ISO, and no other guest tools are installed, the APT service installs the guest tools. If guest tools are installed, and the ISO image contains newer versions of the tools, an upgrade is automatically performed.

When the APT service has successfully installed or upgraded guest tools on a virtual machine, the virtual machine is automatically rebooted.

##### oVirt Guest Drivers and Guest Agents

oVirt provides customized drivers and guest tools to use with Windows and Red Hat Enterprise Linux guests. The drivers allow guests to use enhanced virtual devices that perform better than emulated devices; the guest agents facilitate communication between the guest and oVirt.

⁠

**Table 8.15. oVirt Guest Drivers**

<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"><p>Driver</p></th>
<th align="left"><p>Description</p></th>
<th align="left"><p>Works on</p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><p><code>virtio-net</code></p></td>
<td align="left"><p>Paravirtualized network driver provides enhanced performance over emulated devices like rtl.</p></td>
<td align="left"><p>Server and Desktop.</p></td>
</tr>
<tr class="even">
<td align="left"><p><code>virtio-block</code></p></td>
<td align="left"><p>Paravirtualized HDD driver offers increased I/O performance over emulated devices like IDE by optimizing the coordination and communication between the guest and the hypervisor. The driver complements the software implementation of the virtio-device used by the host to play the role of a hardware device.</p></td>
<td align="left"><p>Server and Desktop.</p></td>
</tr>
<tr class="odd">
<td align="left"><p><code>virtio-scsi</code></p></td>
<td align="left"><p>Paravirtualized iSCSI HDD driver offers similar functionality to the virtio-block device, with some additional enhancements. In particular, this driver supports adding hundreds of devices, and names devices using the standard SCSI device naming scheme.</p></td>
<td align="left"><p>Server and Desktop.</p></td>
</tr>
<tr class="even">
<td align="left"><p><code>virtio-serial</code></p></td>
<td align="left"><p>Virtio-serial provides support for multiple serial ports. The improved performance is used for fast communication between the guest and the host that avoids network complications. This fast communication is required for the guest agents and for other features such as clipboard copy-paste between the guest and the host and logging.</p></td>
<td align="left"><p>Server and Desktop.</p></td>
</tr>
<tr class="odd">
<td align="left"><p><code>virtio-balloon</code></p></td>
<td align="left"><p>Virtio-balloon is used to control the amount of memory a guest actually accesses. It offers improved memory over-commitment. The balloon drivers are installed for future compatibility but not used by default in oVirt 3.1 or higher.</p></td>
<td align="left"><p>Server and Desktop.</p></td>
</tr>
<tr class="even">
<td align="left"><p><code>qxl</code></p></td>
<td align="left"><p>A paravirtualized display driver reduces CPU usage on the host and provides better performance through reduced network bandwidth on most workloads.</p></td>
<td align="left"><p>Server and Desktop.</p></td>
</tr>
</tbody>
</table>

⁠

**Table 8.16. oVirt Guest Agents and Tools**

<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"><p>Guest agent/tool</p></th>
<th align="left"><p>Description</p></th>
<th align="left"><p>Works on</p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><p><code>ovirt-guest-agent</code></p></td>
<td align="left"><p>Allows oVirt to receive guest internal events and information such as IP address and installed applications. Also allows oVirt to execute specific commands, such as shut down or reboot, on a guest. On Red Hat Enterprise Linux 6 and higher guests, the ovirt-guest-agent installs <strong>tuned</strong> on your virtual machine and configures it to use an optimized, virtualized-guest profile.</p></td>
<td align="left"><p>Server and Desktop.</p></td>
</tr>
<tr class="even">
<td align="left"><p><code>spice-agent</code></p></td>
<td align="left"><p>The SPICE agent supports multiple monitors and is responsible for client-mouse-mode support to provide a better user experience and improved responsiveness than the QEMU emulation. Cursor capture is not needed in client-mouse-mode. The SPICE agent reduces bandwidth usage when used over a wide area network by reducing the display level, including color depth, disabling wallpaper, font smoothing, and animation. The SPICE agent enables clipboard support allowing cut and paste operations for both text and images between client and guest, and automatic guest display setting according to client-side settings. On Windows guests, the SPICE agent consists of vdservice and vdagent.</p></td>
<td align="left"><p>Server and Desktop.</p></td>
</tr>
<tr class="odd">
<td align="left"><p><code>ovirt-sso</code></p></td>
<td align="left"><p>An agent that enables users to automatically log in to their virtual machines based on the credentials used to access oVirt.</p></td>
<td align="left"><p>Desktop.</p></td>
</tr>
<tr class="even">
<td align="left"><p><code>ovirt-usb</code></p></td>
<td align="left"><p>A component that contains drivers and services for Legacy USB support (version 3.0 and earlier) on guests. It is needed for accessing a USB device that is plugged into the client machine. <code>ovirt-USB Client</code> is needed on the client side.</p></td>
<td align="left"><p>Desktop.</p></td>
</tr>
</tbody>
</table>

**Comment by sandrobonazzola** [comment]
#140 should fix this issue

**Comment by sandrobonazzola** [comment]
fixed
