### ISSUE TITLE
Metrics documentation needs update

### ISSUE THREAD

**Issue by StLuke** [oVirt/ovirt-site#1387]
### Description of the problem
See the documentation of oVirt Metrics Store Setup.
Should be updated to latest stepes required for metrics-store. (MUX namespaces are defined within vars.yaml, link is not working anymore.

https://github.com/oVirt/ovirt-site/blob/master/source/develop/release-management/features/metrics/metrics-store-installation.html.md 

### Help needed from (use @mention to request assistance)
@sradco

**Comment by sandrobonazzola** [comment]
This should have been fixed by PR #1388. 
Please review https://ovirt.org/develop/release-management/features/metrics/metrics-store-installation/
