### ISSUE TITLE
ovirt

### ISSUE THREAD

**Issue by geyuan001** [oVirt/ovirt-site#1476]
### Steps to reproduce
1.
![1515570760 1](https://user-images.githubusercontent.com/27494361/34761694-d2f49c2e-f61f-11e7-904e-94930772a230.png)

2.
![167617598666137753](https://user-images.githubusercontent.com/27494361/34761697-d8020a08-f61f-11e7-944d-3ce04bcfffa7.jpg)

3.

**Comment by mykaul** [comment]
Hi,

This issue tracker is for issues in the ovirt.org website. Please use Bugzilla to open bugs on ovirt @ https://bugzilla.redhat.com/enter_bug.cgi?classification=oVirt

Also, include version information and logs - not just screenshots.
