### ISSUE TITLE
Ovirt 4.1 cannot installed vm's OS

### ISSUE THREAD

**Issue by chenqifeng28** [oVirt/ovirt-site#1492]
### Description of the problem
I have installed a Ovirt in my computer with VMware workstation, but now I cannot installed the VM's os,Please help to solve the problem, thanks!
### Steps to reproduce

1.THe problem's screenshot :
![1](https://user-images.githubusercontent.com/32876594/35144701-47c12276-fd40-11e7-9550-3762770617f9.jpg)
![2](https://user-images.githubusercontent.com/32876594/35145445-c7a5ce7c-fd42-11e7-8130-9495bd4ef71a.jpg)

2.[root@engine ~]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)

 [root@engine ~]# df -TH
文件系统                类型      容量  已用  可用 已用% 挂载点
/dev/mapper/rootvg-root xfs        38G  7.5G   31G   20% /
devtmpfs                devtmpfs  2.0G     0  2.0G    0% /dev
tmpfs                   tmpfs     2.0G     0  2.0G    0% /dev/shm
tmpfs                   tmpfs     2.0G  9.2M  2.0G    1% /run
tmpfs                   tmpfs     2.0G     0  2.0G    0% /sys/fs/cgroup
/dev/sda1               xfs       1.1G  198M  866M   19% /boot
tmpfs                   tmpfs     396M     0  396M    0% /run/user/03.

3. ovirt: ovirt 4.1.8
[root@engine ~]# rpm -qa |grep ovirt-engine
ovirt-engine-4.1.8.2-1.el7.centos.noarch

Before I ask this question, I saw a similar problem on GitHub, but given the amount of reply I need to log on to the website to view the solution, because I do not have Red Hat's account can not view, please help provide the relevant information, if Also need me to provide relevant information, please tell me, thank you!

**Comment by mykaul** [comment]
Please use the users mailing list to ask questions (users@ovirt.org) - it's a better venue to get responses.
I assume your issue is that you need to enabled nested virtualization on your VMware workstation, so that VM could be used as a hypervisor.

**Comment by chenqifeng28** [comment]
thx , @mykaul
