### ISSUE TITLE
The names there are crossed out on community page

### ISSUE THREAD

**Issue by david-caro** [oVirt/ovirt-site#15]
at http://beta-ovirtweb.rhcloud.com/community/

**Comment by garrett** [comment]
Yep. That's a debugging style to show that the link no longer works for special wiki pages. It should be disabled before the site is published live.

It's defined as `.broken-link` in line 182 of `site.sass`.

https://github.com/oVirt/ovirt-site/blob/master/source/stylesheets/lib/site.sass#L182-L186

This is intentional, to make those non-working links highly visible. Someone needs to go through all the documents and fix the content.

**Comment by garrett** [comment]
Here's a list of all resulting pages:

* community/activities/gamification/index.html
* community/events/archives/events/index.html
* community/events/archives/workshop/global-workshops/index.html
* community/events/archives/workshop/intel-workshop-may-2013/index.html
* community/events/archives/workshop/netapp-workshop-january-2013/index.html
* community/get-involved/wiki-rules-and-etiquette/index.html
* community/index.html
* develop/api/design/using-rest-api-in-web-ui/index.html
* develop/api/design/vm-parameters-in-rest-api-for-vm-pools/index.html
* develop/developer-guide/arch-linux/index.html
* develop/developer-guide/engine/engine-development-environment/index.html
* develop/developer-guide/events/configuration-event-subscribers/index.html
* develop/developer-guide/sample-user-portals/index.html
* develop/developer-guide/ui-plugin-tutorial/index.html
* develop/developer-guide/vdsm/libvirt-performance-scalability/index.html
* develop/developer-guide/vdsm/momvdsmseparation/index.html
* develop/developer-guide/vdsm/scalability-sampling/index.html
* develop/developer-guide/vdsm/vm-startup/index.html
* develop/dev-process/build-binary-package/index.html
* develop/infra/infrastructure/index.html
* develop/projects/multiple-storage-domains/index.html
* develop/projects/node/ipv6-support/index.html
* develop/projects/node/solution-for-2-nodes/index.html
* develop/projects/project-integration/index.html
* develop/projects/project-movirt/index.html
* develop/release-management/features/3.6-proposed-feature/blank-to-defaults/index.html
* develop/release-management/features/3.6-proposed-feature/copy-disks/index.html
* develop/release-management/features/3.6-proposed-feature/iothreads-support/index.html
* develop/release-management/features/3.6-proposed-feature/ppc64le-support/index.html
* develop/release-management/features/3.6-proposed-feature/upgrademanager/index.html
* develop/release-management/features/affinity-rules-enforcement-manager/index.html
* develop/release-management/features/backupawareness/index.html
* develop/release-management/features/boot/index.html
* develop/release-management/features/cinderglance-docker-integration/index.html
* develop/release-management/features/cloud/addingkeystoneurltoexternalproviders/index.html
* develop/release-management/features/cloud/neutronvirtualappliance/index.html
* develop/release-management/features/copy-disks/index.html
* develop/release-management/features/debian-support-for-hosts/index.html
* develop/release-management/features/doctor-rest/index.html
* develop/release-management/features/engine/avoid-ip-spoofing/index.html
* develop/release-management/features/engine/cluster-parameters-override/index.html
* develop/release-management/features/engine/commandcoordinator/index.html
* develop/release-management/features/engine/engine-backup/index.html
* develop/release-management/features/engine/engine-cleanup/index.html
* develop/release-management/features/engine/engine-nic-health-check/index.html
* develop/release-management/features/engine/engine-snmp/index.html
* develop/release-management/features/engine/feature-level-support/index.html
* develop/release-management/features/engine/fedora-21-support/index.html
* develop/release-management/features/engine/fedora-22-support/index.html
* develop/release-management/features/engine/get-route/index.html
* develop/release-management/features/engine/guest-reboot/index.html
* develop/release-management/features/engine/hostdeployprotocol/index.html
* develop/release-management/features/engine/hostdev-passthrough/index.html
* develop/release-management/features/engine/hosted-engine/index.html
* develop/release-management/features/engine/integrating-libosinfo-with-engine/index.html
* develop/release-management/features/engine/migration-of-local-dwh-reports-to-remote/index.html
* develop/release-management/features/engine/reportguestdiskslogicaldevicename/index.html
* develop/release-management/features/engine/self-hosted-engine-fc-support/index.html
* develop/release-management/features/engine/self-hosted-engine-gluster-support/index.html
* develop/release-management/features/engine/self-hosted-engine-hyper-converged-gluster-support/index.html
* develop/release-management/features/engine/self-hosted-engine/index.html
* develop/release-management/features/engine/self-hosted-engine-iscsi-support/index.html
* develop/release-management/features/engine/self-hosted-engine-maintenance-flows/index.html
* develop/release-management/features/engine/separate-dwh-host/index.html
* develop/release-management/features/engine/separate-reports-host/index.html
* develop/release-management/features/engine/serial-console/index.html
* develop/release-management/features/engine/sr-iov/index.html
* develop/release-management/features/engine/upgrademanager/index.html
* develop/release-management/features/engine/vm-icons/index.html
* develop/release-management/features/engine/watchdog-engine-support/index.html
* develop/release-management/features/engine/windows-guest-tools/index.html
* develop/release-management/features/extension-tester-tool/index.html
* develop/release-management/features/feature-template/index.html
* develop/release-management/features/genericregistration/index.html
* develop/release-management/features/heapplianceflow/index.html
* develop/release-management/features/hosted-engine-add-hosts-with-web-ui/index.html
* develop/release-management/features/hosted-engine-configuration-on-shared-storage/index.html
* develop/release-management/features/hot-plug-memory/index.html
* develop/release-management/features/infra/asynctaskmanagerchanges-3.3/index.html
* develop/release-management/features/infra/asynctaskmanagerchanges/index.html
* develop/release-management/features/infra/authentication-rewrite/index.html
* develop/release-management/features/infra/bootstrap-improvements/index.html
* develop/release-management/features/infra/clonevmfromsnapshot/index.html
* develop/release-management/features/infra/custompropertiessheet/index.html
* develop/release-management/features/infra/dbschemaversioncheck/index.html
* develop/release-management/features/infra/detailedclonevmfromsnapshot/index.html
* develop/release-management/features/infra/detailedhostpmproxypreferences/index.html
* develop/release-management/features/infra/detailedlockmechanism/index.html
* develop/release-management/features/infra/detailedpmhealthcheck/index.html
* develop/release-management/features/infra/drbd/index.html
* develop/release-management/features/infra/externaltasks/index.html
* develop/release-management/features/infra/hostpmproxypreferences/index.html
* develop/release-management/features/infra/kerberos-support-in-sdks-and-cli/index.html
* develop/release-management/features/infra/microthreading/index.html
* develop/release-management/features/infra/one-certificate-key-pair-per-nic/index.html
* develop/release-management/features/infra/pki-improvements/index.html
* develop/release-management/features/infra/pki/index.html
* develop/release-management/features/infra/pkireduce/index.html
* develop/release-management/features/infra/pmhealthcheck/index.html
* develop/release-management/features/infra/reloadableconfiguration/index.html
* develop/release-management/features/infra/restsessionmanagement/index.html
* develop/release-management/features/infra/runningcommandsonendactionfailure/index.html
* develop/release-management/features/infra/ssh-abilities/index.html
* develop/release-management/features/infra/sso/index.html
* develop/release-management/features/infra/sso-method-control/index.html
* develop/release-management/features/infra/taskmanagerdetailed/index.html
* develop/release-management/features/infra/taskmanager/index.html
* develop/release-management/features/infra/uniformssosupport/index.html
* develop/release-management/features/integration/allinone/index.html
* develop/release-management/features/integration/otopi-infra-migration/index.html
* develop/release-management/features/integration/ovirtappliance/index.html
* develop/release-management/features/integration/remotedb/index.html
* develop/release-management/features/integration/websocketproxy-on-a-separate-host/index.html
* develop/release-management/features/iothreads-support/index.html
* develop/release-management/features/katellointegration/index.html
* develop/release-management/features/kernel-cmdline/index.html
* develop/release-management/features/linux-bridges-libvirt-management/index.html
* develop/release-management/features/live-rebase-on-centos-7/index.html
* develop/release-management/features/live-storage-migration-between-mixed-domains/index.html
* develop/release-management/features/lun-resize/index.html
* develop/release-management/features/memorybasedbalancing/index.html
* develop/release-management/features/migration-enhancements/index.html
* develop/release-management/features/network/apidatacenternetworks/index.html
* develop/release-management/features/network/arbitraryvlandevicename/index.html
* develop/release-management/features/network/bridgeless-networking/index.html
* develop/release-management/features/network/bridgeless-networks/index.html
* develop/release-management/features/network/detailedhostnetworkingapi/index.html
* develop/release-management/features/network/detailednetworklinking/index.html
* develop/release-management/features/network/detailed-osn-integration/index.html
* develop/release-management/features/network/device-custom-properties/index.html
* develop/release-management/features/network/ethtool-options/index.html
* develop/release-management/features/network/hostnetworkingapi/index.html
* develop/release-management/features/network/hotplugnic/index.html
* develop/release-management/features/network/isolatednetworks/index.html
* develop/release-management/features/network/migration-network/index.html
* develop/release-management/features/network/multiple-gateways/index.html
* develop/release-management/features/network/network-custom-properties/index.html
* develop/release-management/features/network/networkfiltering/index.html
* develop/release-management/features/network/networklabels/index.html
* develop/release-management/features/network/networklinking/index.html
* develop/release-management/features/network/networkmaintab/index.html
* develop/release-management/features/network/network-qos-detailed-design/index.html
* develop/release-management/features/network/networkreloaded/index.html
* develop/release-management/features/network/nicless-network/index.html
* develop/release-management/features/network/normalized-ovirtmgmt-initialization/index.html
* develop/release-management/features/network/osn-integration/index.html
* develop/release-management/features/network/portmirroring/index.html
* develop/release-management/features/network/predictable-vnic-order/index.html
* develop/release-management/features/network/setupnetworks/index.html
* develop/release-management/features/network/ucs-integration/index.html
* develop/release-management/features/network/unrestricted-network-names/index.html
* develop/release-management/features/network/update-device-hooks/index.html
* develop/release-management/features/node/buildtoolmigration/index.html
* develop/release-management/features/node/cockpit/index.html
* develop/release-management/features/node/dbusbackend/index.html
* develop/release-management/features/node/diagnostic-page/index.html
* develop/release-management/features/node/docker-integration/index.html
* develop/release-management/features/node/featurepublishing/index.html
* develop/release-management/features/node/glusterfs-support/index.html
* develop/release-management/features/node/ipv6-support/index.html
* develop/release-management/features/node/kimchiplugin/index.html
* develop/release-management/features/node/nic-bonding/index.html
* develop/release-management/features/node/nodeautomation/index.html
* develop/release-management/features/node/node.next/index.html
* develop/release-management/features/node/openvswitchsupport/index.html
* develop/release-management/features/node/packagerefactoring/index.html
* develop/release-management/features/node/pluginliveinstall/index.html
* develop/release-management/features/node/puppet-plugin/index.html
* develop/release-management/features/node/software-iscsi-root/index.html
* develop/release-management/features/node/storageandinstallermodulerewrite/index.html
* develop/release-management/features/node/subpackages/index.html
* develop/release-management/features/node/tuiredesign/index.html
* develop/release-management/features/node/universal-image/index.html
* develop/release-management/features/node/upgrade-tool/index.html
* develop/release-management/features/node/urwid-tui/index.html
* develop/release-management/features/ovmf/index.html
* develop/release-management/features/patternfly-tooltips/index.html
* develop/release-management/features/pendingresourcemanager/index.html
* develop/release-management/features/plugins/plugins/index.html
* develop/release-management/features/scheduler-policies/index.html
* develop/release-management/features/serial-console-in-cli/index.html
* develop/release-management/features/sla/aggregate-qos/index.html
* develop/release-management/features/sla/automatic-scaling/index.html
* develop/release-management/features/sla/blkio-support/index.html
* develop/release-management/features/sla/cpu-host-support/index.html
* develop/release-management/features/sla/cpu-sla/index.html
* develop/release-management/features/sla/cpu-thread-handling/index.html
* develop/release-management/features/sla/detailed-numa-and-virtual-numa/index.html
* develop/release-management/features/sla/detailedquota/index.html
* develop/release-management/features/sla/drools-planner-scheduler/index.html
* develop/release-management/features/sla/even-vm-count-distribution/index.html
* develop/release-management/features/sla/external-scheduling-proxy/index.html
* develop/release-management/features/sla/ha-vm-reservation-detaileddesign/index.html
* develop/release-management/features/sla/ha-vm-reservation/index.html
* develop/release-management/features/sla/memory-hotplug/index.html
* develop/release-management/features/sla/minimum-guaranteed-memory/index.html
* develop/release-management/features/sla/numa-and-virtual-numa/index.html
* develop/release-management/features/sla/optaplanner/index.html
* develop/release-management/features/sla/ovirtschedulerapi/index.html
* develop/release-management/features/sla/ovirtscheduler/index.html
* develop/release-management/features/sla/quota/index.html
* develop/release-management/features/sla/sla-mom-ballooning-tp/index.html
* develop/release-management/features/sla/sla-mom/index.html
* develop/release-management/features/sla/trusted-compute-pools/index.html
* develop/release-management/features/sla/vm-affinity/index.html
* develop/release-management/features/sla/vm-coredump/index.html
* develop/release-management/features/sla/xbzrle-and-auto-convergence/index.html
* develop/release-management/features/splash/index.html
* develop/release-management/features/storage/backup-provider/index.html
* develop/release-management/features/storage/cinder-integration/index.html
* develop/release-management/features/storage/decommission-master-domain-and-spm/index.html
* develop/release-management/features/storage/detailedfloatingdisk/index.html
* develop/release-management/features/storage/detailed-gluster-geo-rep/index.html
* develop/release-management/features/storage/detailed-gluster-volume-asynchronous-tasks-management/index.html
* develop/release-management/features/storage/detailedsharedrawdisk/index.html
* develop/release-management/features/storage/disk-hooks/index.html
* develop/release-management/features/storage/domain-scan/index.html
* develop/release-management/features/storage/floatingdisk/index.html
* develop/release-management/features/storage/glance-integration/index.html
* develop/release-management/features/storage/glusterfs-hyperconvergence/index.html
* develop/release-management/features/storage/hotplug/index.html
* develop/release-management/features/storage/importmorethanonce/index.html
* develop/release-management/features/storage/ioprocess/index.html
* develop/release-management/features/storage/live-merge/index.html
* develop/release-management/features/storage/moveascopyanddelete/index.html
* develop/release-management/features/storage/move-disk-two-phase-commit/index.html
* develop/release-management/features/storage/multiplestoragedomains/index.html
* develop/release-management/features/storage/orphaned-images/index.html
* develop/release-management/features/storage/ovfautoupdater/index.html
* develop/release-management/features/storage/read-only-disk/index.html
* develop/release-management/features/storage/sanlock-fencing/index.html
* develop/release-management/features/storage/serial-execution-of-asynchronous-tasks-detailed-design/index.html
* develop/release-management/features/storage/serial-execution-of-asynchronous-tasks/index.html
* develop/release-management/features/storage/single-disk-snapshot/index.html
* develop/release-management/features/storage/snapshots-overview/index.html
* develop/release-management/features/storage/spmpriority/index.html
* develop/release-management/features/storage/storagepool-metadata-removal/index.html
* develop/release-management/features/storage/virtio-scsi/index.html
* develop/release-management/features/ui/index.html
* develop/release-management/features/ux/branding/index.html
* develop/release-management/features/ux/cssgrids/index.html
* develop/release-management/features/ux/design/network/jumbo-frames/index.html
* develop/release-management/features/ux/design/stabledeviceaddresses/index.html
* develop/release-management/features/ux/detailedexternalevents/index.html
* develop/release-management/features/ux/detailedexternaltasks/index.html
* develop/release-management/features/ux/detailedhostpmmultipleagents/index.html
* develop/release-management/features/ux/detailedhotplugnic/index.html
* develop/release-management/features/ux/detailedstabledeviceaddresses/index.html
* develop/release-management/features/ux/entityhealthstatus/index.html
* develop/release-management/features/ux/frontendrefactor/index.html
* develop/release-management/features/ux/gwt-platform-upgrade/index.html
* develop/release-management/features/ux/hostbiosinfo/index.html
* develop/release-management/features/ux/hosthardwareinfo/index.html
* develop/release-management/features/ux/hostpmmultipleagents/index.html
* develop/release-management/features/ux/i18n/index.html
* develop/release-management/features/ux/jasper-in-webadmin/index.html
* develop/release-management/features/ux/lowerresolutionsupport/index.html
* develop/release-management/features/ux/newlookandfeelpatternflyphase1/index.html
* develop/release-management/features/ux/reports-dashboard/index.html
* develop/release-management/features/ux/uiplugins/index.html
* develop/release-management/features/ux/uirefreshsynchronization/index.html
* develop/release-management/features/vdsm/jsonrpc/index.html
* develop/release-management/features/vdsm/libvdsm/index.html
* develop/release-management/features/vdsm/python3-compatibility/index.html
* develop/release-management/features/vdsm/supervdsm-service/index.html
* develop/release-management/features/vdsm/vdsm-plugin/index.html
* develop/release-management/features/vdsm/vdsm-vm-query-api/index.html
* develop/release-management/features/virt/blank-to-defaults/index.html
* develop/release-management/features/virt/clone-vm/index.html
* develop/release-management/features/virt/cluster-emulation-modes/index.html
* develop/release-management/features/virt/console-connection-settings-dialog-in-portals/index.html
* develop/release-management/features/virt/detailed-exit-reason/index.html
* develop/release-management/features/virt/display-address-override/index.html
* develop/release-management/features/virt/guestagentdebian/index.html
* develop/release-management/features/virt/guestagentopensuse/index.html
* develop/release-management/features/virt/guestagentsles/index.html
* develop/release-management/features/virt/guestagentubuntu/index.html
* develop/release-management/features/virt/hot-plug-cpu/index.html
* develop/release-management/features/virt/instance-types/index.html
* develop/release-management/features/virt/intial-run-vm-tab/index.html
* develop/release-management/features/virt/multiple-consoles/index.html
* develop/release-management/features/virt/multiple-graphic-servers/index.html
* develop/release-management/features/virt/multiplemonitors/index.html
* develop/release-management/features/virt/non-plugin-console-invocation/index.html
* develop/release-management/features/virt/novnc-console/index.html
* develop/release-management/features/virt/os-info/index.html
* develop/release-management/features/virt/prestartedvm/index.html
* develop/release-management/features/virt/ram-snapshots/index.html
* develop/release-management/features/virt/resourceusagegraph/index.html
* develop/release-management/features/virt/s3-suspend/index.html
* develop/release-management/features/virt/smartcard-support/index.html
* develop/release-management/features/virt-sparsify/index.html
* develop/release-management/features/virt/spicehtml5/index.html
* develop/release-management/features/virt/spicerelatedfeatures/index.html
* develop/release-management/features/virt-sysprep/index.html
* develop/release-management/features/virt/virt-v2v-integration/index.html
* develop/release-management/features/virt/vmpayload/index.html
* develop/release-management/features/vmdevices-rework/index.html
* develop/release-management/proposals/mass-vms-run/index.html
* develop/release-management/releases/3.3.4/testing/index.html
* develop/release-management/releases/3.3.5/testing/index.html
* develop/release-management/releases/3.3/release-management/index.html
* develop/release-management/releases/3.3/testday/index.html
* develop/release-management/releases/3.4.1/testing/index.html
* develop/release-management/releases/3.4.2/testing/index.html
* develop/release-management/releases/3.4.4/testing/index.html
* develop/release-management/releases/3.4/test-day/index.html
* develop/release-management/releases/3.5.1/testing/index.html
* develop/release-management/releases/3.5.2/index.html
* develop/release-management/releases/3.5.2/testing/index.html
* develop/release-management/releases/3.5.3/testing/index.html
* develop/release-management/releases/3.5/testday/index.html
* documentation/admin-guide/addtabs/index.html
* documentation/index.html
* documentation/sla/index.html
* documentation/sla/network-qos/index.html
* documentation/sla/trusted-compute-pools-deployment/index.html
* documentation/storage/backup-and-restore-engine/index.html

Most are linking to "user:" pages, which do not exist. Some are linking to "special:" pages, which also do not exist (as this is not MediaWiki).

**Comment by garrett** [comment]
I can modify the code that produces the error to silently ignore user pages. It would then not link to anything, but still show the text of the link (that is, the name of the person). For the case of the Special pages, those need to be edited in the source.

There are 706 pages that refer to "user:", so having it automated would probably be preferable.

There are 4 documents that link to "special:" pages. These source docs need hand-editing to remove the links. The source files for these 4 are:

* community/index.html.md
* community/get-involved/wiki-rules-and-etiquette.html.md
* documentation/index.html.haml
* documentation/sla/index.html.md

The documentation for these 4 pages probably need to be revised anyway, as I'm certain that each one of them refers to wiki-related stuff (else they wouldn't have wiki links).

**Comment by thatdocslady** [comment]
@eedri I think this is what you were talking about?

**Comment by eedri** [comment]
@thatdocslady yes

**Comment by garrett** [comment]
This looks fixed. Closing bug.
