### ISSUE TITLE
"About" link in all pages is broken

### ISSUE THREAD

**Issue by rollandf** [oVirt/ovirt-site#152]
The "About" link in the bottom of all the pages is not leading anywhere.
http://www.ovirt.org/about/

**Comment by garrett** [comment]
To fix this, someone working on content would need to one of the following:

1. make the content for an about page
2. move http://www.ovirt.org/documentation/introduction/about-ovirt/ to /about/ (and polish up that page)
3. change the footer link to point to /documentation/introduction/about-ovirt/ (and polish up that page)

(I've listed the options in the order of preference.)

So, someone who could make this decision: what should be done?

**Comment by duck-rh** [comment]
I think I like option 2. having two pages on almost the same kind of information is not fine and noone would thin to update them both and one or both would be partially obsolete fast.
But if we intend to talk about the community and general goal of the project in the about page and the software/solution presentation in /documentation/introduction/about-ovirt/, which is probably better, then option 1 is the best (and they can link one another "want details about the software?" "don't know what this site is about?").

**Comment by garrett** [comment]
I just sent a PR that addresses the footer links being broken and points them to the location of the ported-from-mediawiki pages. It's option 3 for now.

A good second step is to create a standalone about page which talks about oVirt _and_ the oVirt community. (Option 1, with a link change to that new about page.)

But this PR fixes the link to the about page (and privacy policy and legal disclaimers) being broken, which is the topic of issue.

**Comment by garrett** [comment]
Created new issue for about page content; closing this issue as the link is fixed.
