### ISSUE TITLE
broken link on latest blog - http://www.ovirt.org/blog/2016/03/up-and-running-with-ovirt-3-6/

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#153]
The link to http://www.ovirt.org/blog/2016/03/up-and-running-with-ovirt-3-6/develop/release-management/features/engine/self-hosted-engine-hyper-converged-gluster-support/ is broken.

@jasonbrooks  -  can you look at this?

**Comment by jasonbrooks** [comment]
The link should be working -- something's happening w/ middleman and links that point to ovirt.org, they're being made relative to the blog post they appear in. PR 160 works around the issue for now w/ html-style links.

**Comment by sandrobonazzola** [comment]
Closing this as solved by PR #160. If there's an issue in middleman configuration, @jasonbrooks or @garrett please open a separate issue. If it's a middleman bug, let's ensure it's reported.
