### ISSUE TITLE
Merged blog post isn't showing under 'Blog' section

### ISSUE THREAD

**Issue by rgolangh** [oVirt/ovirt-site#1549]
### Description of the problem
The latest blog post, merged at commit ea6e194d07f3ff7b158a747ea957da5cd6be2fb6 is not rendered or published under the /blog section. I see it perfectly fine when I ./run-server locally.

### Help needed from (use @mention to request assistance)
@duck-rh

**Comment by mscherer** [comment]
I am going to take a look. Seems we had a issue on others builders too, and @duck-rh asked me to see if a fresh eye could help.

**Comment by mscherer** [comment]
Ok, seems one process was locking the build since last Github DDOS. I killed it and we will see cron pick the build soon. It should be finished in around 1h at most.

**Comment by rgolangh** [comment]
Already showing up. Thanks!
