### ISSUE TITLE
Server not providing intermediate certificate makes Google Chrome report as untrusted website

### ISSUE THREAD

**Issue by SyuTingSong** [oVirt/ovirt-site#159]
Server not providing intermediate certificate makes Google Chrome report as untrusted website

**Comment by sandrobonazzola** [comment]
Can you please re-check? Looks ok to me now.

**Comment by ekohl** [comment]
This is still incorrect. See https://www.ssllabs.com/ssltest/analyze.html?d=www.ovirt.org

**Comment by duck-rh** [comment]
Interestingly chromium 55.0.2883.75-2 does not complain.

I have re-setup the certificate and used a chain to include the intermediate certs and it works well now.

**Comment by ekohl** [comment]
@duck-rh browsers have an intermediate cache, so if you visited another site that uses the same intermediate then they will happily use that. It's no guarantee though.

Thanks for fixing this, I've added the blog to https://planet-ovirt.ekohl.nl/ (which could use some more content)
