### ISSUE TITLE
404 not found - section / anchor links

### ISSUE THREAD

**Issue by Ninroot** [oVirt/ovirt-site#1597]
### Description of the problem
Hi,

It seems like sections like `[Importing Existing Storage Domains](sect-Importing_Existing_Storage_Domains)` are not working properly. The link brings me to a 404.

### Steps to reproduce

1. Go to https://www.ovirt.org/documentation/admin-guide/chap-Storage/ web page.

2. Click on "See Importing Existing Storage Domains for information on importing storage domains.".

3.

### Help needed from (use @mention to request assistance)
Fix the `sect` or change it to be an anchor like `[ Mailing lists](/community/about/mailing-lists/), [ IRC](#IRC)`

**Comment by crutonjohn** [comment]
Couldn't this be fixed by replacing links like:
https://www.ovirt.org/documentation/admin-guide/chap-Storage/sect-Importing_Existing_Storage_Domains

with the embedded links such as:
https://www.ovirt.org/documentation/admin-guide/chap-Storage/#importing-existing-storage-domains

let me know and I can tackle this one; globally if need be.

**Comment by gregsheremeta** [comment]
> Couldn't this be fixed by replacing links like:
> https://www.ovirt.org/documentation/admin-guide/chap-Storage/sect-Importing_Existing_Storage_Domains
> 
> with the embedded links such as:
> https://www.ovirt.org/documentation/admin-guide/chap-Storage/#importing-existing-storage-domains
> 
> let me know and I can tackle this one; globally if need be.

yes, feel free

**Comment by imjoey** [comment]
Hi @crutonjohn , are you still working on this issue? If not, I'd like to make it fixed. Thanks.

**Comment by crutonjohn** [comment]
@imjoey go ahead my friend, i got caught up in some other projects. i'll try and pick something else to work on.

**Comment by sandrobonazzola** [comment]
Looks like this didn't move. I'm handling this today.
