### ISSUE TITLE
node page needs a re-work

### ISSUE THREAD

**Issue by jekader** [oVirt/ovirt-site#1598]
### Description of the problem

The [Node](https://www.ovirt.org/node/) page is currently very confusing for people who are not familiar with oVirt and came just to download an ISO. There are multiple links to various Node versions, most of them leading to Jenkins which should not be a download server for ISOs.

### Steps to reproduce

1. ask a random person to download oVirt Node

2. check how much time it takes to find a suitable link on the Node page

3. verify which node version was actually downloaded (4.0? 4.1? 4.2? master?)

### Proposal to fix:

1. Re-arrange the Downloads section and put a link to it at the very top (currently link is broken in the quickstart)

2. Ensure the current release is the recommended download on top of the list, while older releases after it and Master at the very end as it's mostly needed by contributors and not the major audience.

3. Put links to [resources.ovirt.org](http://resources.ovirt.org/pub/ovirt-4.2/iso/ovirt-node-ng-installer-ovirt/) instead of jenkins.ovirt.org where possible. We may need to improve publishing to have a "latest" directory on resources.

I can submit a PR for this but first want to agree on the action items.

**Comment by mykaul** [comment]
@eldan - thoughts?

**Comment by gregsheremeta** [comment]
This page will be redirected to https://www.ovirt.org/documentation/admin-guide/chap-Hosts.html

**Comment by gregsheremeta** [comment]
done
