### ISSUE TITLE
MediaWiki anchors are named differently — try to handle the difference with client-side JS fuzzy string matching

### ISSUE THREAD

**Issue by david-caro** [oVirt/ovirt-site#16]
In the old wiki you have some html anchors to link page sections, and some intra-page links for the are now broken

**Comment by garrett** [comment]
...every heading has an auto-generated ID based on the text. You can link to that.

It basically takes the text, lowercases it, and replaces most non-alphanumeric character with a dash. So a headline with "This is an example, here!" would be transformed into "this-is-an-example-here" for the ID of the h1/h2/h3/h4/h5/h6. You can then link directly to it by adding `#this-is-an-example-here` at the end of the URL.

If you want to confirm the ID of an element, you can right-click on the headline and select "Inspect element" in Firefox, Chrome, and Epiphany (GNOME Web). Each browser would then show you the developer console with the element highlighted. You'll see something like `<h3 id="this-is-an-example-here">This is an example, here!</h3>` — the ID is what's used as a document fragment. Using an ID as a document fragment works for all web pages, everywhere on the Internet, in every browser (even Lynx, Links, all the mobile browsers, etc.).

**Comment by garrett** [comment]
Also, the links to headings within pages are going to be broken, as MediaWiki handles them differently. This is not a bug; it's an implementation difference. The same page will still load, however.

**Comment by garrett** [comment]
(That said, it might be possible to do some magic in client-side JavaScript to check for a fragment and see if any ID on the page fuzzy matches and redirect it to the best match.)

**Comment by garrett** [comment]
(I'm pretty sure that's possible, in fact. And I am fairly certain I know how to do it.)

**Comment by garrett** [comment]
This is now handled in the new redirect code. (#285)
