### ISSUE TITLE
Administration Guide and Administration go the same place

### ISSUE THREAD

**Issue by shaunix** [oVirt/ovirt-site#1633]
### Description of the problem

On the documentation main page, "oVirt Administration Guide" and "Administration" point the same place.

### Steps to reproduce

1. Go to https://www.ovirt.org/documentation/

2. Look at  "oVirt Administration Guide"  under "Primary Documentation"

3. Also look at "Administration" under "Additional Documentation"

4. These two links point to the same document/directory, except the first points to a hand-crafted table of contents, whereas the second points to an auto-generated list of pages.

**Comment by sandrobonazzola** [comment]
Administration provides the same link in Administration Guide book + https://www.ovirt.org/documentation/admin-guide/virt/console-client-resources/ which is outside the book.

I tend to agree the 2 links are redundant. @eldan what do you think?

**Comment by gregsheremeta** [comment]
fixed

**Comment by gregsheremeta** [comment]
will be fixed by disabling the auto-generated index pages

**Comment by sandrobonazzola** [comment]
This is fixed now.
