### ISSUE TITLE
Neutron Integration How to is obsolete

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#1634]
### Description of the problem
[Neutron Integration How To](https://www.ovirt.org/documentation/how-to/networking/overlay-networks-with-neutron-integration/) is obsolete
### Steps to reproduce

1. Go to: https://www.ovirt.org/documentation/how-to/networking/overlay-networks-with-neutron-integration/

2. Read it

3. See it still uses OpenStack Havana while last released RDO is Queen and Rocky is being developed.

Also, it points to https://brewweb.devel.redhat.com which is not accessible.

**Comment by 18641315209** [comment]
When I built the ovirt and openstack environments according to the documents, I performed "engine-config --set keyauthstoneurl =http://< host-fqdn >:35357/v2.0". The Error was as follows: Error setting KeystoneAuthUrl's value. No such entry.

I found no "KeystoneAuthUrl" configuration option in engine-config.

Did you remove this configuration in the new version?

**Comment by gregsheremeta** [comment]
https://www.ovirt.org/documentation/admin-guide/chap-Logical_Networks.html should replace this.
