### ISSUE TITLE
add API documentation

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-site#1670]
### Description of the problem
we are missing API and SDK docs on the ovirt site. I think we missed them when doing the 4.2 docs.

A google search for "ovirt api" docs gives poor results -- nowhere to be found are descriptions of entities that I can GET or DELETE, for example. It should fairly quickly point to the REST API Guide (RH doc: https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html/rest_api_guide/) and the model (http://ovirt.github.io/ovirt-engine-api-model/  - but style that page)

All of the API docs related to ovirt should be on the website, such that googling for "ovirt api" pulls up a delightful list of helpful documentation.

### Steps to reproduce

1. https://www.google.com/search?q=ovirt+api
2. the results are lacking

1. go to www.ovirt.org/documentation
2. no API or SDK docs are present

**Comment by sandrobonazzola** [comment]
Sent a PR pointing to API, SDK and ansible docs. Better than nothing.
