### ISSUE TITLE
Weak wording for information on remove-old-host-from-the-metadata-whiteboard

### ISSUE THREAD

**Issue by itsafire** [oVirt/ovirt-site#1717]
### Description of the problem

The hosted-engine howto at `ovirt-site/source/documentation/how-to/hosted-engine.html.md#remove-old-host-from-the-metadata-whiteboard` is too weak.

It says:

> It is possible to remove an old host from the hosted-engine --vm-status report by using the hosted-engine --clean-metadata command. The agent has to be stopped first. You can force cleaning of a specific ID In the case when the host does not exist anymore by adding --host-id= argument.

This information unclear to me are:
* which agent exactly ? I suspect the ha-agent, but I am not certain.
* where does it have to be stopped. Everywhere ? or only on that node I am issuing the command ?
* No global maintenance ? Sounds odd when fiddling around with the ha-agent or whatever agent.
 
### Help needed from (use @mention to request assistance)
someone how knows better than me.

**Comment by gregsheremeta** [comment]
Does this updated documentation make more sense?
https://ovirt.org/documentation/self-hosted/chap-Maintenance_and_Upgrading_Resources/

**Comment by gregsheremeta** [comment]
the old hosted-engine how-to is replaced with the new Self Hosted Engine Guide. Please reference that instead. Thanks!
