### ISSUE TITLE
Bad link on webpage

### ISSUE THREAD

**Issue by StackKorora** [oVirt/ovirt-site#1723]
### Description of the problem
The Webpage:
https://www.ovirt.org/community/

The Github page for it:
https://github.com/oVirt/ovirt-site/blob/master/source/community/index.html.md

The first bullet point says "Sign up to the users@ovirt.org@ovirt.org/ mailing..."

Issue 1: Double use of '@ovirt.org'
Issue 2: The link points to https://lists.ovirt.org/archives/list/users/ but that link doesn't work for me.

**Comment by gregsheremeta** [comment]
Thanks for reporting. Use the "Forum" link in the site header until we get this (ancient) page updated.
