### ISSUE TITLE
Ubuntu guest agent info out-of-date

### ISSUE THREAD

**Issue by dougti** [oVirt/ovirt-site#1726]
### Description of the problem
The old evilissimo repo on the openSUSE site was removed some time ago now. From what I can tell, it's now being maintained on Ubuntu's own Universe repo, with the oldest supported release being Xenial (16.04).

Time to update the documentation?

- https://www.ovirt.org/documentation/how-to/guest-agent/install-the-guest-agent-in-ubuntu/
- https://github.com/oVirt/ovirt-site/blob/master/source/documentation/how-to/guest-agent/install-the-guest-agent-in-ubuntu.html.md
- https://launchpad.net/ubuntu/+source/ovirt-guest-agent

**Comment by gregsheremeta** [comment]
Indeed, this was not maintained. We don't have any guidance for guest agent Ubuntu guests, so I deleted the page. Thanks for reporting.
