### ISSUE TITLE
Presentation of Explanation of Settings in the VM Interface Profile Window

### ISSUE THREAD

**Issue by MESHSfr** [oVirt/ovirt-site#1755]
### Description of the problem

HTML problem on the "Explanation of Settings in the VM Interface Profile Window" part

### Steps to reproduce

1. go to https://ovirt.org/documentation/admin-guide/chap-Logical_Networks/

2. go to "Explanation of Settings in the VM Interface Profile Window"

3. well, i guess there's some html tag are not closed :)

**Comment by sandrobonazzola** [comment]
Closed in #1761
