### ISSUE TITLE
Pool page in docs.

### ISSUE THREAD

**Issue by atriumcarceri** [oVirt/ovirt-site#1775]
Troubles with bad display, html codes as plain text. 
http://prntscr.com/l69jk8

And please, can u update this for 4.2 version?

**Comment by sandrobonazzola** [comment]
@atriumcarceri can you please share the link to the page you are referring to? URL is not included in your screenshot

**Comment by gregsheremeta** [comment]
Documentation has been updated to 4.2. Please open a new issue with a URL if you are still having trouble.
