### ISSUE TITLE
OVirt 4.3 Schedule Update

### ISSUE THREAD

**Issue by pkchavva** [oVirt/ovirt-site#1789]
### Description of the problem

The oVirt 4.3 schedule is not updated.

### Steps to reproduce

1.Go to https://www.ovirt.org/develop/release-management/releases/4.3/release-management/

2.

3.

**Comment by sandrobonazzola** [comment]
Hi, only planned date for now is initial oVirt 4.3 beta release, targeted to November 26th.
So up to now, schedule is updated with known content. Also please note dates are tentative.
