### ISSUE TITLE
documentation - bad formatting in vmm guide

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-site#1843]
### Description of the problem
https://www.ovirt.org/documentation/vmm-guide/appe-Reference_Settings_in_Administration_Portal_and_User_Portal_Windows.html
is badly formatted -- looks like markdown issues on some of the tables

I haven't investigated yet.

![selection_261](https://user-images.githubusercontent.com/2248293/50160226-c259c300-02a6-11e9-9ab6-e46aa040c66e.png)

**Comment by shaunix** [comment]
There's quite a bit of bad markup in this file. Because of the complexity of the tables, we have to revert to HTML, and, well, it's not perfect. I'll clean it up.

**Comment by shaunix** [comment]
Fixed all the invalid markup I saw, but I noticed the last two tables have 50% column widths, which seems way off to me. I'm guessing it's auto-generated and not intentional. Might just want to drop the cols.

**Comment by gregsheremeta** [comment]
@shaunix whatever you can do to make it look decent is good with me. I don't want to lose any information - ?

**Comment by shaunix** [comment]
Added a commit to my PR branch that cleans up the tables, gets rid of the 50% column sizing, makes the markup simpler for humans, and fixes a few remaining harder to spot errors.

**Comment by gregsheremeta** [comment]
Thank you, Shaun.
