### ISSUE TITLE
Local test requested before pull, but no instructions and both server and docker scripts fail

### ISSUE THREAD

**Issue by MarSik** [oVirt/ovirt-site#186]
Hi,

The CONTRIBUTING file asks for local testing of changes in the "Test your changes locally" section. But there are no instructions about how to actually do that.

I tried using the standard approach of bundle install && bundle exec ./run-server.sh, but it fails with:

```
/home/msivak/.gem/ruby/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/data.rb:167:in `method_missing': undefined method `events' for #<Middleman::CoreExtensions::Data::DataStore:0x00000004b30160> (NoMethodError)
	from /home/msivak/Work/ovirt-site/config.rb:138:in `block in initialize'
```

I also tried to use the ./docker-setup.sh && ./docker-run.sh script, but that also failed:

```
[msivak@dhcp131-31 ovirt-site]$ sudo ./docker-run.sh 
Running docker image springboard-20160420-10023
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.
```

So apart from having no instructions, the "obvious" ways do not work either.

**Comment by gregsheremeta** [comment]
run ./setup.sh and then ./run-server.sh
