### ISSUE TITLE
Documentation > Hyperconverged documentation needs improvement, should document Cockpit installation

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-site#1897]
### Description of the problem
Hyperconverged documentation needs improvement, should document Cockpit installation fully
https://ovirt.org/documentation/gluster-hyperconverged/Gluster_Hyperconverged_Guide.html

From https://ovirt.org/documentation/gluster-hyperconverged/chap-Deploying_Hyperconverged.html :
"""
Setting up the hyperconverged environment
Steps for installing are detailed in this blog post [link].
"""
^ Linking to a blog post is not acceptable for end user documentation.

https://lists.ovirt.org/archives/list/users@ovirt.org/message/CZUXSSJL4TVCVRNUBE6KZHYTKGBUX5TL/

**Comment by sandrobonazzola** [comment]
@gobindadas can you take care of getting this guide updated?

**Comment by sandrobonazzola** [comment]
We are deprecating cockpit based installation, so closing thie ticket.

**Comment by mtorromeo** [comment]
@sandrobonazzola Is there any documentation on installing a hyperconverged cluster without using cockpit-ovirt though?
