### ISSUE TITLE
Documentation > Host Upgrade Guide is confusing

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-site#1906]
### Description of the problem
https://ovirt.org/documentation/upgrade-guide/appe-Manually_Updating_Hosts.html

Needs improvement.
* ovirt-node-ng-image-update is not mentioned
* rhel repos are mentioned

see https://lists.ovirt.org/archives/list/users@ovirt.org/message/6JB2GRHPMYCDA5VA32SFZ3I4F7J5TKDF/
for conversation

**Comment by sandrobonazzola** [comment]
I think this is now fixed. RHEL repos are not mentioned anymore and correct steps for updating oVirt Node are there.
