### ISSUE TITLE
[urgent] ovirt.org not being updated by github commits

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#193]
Looks like ovirt.org is not receiving updates from github commits.
patches merged more than 1 hour ago are not showing up even if travis finished more than one hour ago.

**Comment by garrett** [comment]
@mscherer or @duck-rh would have to look into this.

I haven't had any problems in a while — and I know that the site has updated fine a few times today (with a few PRs I sent in and merged), so I suspect this was a one time odd thing. Perhaps there was an issue with the build machine or a bad commit might have been merged in. Regardless, it seems like it is no longer an issue, so I'm closing the ticket.

(Feel free to re-open if you are still experiencing the issue. Thanks!)

**Comment by duck-rh** [comment]
It is too old to investigate, there is only status files for debugging the previous run and it would be unreproducible now. It was probably discussed/investigated on IRC anyway at that time.
