### ISSUE TITLE
Issue: /source/develop/release-management/features/virt/hot-plug-cpu.html.md

### ISSUE THREAD

**Issue by ktopogli** [oVirt/ovirt-site#1933]
#### Type of problem?
Formatting issue on the OS compatibility list

The list is not well formatted and difficult to read (if not impossible)

#### Help needed 
to be corrected please :)

**Comment by sandrobonazzola** [comment]
@evol262 can you handle this?

**Comment by sandrobonazzola** [comment]
Fixed by #2355
