### ISSUE TITLE
Issue: /source/download/index.html.md

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#1941]
### Description of the problem
Download page shows guest OS which are not supported anymore by OS Vendor.

#### Type of problem?
Content issue

For Ubuntu, list of supported versions by vendor is at: https://wiki.ubuntu-it.org/Rilasci
For SUSE: https://www.suse.com/lifecycle/
And so on for the other OS/ distributions listed there.

**Comment by sandrobonazzola** [comment]
@evol262 , @michalskrivanek can we update engine and documentation aligning to supported distributions by OS vendors?

**Comment by michalskrivanek** [comment]
there are some minor things (like i don't think one needs to select Other for Suse when we have a SLES entry, perhaps RHEL8 entry to say no ovirt-guest-agent there), but other than that I do not see a problem, those are minimal versions - note the "+" next to the name.

**Comment by evol262** [comment]
We also have https://bugzilla.redhat.com/show_bug.cgi?id=1341161 for tracking updated versions

For removing the older versions, it seems relatively common among other products, and we still expect them to work. We did simply add "Other Linux (kernel 4.x)" in 4.3, but that doesn't cover the older versions of Ubuntu LTS (for example) which are still supported

**Comment by sandrobonazzola** [comment]
closing according to comments from @michalskrivanek and @evol262.
