### ISSUE TITLE
Issue: /source/index.html.haml

### ISSUE THREAD

**Issue by dxjxo** [oVirt/ovirt-site#1950]
[ Thank you for submitting an issue! Please read these instructions and then delete the instructions sections before submitting the issue.

Is this Issue something you can help fix? If you'd like to contribute to making our site better, submit a Pull Request along with your Issue report! ]

#### Type of problem?
Documentation issue | Content issue | Formatting issue | 404 | something else

[ Enter a detailed description of the problem. If you have suggestions for improvements, please include them (and open a Pull Request too, if you'd like!). Please include links to users list discussions, external documentation, or anything else that might be helpful. Delete this section before submitting your Issue. ]

Enter details ...

**Comment by duck-rh** [comment]
@dxjxo you're supposed to fill-in the details because currently we have no idea what kind of problem you encountered.

**Comment by sandrobonazzola** [comment]
Closing since no issue has been reported here.
