### ISSUE TITLE
Site redesign proposal 

### ISSUE THREAD

**Issue by lwrigh** [oVirt/ovirt-site#1968]
### Description of the problem
The site could use a redesign to help to streamline the content and the look and feel of the site to reflect more of the design of the application itself. The site should reflect more of the design of the application so they do not feel as separated. 

#### Type of problem?
Documentation issue | Content issue | Formatting issue | Design issue

Links to wireframes:
-Desktop: <s>https://redhat.invisionapp.com/share/7KOVWW4APV9#/screens</s> Old link
New link: https://marvelapp.com/1g9eh6h6
-Mobile: <s>https://redhat.invisionapp.com/share/K7PZLSMX3Q5#/screens/341026523_Mobile_Homepage</s> Old link
New link: https://marvelapp.com/i4i43fe

I've put together some wireframes for a proposed redesign of the site. I've included both desktop and mobile variations. Some of the main goals of the redesign included utilizing the newer branding to unify the site more with application, clean up the page layouts to be more consistent with one another, and update content so it's up to date.

**Comment by nirs** [comment]
I commented on https://redhat.invisionapp.com/share/7KOVWW4APV9#/screens.

Awesome work!

**Comment by lwrigh** [comment]
@nirs Awesome thank you for checking our the wireframes and leaving feedback!

**Comment by duck-rh** [comment]
I added a few comments

**Comment by lwrigh** [comment]
@duck-rh Great thank you!

**Comment by sandrobonazzola** [comment]
Looks great to me

**Comment by lwrigh** [comment]
@nirs @duck-rh I made some more updates to the wireframes based off of the feedback you left, feel free to check them out if you like.

**Comment by nirs** [comment]
@lwrigh looks much better now. I added some more comments on https://redhat.invisionapp.com/share/7KOVWW4APV9#/screens.

**Comment by duck-rh** [comment]
thanks @lwrigh that's much clearer and readable :-)

**Comment by lwrigh** [comment]
@duck-rh Great I'm glad to hear! @nirs I added some more updates to the wireframes based off of the feedback you left, I updated the breadcrumbs across the board as well.

**Comment by sandrobonazzola** [comment]
looks good to me, @lwrigh  can you push this to production?

**Comment by matthewcarleton** [comment]
just as a follow up @lwrigh and I have a meeting scheduled this week to discuss this.

**Comment by matthewcarleton** [comment]
hey @sandrobonazzola @duck-rh I'm talking through requirements with @lwrigh. Just wondering how we want to move forward with this once I have some html/css ready for implementation?

**Comment by sandrobonazzola** [comment]
@matthewcarleton I don't have a specific plan.

**Comment by lwrigh** [comment]
Would it be helpful if we had a chat to figure out possible paths forward?

**Comment by lwrigh** [comment]
Documentation solution must support asciidoc.

**Comment by sandrobonazzola** [comment]
@duck-rh @gregsheremeta there was a plan to switch middleman to something which also support asciidoc, any update or ETA on that?

**Comment by duck-rh** [comment]
The proposed solution is to use Jekyll. Several other communities have been using it for quite some time now and are happy with it, and we have al the deployment materials and knowledge to support it.

I checked and there's an asciidoc plugin.

Now converting to the new system is going to be some work. I can prepare a builder and test vhost but people are needed to actually port the content. Markdown is supported but some adaptation will probably be needed, as well as working together to polish the config (maybe find useful replcement plugins, get rid of the custom Ruby code…).

Also one step in that direction is moving the blog part to WP (see OVIRT-2652). Once done this part won't have to be ported to Jekyll. I'll ping Jason about it.

**Comment by nirs** [comment]
We like markdown, and we don't want to learn complicated syntax that we don't need.

How new design related to changing the markup language and tools used to create the site? Can we implement the proposed design in the current system as is?

**Comment by matthewcarleton** [comment]
@nirs for the front end html/css it's going to be much easier to build from scratch but I'm not opposed to using the current structure. Whatever works!

**Comment by nirs** [comment]
I'm not attached to the current system, just wanted to understand why site redesign proposal requires a rewrite :) Anyway If it is easier, replace special code standard tools, add features, and more fun, why not.

**Comment by lwrigh** [comment]
@matthewcarleton Do we want to get started on doing a preliminary look at the current code and seeing where we can go from there?

**Comment by lwrigh** [comment]
@nirs @sandrobonazzola @duck-rh 

We have a couple questions about next steps that I'm hoping you guys can help answer:

What will we build the site with (Jekyll?) and who will do this? 

From a content migration strategy perspective who will be doing this? If multiple teams have been involved in the past, who would be good to get in contact with? 

Do all the current pages on the site have 1:1 mapping with the new site? (I have to double check that the design covers the majority of page cases.) If not we'll want to make sure we cover broken links in search results.

Who would be a good contact/task owner for implementing the server side stuff? 

Let me know what you guys think!

**Comment by duck-rh** [comment]
Quack,

> What will we build the site with (Jekyll?) and who will do this?

I suggested Jekyll because we can reuse the Markdown pages (with some changes though, like headers) and other communities are happy with it. It is also easy to maintain and without security risks (static generation).

OSPO (ex-OSAS) CommInfra is already running the current site and builder, and we already have the materials to deploy for Jekyll, so we can do it.

I'm also part of the oVirt Infra team and I brought the subject in the team meeting: noone had any objection.  I nevertheless do not have a final world on this. If the community thinks this solution is not satisfactory we can work on something else.

> From a content migration strategy perspective who will be doing this? If multiple teams have been involved in the past, who would be good to get in contact with?

The migration needs some work, and as I said we need the blog part migrated first. @jasonbrooks will lead this part.

I can help migrate the site, like setup the new site settings, cleanup the old cruft, and also automate  part of the changes needed on the pages. I'll need the help of Ovirt people writing the site to help me check and fix the remaining issues though.

> Do all the current pages on the site have 1:1 mapping with the new site? (I have to double check that the design covers the majority of page cases.) If not we'll want to make sure we cover broken links in search results.

I need to check that.
Pulp migrated to Jekyll too and they'll probably be able to give us some tips.

> Who would be a good contact/task owner for implementing the server side stuff?

OSPO CommInfra

\\_o<

**Comment by lwrigh** [comment]
Thank you for the input @duck-rh!

Great Jekyll sounds like a solid option then. 

Do you know if there's a specific contact person for oVirt on the OSPO team? Would it be helpful to reach out to them? For asking the community, we can send a message out on the community channels asking for feedback on it. 

@jasonbrooks Nice to meet you! Let me know if you need any UX support along the way. 

I can also reach out to OSPO CommInfra to ask them for their assistance for server side stuff.

**Comment by duck-rh** [comment]
@lwrigh I'm in OSPO CommInfra
I'm just a secret oVirt Infra team operative too ;-P

**Comment by lwrigh** [comment]
Perfect! Even better :)

**Comment by pmkovar** [comment]
> We like markdown, and we don't want to learn complicated syntax that we don't need.
> 
> How new design related to changing the markup language and tools used to create the site? Can we implement the proposed design in the current system as is?

This was brought up by me and the RHV docs team. Support for Asciidoc is a must-have feature for us to establish some sport of content sharing between ovirt and downstream (where docs are written in Asciidoc), which is what many have been asking for.

If Jekyll can support both Markdown and Asciidoc, good. As for migrating ovirt guides that have RHV counterparts, I'd suggest we just reuse the current RHV 4.3 downstream content in Asciidoc instead of spending time migrating outdated ovirt docs in Markdown.

**Comment by duck-rh** [comment]
@pmkovar I totally agree this is a loss of energy but at the same time I think the "upstream first" pillar of Red Hat was lost somewhere in the process; so I guess convincing oVirt people should come first.

On my side I see no problem activating the asciidoc support. I'll do that when the site is ported to Jekyll, working well, and people are happy. I've sent a message on the mailing-lists and the work is being tracked in #2043
This is important because the theme will need to be ported to Jekyll, it should not be too difficult though.

**Comment by darkfiberiru** [comment]
@duck-rh @pmkovar  Are we still looking to migrate RHV content instead of current ovirt guides? Trying to see if working on #1228  makes any sense

**Comment by duck-rh** [comment]
@darkfiberiru I did not initiate the discussion on the RHV guides. I think it makes sense to merge the content but it would be nice to know how the community feels about it and the new format. If this is going to happen I can help on the Jekyll integration. There was no asciidoc content in the previous site so I could not try the plugin. I think we should create a specific issue for that as this does not impact the redesign.

As for #1228, I think it makes sense to rerun a check on the new (Jekyll) site. again I think it should be discussed in this other ticket and not here.

**Comment by pmkovar** [comment]
> @duck-rh @pmkovar Are we still looking to migrate RHV content instead of current ovirt guides? Trying to see if working on #1228 makes any sense

Yes, it is still the plan once we get site support for AsciiDoc.

> There was no asciidoc content in the previous site so I could not try the plugin. I think we should create a specific issue for that as this does not impact the redesign.

I filed #2086. 

Note that the request here is not to replace Markdown with AsciiDoc but to add AsciiDoc support in addition to Markdown, so I see no reason why not enable it.

**Comment by sandrobonazzola** [comment]
Hi, where do we stand with this? can we move it to production?

**Comment by lwrigh** [comment]
We have some of the base CSS and HTML written for the homepage and a couple of the other pages so those could potentially be started to be moved over.

**Comment by sandrobonazzola** [comment]
@lwrigh I think we can start moving over

**Comment by sandrobonazzola** [comment]
closing with #2395
