### ISSUE TITLE
Issue: /source/documentation/admin-guide/appe-oVirt_and_SSL.html.md

### ISSUE THREAD

**Issue by kroisler** [oVirt/ovirt-site#1989]
[ Thank you for submitting a documentation issue! Please read these instructions and then delete the instructions sections before submitting the issue.

Is this documentation Issue something you can help fix? If you'd like to contribute to making our documentation better, submit a Pull Request along with your Issue report! ]

Wrong HowTo Section

![image](https://user-images.githubusercontent.com/7203622/57221287-e2dcac80-6ffe-11e9-9e2a-871330073a1c.png)

The wrong file for ovirt-websocket-proxy.conf.d is wrong.

**Comment by sandrobonazzola** [comment]
This seems to be already fixed. I see now:

![image](https://user-images.githubusercontent.com/937860/71248000-2976e100-231a-11ea-8a0f-0aa9b0f24004.png)
