### ISSUE TITLE
Expand community guidelines topic to community CoC

### ISSUE THREAD

**Issue by thatdocslady** [oVirt/ovirt-site#2]
Currently we have a "community guidelines" topic that lists in general terms the guidelines to follow when operating within the community. However, the topic describes conduct guidelines only in broad terms, and also contains sections related to naming conventions etc, that don't really belong there.

Link to original topic:
https://github.com/oVirt/ovirt-site/blob/master/source/community/about/community-guidelines.html.md

Need to break down the topic to conduct vs infra vs ops, and formalize each type of information into its own topic.

**Comment by sandrobonazzola** [comment]
@duck-rh what's missing to close this issue?

**Comment by duck-rh** [comment]
Well, my "#\<i\>" in the commit messages were to say "part \<i\>" of the changes, and not to link to this issue.

From what I can see the page changed since @thatdocslady opened this ticket. There are no more naming conventions and such technical content. It seems fine to me as it is now.

**Comment by gregsheremeta** [comment]
it's fine now, closing
