### ISSUE TITLE
Issue: /source/develop/security/security.html.md

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2003]
### Description of the problem
"The security advisories page lists all security vulnerabilities fixed in oVirt." points to a non existing page https://ovirt.org/documentation/security/security-advisories/

#### Type of problem?
404

"The security advisories page lists all security vulnerabilities fixed in oVirt." points to a non existing page https://ovirt.org/documentation/security/security-advisories/

**Comment by rolfedh** [comment]
That URL doesn't show up in [archive.org](https://archive.org/search.php?query=https%3A%2F%2Fovirt.org%2Fdocumentation%2Fsecurity%2Fsecurity-advisories%2F). However, there is this page (https://www.ovirt.org/develop/security/security-advisories.html)

**Comment by sandrobonazzola** [comment]
Fixed with PR #2136
