### ISSUE TITLE
add visible RSS feed link for our blog

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#203]
How do we add a RSS feed to oVirt blog?
For example, I wanted to add news to it @ https://www.openhub.net/p/oVirt/rss_subscriptions/new - and I did not find our RSS feed.

@jasonbrooks  ?

**Comment by jasonbrooks** [comment]
@mykaul http://www.ovirt.org/blog/feed.xml

**Comment by mykaul** [comment]
@jasonbrooks  - thanks - how can one know it? I did not find it anywhere.

**Comment by jasonbrooks** [comment]
We should add a link or rss image somewhere -- I only know about it from familiarity w/ other middleman-powered sites.

**Comment by ekohl** [comment]
At least a link header would help. I think ```<link type="application/atom+xml" rel="alternate" href="https://www.ovirt.org/blog/feed.xml">``` would work.

**Comment by duck-rh** [comment]
@garrett I think you should have a look at this. I guess MM has a feature to add it.

**Comment by sandrobonazzola** [comment]
RSS feed link is now https://blogs.ovirt.org/feed . @duck-rh can you edit the wordpress template we are using and add a link to it?

**Comment by jasonbrooks** [comment]
I can do this

**Comment by jasonbrooks** [comment]
Sorry for the delay, @sandrobonazzola. I added the link to the footer. Does that work?

**Comment by sandrobonazzola** [comment]
Thanks @jasonbrooks , works for me. Closing.
