### ISSUE TITLE
Probably a typo in documentation - Chapter 9: Configuring Storage

### ISSUE THREAD

**Issue by string-sharper** [oVirt/ovirt-site#2065]
#1689 # Description of the problem
Most likely a "right-click paste" issue. Something that should be in a document text unfortunately is.  

#### Type of problem?
Documentation issue

In "Chapter 9: Configuring Storage" document (https://ovirt.org/documentation/install-guide/chap-Configuring_Storage.html), under "Introduction to Storage" section, in 2nd paragraph, there is this string: "Installing_the_Websocket_Proxy_on_a_Separate_Machine", and correct me if I'm wrong, but it looks like someone who was editing this doc. accidentally paste this there. Below is the whole paragraph with pasted string and a paragraph version that I guess should be there instead:

There is:
"_There are Installing_the_Websocket_Proxy_on_a_Separate_Machine types of storage domain:_"

There should be:
"_There are types of storage domain:_"  

I might be wrong, cause I am an oVirt noob, but as far as I see -- this looks like a typo/mistake/etc.

**Comment by nirs** [comment]
Was broken by this 79b048ce94.

**Comment by sandrobonazzola** [comment]
@nirs can you please review the fix at #2069 ?

**Comment by nirs** [comment]
Fixed by #2069
