### ISSUE TITLE
Events "Back to top" link appears above header

### ISSUE THREAD

**Issue by duck-rh** [oVirt/ovirt-site#2077]
#### Type of problem?
Formatting issue

Looking at https://www.ovirt.org/events/2019.html#scale

The "Back to top" link appears above header. I suspect the problem is in the `quicklinks.sass` CSS file but I could not find the source of the problem.

**Comment by sandrobonazzola** [comment]
@duck-rh can you attach screenshot? I don't see issues with my browser

**Comment by duck-rh** [comment]
@sandrobonazzola here it is
![20190822-042415_screenshot](https://user-images.githubusercontent.com/19259504/63462106-23b8de00-c495-11e9-901b-68db7a936fc6.png)

**Comment by duck-rh** [comment]
I can still reproduce it.

**Comment by sandrobonazzola** [comment]
I still can't reproduce.
With Google Chrome 83.0.4103.116:
![Schermata da 2020-06-24 08-48-27](https://user-images.githubusercontent.com/937860/85510509-b8312700-b5f7-11ea-92cc-9e910d8ab952.png)

![Schermata da 2020-06-24 08-48-21](https://user-images.githubusercontent.com/937860/85510535-c54e1600-b5f7-11ea-80c2-ed89c1a644ee.png)


With Firefox 68.9.0esr
![Schermata da 2020-06-24 08-48-53](https://user-images.githubusercontent.com/937860/85510608-e57dd500-b5f7-11ea-9dec-5e874235afe9.png)

![Schermata da 2020-06-24 08-48-58](https://user-images.githubusercontent.com/937860/85510631-ef9fd380-b5f7-11ea-9ca9-7de792898ffe.png)

**Comment by duck-rh** [comment]
I'm on Firefox 77.0.

You need to scroll down so that on of the "back to top" link happen to be right at the bottom of the header bar. That does not happen all the time and it seems to only affect the bottom of the header.

**Comment by duck-rh** [comment]
Here's a new screenshot:

![20200624-160658_screenshot](https://user-images.githubusercontent.com/19259504/85512468-e5e89100-b634-11ea-863e-dc32c26cde4a.png)

**Comment by sandrobonazzola** [comment]
Can you share details about your browser?

**Comment by sandrobonazzola** [comment]
ok, now I reproduced. Issue is that  back to top link has z-index: 500; while the top bar has z-index: 100;
So when you scroll to the bottom of the page the "back to top" link is over the header bar.
