### ISSUE TITLE
Enable site support for AsciiDoc format

### ISSUE THREAD

**Issue by pmkovar** [oVirt/ovirt-site#2086]
A larger part of the ovirt user docs ( https://www.ovirt.org/documentation/) is now outdated, still describing 4.2, and out of sync with the downstream RHV product docs (https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/) that are actively maintained. 

With the site migration to Jekyll (#1968), we can now enable support for the AsciiDoc format (the Asciidoctor variant) that is a prerequisite to keep ovirt docs updated and in sync with downstream.

**Comment by pmkovar** [comment]
@dominikholler @sandrobonazzola

**Comment by duck-rh** [comment]
I can help for the Jekyll settings but I'll need some example asciidoc sources to integrate; I could not find the sources to the linked doc.

**Comment by pmkovar** [comment]
Many thanks @duck-rh 

@rolfedh Can you help here with supplying a good stand-alone RHV adoc file as a test doc? Doesn't matter what the content is, we are interested in markup only.

**Comment by sandrobonazzola** [comment]
+1 for enabling asciidoc

**Comment by rolfedh** [comment]
> ith supplying a good stand-alone RHV adoc file as a test doc? 
Here's the upgrade guide...
[doc-Upgrade_Guide.zip](https://github.com/oVirt/ovirt-site/files/3569607/doc-Upgrade_Guide.zip)

**Comment by rolfedh** [comment]
I have some questions about the proposed approach. The oVirt doc repo is open source. How do we incorporate contributions that others have made directly to that repo? Merging may not be enough. If RHV delivers a subset of oVirt's features, how do we address the features that are not covered in the RHV doc?

**Comment by pmkovar** [comment]
@rolfedh Thanks, I think the archive is missing files from the `common` directory, though.

I agree simple merging may not be enough. My idea is to carefully merge one title at a time, making sure we do not override upstream-only changes that might have been made. Every PR should go through a thorough SME/peer review. 

That said, looking at the git history, the number of upstream-only contributions seems low for most titles under https://github.com/oVirt/ovirt-site/tree/master/source/documentation. 

I'd leave it up for the community contributors to decide what upstream-only features they want to cover in user docs, and how.

Thoughts on improving the workflow welcome, though.

**Comment by duck-rh** [comment]
@pmkovar I heard the documentation is heavily outdated, so it makes sense to merge thinks in (with care for previous contributions), After this is done, I think we should continue with the `upstream first` way Red hat has been doing successfully for long time.

@rolfedh I also need the common directory, currently this is a symlink to a upper directory.

As I began to look at the doc, I noted this:
* this doc is meant to be built as a huge manual; it is split in parts but the chapters are defined in the `master.adoc` file, so we would need to rearrange things a bit to create a TOC instead of including
* files have no headers, thus no title/author/… these would be needed; it's not very difficult but then they would need to be removed to assemble the RHV doc again

**Comment by rolfedh** [comment]
@duck-rh  [common.zip](https://github.com/oVirt/ovirt-site/files/3591668/common.zip)
Here's a zip of the ./docs-Red_Hat_Enterprise_Virtualization/common directory. (Sorry I was gone last week).

**Comment by rolfedh** [comment]
@pmkovar Just brainstorming here: What about practicing "upstream **FIRST**"? That is, why not author all of our content here in the oVirt repo (with an emphasis on features we expect to adopt in RHV) in a scrupulously modular way? Then, we could bring the features and content downstream to RHV and "feature-off" any non-RHV features in the doc.

**Comment by duck-rh** [comment]
thanks @rolfedh 

I was able to compile the document and it looks fine. There are still these errors:
```
asciidoctor: ERROR: master.adoc: line 9: level 0 sections can only be used when doctype is book
asciidoctor: ERROR: master.adoc: line 18: level 0 sections can only be used when doctype is book
asciidoctor: ERROR: master.adoc: line 27: level 0 sections can only be used when doctype is book
asciidoctor: ERROR: master.adoc: line 39: level 0 sections can only be used when doctype is book
```

more notes:
* the above errors are not due to the website's conversion but because they do not follow the header's specifications; `attributes.adoc` contains empty lines and its include is separated from the document title by a newline; once I fixed that the errors vanished and the TOC appeared
* currently all adoc files are processed, I'm experimenting with the layout to avoid this by moving the includes apart
* I had to enable the unsafe mode because some includes reference the parent directory; it's not a big deal but I think it could be improved (as the layout needs to be adapted anyway)
* asciidoctor has a `skip-front-matter` option to skip website generators special headers, so it can be used to ignore Jekyll's frontmatter when generating the RHV version
* the option in `build.cfg` was added in the processor config but this will impact all adoc files on the site and makes it difficult to synchronize with RHV doc. In fact on second look I could not find it in the asciidoctor manual so I was wondering which tool is using this parameter? @rolfedh any idea?

**Comment by pmkovar** [comment]
> I was able to compile the document and it looks fine. There are still these errors:
> 
> ```
> asciidoctor: ERROR: master.adoc: line 9: level 0 sections can only be used when doctype is book
> asciidoctor: ERROR: master.adoc: line 18: level 0 sections can only be used when doctype is book
> asciidoctor: ERROR: master.adoc: line 27: level 0 sections can only be used when doctype is book
> asciidoctor: ERROR: master.adoc: line 39: level 0 sections can only be used when doctype is book
> ```

It looks like the `master.adoc` file is missing some basic header attributes below the title line, something like:

```
:imagesdir: images
:vernum: 4.3
:doctype: book
:toc: left
:toclevels: 3
:numbered!:
:experimental:
```

> * the above errors are not due to the website's conversion but because they do not follow the header's specifications; `attributes.adoc` contains empty lines and its include is separated from the document title by a newline; once I fixed that the errors vanished and the TOC appeared

Speaking of `attributes.adoc`, we will need to add a new attribute for the product name so that we can easily switch between RHV and ovirt without having to find'n'replace:

https://redhat-documentation.github.io/community-collaboration-guide/#ccg-asciidoc-attributes 

>  * currently all adoc files are processed, I'm experimenting with the layout to avoid this by moving the includes apart
> 
>  * I had to enable the unsafe mode because some includes reference the parent directory; it's not a big deal but I think it could be improved (as the layout needs to be adapted anyway)

Perhaps with a symlink? The `commons` directory should be a symlink in any case as we need to share the content across the guides.
 
>  * asciidoctor has a `skip-front-matter` option to skip website generators special headers, so it can be used to ignore Jekyll's frontmatter when generating the RHV version

I think that we want to maintain two separate master files for ovirt and RHV, for each title. That will make the frontmatter maintenance much easier.
 
>  * the option in `build.cfg` was added in the processor config but this will impact all adoc files on the site and makes it difficult to synchronize with RHV doc. In fact on second look I could not find it in the asciidoctor manual so I was wondering which tool is using this parameter? @rolfedh any idea?

This is just RHV-specific, I believe we can ignore this file in ovirt, perhaps move `chunk_section_depth: 1` to an ovirt-specific master file if needed.

**Comment by rolfedh** [comment]
> > I was able to compile the document and it looks fine. There are still these errors:
> > ```
> > asciidoctor: ERROR: master.adoc: line 9: level 0 sections can only be used when doctype is book
> > asciidoctor: ERROR: master.adoc: line 18: level 0 sections can only be used when doctype is book
> > asciidoctor: ERROR: master.adoc: line 27: level 0 sections can only be used when doctype is book
> > asciidoctor: ERROR: master.adoc: line 39: level 0 sections can only be used when doctype is book
> > ```

Would it be possible to know _which_ of the books generated these errors? Recently, a colleague and I created common/collateral_files/attributes.adoc and included it the master.adoc for four of the guides. Although attributes.adoc contains `:doctype: book`, I wonder if it is related to these errors. 

> It looks like the `master.adoc` file is missing some basic header attributes below the title line, something like:
> 
> ```
> :imagesdir: images
> :vernum: 4.3
> :doctype: book
> :toc: left
> :toclevels: 3
> :numbered!:
> :experimental:
> ```
> 
> > * the above errors are not due to the website's conversion but because they do not follow the header's specifications; `attributes.adoc` contains empty lines and its include is separated from the document title by a newline; once I fixed that the errors vanished and the TOC appeared

We'll fix this in our files by:

* Removing the empty lines from attributes.adoc 
* Removing the separation between the title and the include for attributes.adoc. 

> 
> Speaking of `attributes.adoc`, we will need to add a new attribute for the product name so that we can easily switch between RHV and ovirt without having to find'n'replace:
> 

We'll look at adding `:product-name: Red Hat Virtualization` to attributes.adoc and replacing that string in our documentation.
 
We'll also discuss how to address any other items you mentioned here.

**Comment by rolfedh** [comment]
I created [an MR](https://gitlab.cee.redhat.com/rhci-documentation/docs-Red_Hat_Enterprise_Virtualization/merge_requests/1452) for these changes last week. Petr merged the changes. Next, Sandro will be addressing tooling issues for the oVirt site and will validate these changes.

**Comment by rolfedh** [comment]
I created [an MR](https://gitlab.cee.redhat.com/rhci-documentation/docs-Red_Hat_Enterprise_Virtualization/merge_requests/1452) for these changes last week. Petr merged the changes. Next, Sandro will be addressing tooling issues for the oVirt site and will validate these changes.

**Comment by sandrobonazzola** [comment]
this is already active on production right? can we close this issue?

**Comment by pmkovar** [comment]
Yes, this is up and running. Thank you, everybody.
