### ISSUE TITLE
Please improve the documentation of the Right-Click context menu for Power Off

### ISSUE THREAD

**Issue by derekatkins** [oVirt/ovirt-site#2132]
#### Description of the problem
I was trying to force power-off a VM.  There's the "Shutdown" button on the VM tab, but no indication of additional functionality.  There's no documentation that indicates the existence of the right-click context menu where one can find power off.

#### Type of problem?
Documentation issue

From https://bugzilla.redhat.com/show_bug.cgi?id=1448491

Go to the VM tab.  There is no "power off" button.
Google for "ovirt power off" and nothing comes up to indicate the right-click context menu.

> First, are you looking for some content in the oVirt documentation itself?
>
> If so, there is a procedure that you can follow here -
> 
> http://www.ovirt.org/documentation/vmm-guide/chap-Administrative_Tasks/
> #shutting-down-a-virtual-machine

Thank you.  This page did not come up on google searches..

> This is a procedure about shutting down virtual machines rather than using
> the right-click context menu itself, but it does contain a note about this
> functionality, and there are several other procedures that provide some
> details as well.
> 
> Does this provide enough detail?

Well, it DOES (obliquely) mention the right click context menu.  However nowhere on the page does it mention "power off".  I would recommend this page get a small update saying:

If the Shutdown fails (e.g. the VM is hung and not responding to the soft shutdown request) then you can force power-off the VM by right clicking the Virtual Machine and using the Power Off method in the menu.

**Comment by emarcusRH** [comment]
Updating the Virtual Machine Management Guide in the downstream - RHV 4.4
https://gitlab.cee.redhat.com/rhci-documentation/docs-Red_Hat_Enterprise_Virtualization/-/merge_requests/1853

**Comment by sandrobonazzola** [comment]
This will be solved on next documentation sync

**Comment by ctomasko** [comment]
Documentation updates done update 
already published in 

https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/virtual_machine_management_guide/index#Shutting_down_a_virtual_machine

and in 
https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/virtual_machine_management_guide/index#Suspending_a_virtual_machine
