### ISSUE TITLE
Reddit integration for blogs.ovirt.org

### ISSUE THREAD

**Issue by sstagnaro** [oVirt/ovirt-site#2137]
It would be nice to have the blog section integrated with [oVirt subreddit ](https://www.reddit.com/r/ovirt) in manner that:

* blog post will be automatically posted to the subreddit (with the whole content, not just the link)
* comments on the subreddit post will shown on the blog post
* users on the blog may only posts through Reddit integration

This will give both posts and comments more visibility.

**Comment by sandrobonazzola** [comment]
@duck-rh is this something possible?

**Comment by duck-rh** [comment]
>     * users on the blog may only posts through Reddit integration

Does this mean you wish to write the post on Reddit instead of the blog?

**Comment by duck-rh** [comment]
It seems there is a plugin which could help: https://wordpress.org/plugins/blog2social/

**Comment by sandrobonazzola** [comment]
> Does this mean you wish to write the post on Reddit instead of the blog?

no, meaning that posts to the blog always get sent to reddit too

**Comment by duck-rh** [comment]
Republishing posts is possible with various plugins but comments are a different beat.

I found two interesting plugins (Reddit for Keyring and Reddit Embed) but both have not been updated for 5-6 years and I could not find anything properly maintained so far. I will revisit this topic but at the moment I do not have any solution to suggest.

**Comment by bencurio** [comment]
I started working on an integration in Golang that can synchronize WordPress posts to a specific subreddit page. When the first working version is ready, I'll paste the URL of the repo here.

**Comment by sandrobonazzola** [comment]
Didn't move in 2 years, no capacity for handling, closing deferred. Feel free to reopen if you have capacity for working on this.
