### ISSUE TITLE
Issue: /404.html

### ISSUE THREAD

**Issue by aalling-jorgensen** [oVirt/ovirt-site#2144]
### Description of the problem
On the page https://ovirt.org/documentation/vmm-guide/chap-Installing_Linux_Virtual_Machines.html you are referring to this page, https://ovirt.org/documentation/vmm-guide/Add_Virtual_Disk_dialogue_entries, under creating a new virtual machine, but the page does not exist.
#### Type of problem?
404

#### Help needed from (use @mention to request assistance)

/Jakob

**Comment by sandrobonazzola** [comment]
thanks for reporting! @michalskrivanek do you know where that link was supposed to point?

**Comment by sandrobonazzola** [comment]
@evol262 do you know where that link was supposed to point?

**Comment by sandrobonazzola** [comment]
Nevermind, found the updated docs references.
