### ISSUE TITLE
Issue: /develop/release-management/features/sla/self-hosted-engine-gluster-support.html

### ISSUE THREAD

**Issue by ThorOra** [oVirt/ovirt-site#2158]
.

Is this Issue something you can help fix?

After installation self hosted engine, hosted engine on ovirt not running.
I already refer this link https://ovirt.org/documentation/self-hosted/chap-Troubleshooting.html but still same

**Comment by sandrobonazzola** [comment]
Please either reach out to users@ovirt.org asking for help or open a bug on https://bugzilla.redhat.com/enter_bug.cgi?classification=oVirt unless you have a specific issue on the development page you referred above. Please note the development page mentioned in the issue title is not meant to be user documentation. For installing hosted engine you should follow the installation guide at https://ovirt.org/documentation/self-hosted/Self-Hosted_Engine_Guide.html
