### ISSUE TITLE
Issue: /documentation/admin-guide/chap-External_Providers.html

### ISSUE THREAD

**Issue by prstaniforth** [oVirt/ovirt-site#2170]
#### Type of problem?
Documentation issue

In the external providers section 
Adding a KVM Host as a Virtual Machine Provider
item one refers to a Xen host not KVM host

 1  Enable public key authentication between the proxy host and the Xen host:

**Comment by sandrobonazzola** [comment]
This has been fixed, https://ovirt.org/documentation/administration_guide/#Adding_KVM_as_an_External_Provider
