### ISSUE TITLE
Issue: /documentation/install-guide/appe-Preparing_a_Local_Manually-Configured_PostgreSQL_Database.html

### ISSUE THREAD

**Issue by wdpjylinyi** [oVirt/ovirt-site#2171]
The command in Step 11 is wrong. The correct command should be "systemctl restart rh-postgresql95-postgresql "

**Comment by sandrobonazzola** [comment]
Documentation for oVirt 4.4 has been updated and rh-postgresql95 is not used anymore. Closing this issue.
