### ISSUE TITLE
Issue: /documentation/vmm-guide/chap-Installing_Linux_Virtual_Machines.html

### ISSUE THREAD

**Issue by cbinyu** [oVirt/ovirt-site#2191]
Step 1. of "Creating Linux Virtual Machines" reads:
"Click Compute &raar; Virtual Machines."

If you look at the source page it is:
"Click <strong>Compute</strong> &amp;raar; <strong>Virtual Machines</strong>"

It should be:
"Click <strong>Compute</strong> &raar; <strong>Virtual Machines</strong>

Same error in step 1 of "Starting Virtual Machines" and step 2 of "Connecting to Virtual Machines".

**Comment by sandrobonazzola** [comment]
Fixed in #2251
