### ISSUE TITLE
Issue: /documentation/gluster-hyperconverged/chap-Deploying_Hyperconverged.html

### ISSUE THREAD

**Issue by kidalabama** [oVirt/ovirt-site#2219]
### Description of the problem
The page has broken links to
https://www.ovirt.org/documentation/gluster-hyperconverged/install-guide/chap-oVirt_Nodes

#### Type of problem?
ovirt nodes links are broken, raising 404 error.

**Comment by sandrobonazzola** [comment]
fixed by #2250
