### ISSUE TITLE
4.0 Release notes link @ http://www.ovirt.org/develop/release-management/releases/4.0/release-management/ is broken

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#224]
Can't find the RN from http://www.ovirt.org/develop/release-management/releases/4.0/release-management/

**Comment by sandrobonazzola** [comment]
Code looks good:
[oVirt 4.0 Release Notes](http://www.ovirt.org/release/4.0.0/)
but it's translated to http://www.ovirt.org/develop/release-management/releases/4.0/release-management/release/4.0.0/ so something broken somewhere else. @garrett can you please have a look?

**Comment by garrett** [comment]
First link works fine for me. Perhaps it was fixed with the redirect changes I made earlier this month? (PR #285)

Closing, as I cannot replicate the error. Please re-open with clarification if I'm incorrect in closing this. :wink:
