### ISSUE TITLE
Fix or remove docker support

### ISSUE THREAD

**Issue by duck-rh** [oVirt/ovirt-site#2254]
### Description of the problem
Docker support is currently broken

#### Type of problem?
Setup issue

The Docker rules are not up-to-date, which leads to #2124 but the list of package to install is not up-to-date and nowadays using CentOS 7 is not gonna work.

Except from the bug above it seems the site developers do not complain about the docker support, so maybe it's not worth the trouble and we should just remove it.

If we want to keep it then why not run the setup script instead of replicating it's work? Also switching to CentOS 8 would help. There are maybe other things to fix but I do not use it thus I have no idea.

@sandrobonazzola what do you think?

**Comment by sandrobonazzola** [comment]
I'm for dropping the docker script
