### ISSUE TITLE
Autogenerated pages point to github resulting in 404 error

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2263]
### Description of the problem

Autogenerated pages like indexes (eg. https://ovirt.org/release/ ) show footer pointing to github for "Edit this page" and "Report an issue with this page".
Since the page is autogenertated there is no corresponding github link, resulting in a 404 error page.
We should have a condition on source/_includes/footer.haml to skip these links on auto-generated pages.

#### Type of problem?
404 | Bug

**Comment by sandrobonazzola** [comment]
@duck-rh I don't know ruby enough to fix this myself, can you handle?

**Comment by duck-rh** [comment]
@sandrobonazzola yes, will have a look at it.
