### ISSUE TITLE
Issue: /404.html

### ISSUE THREAD

**Issue by StormyOS** [oVirt/ovirt-site#2268]
This page: 

https://www.ovirt.org/documentation/admin-guide/virt/console-client-resources/

used to be active, now returns 404:

this is archived version: https://web.archive.org/web/20170218150225/https://www.ovirt.org/documentation/admin-guide/virt/console-client-resources/

**Comment by sandrobonazzola** [comment]
Hi, did you come to that page from any other website link?
The page you're pointing has been merged with other parts in https://ovirt.org/documentation/vmm-guide/chap-Additional_Configuration.html

**Comment by StormyOS** [comment]
It's linked from MANY places, to name a few:
https://github.com/oVirt/moVirt/issues/303
https://lists.ovirt.org/pipermail/users/2018-March/087559.html
https://bugzilla.redhat.com/show_bug.cgi?id=1389321
https://bugzilla.redhat.com/show_bug.cgi?id=1318605
https://bugzilla.redhat.com/show_bug.cgi?id=1353293
https://quorten.github.io/quorten-blog1/blog/2018/10/10/ovirt-howto

Typically pages that change have a redirect, at least first few years :)

**Comment by stoobie** [comment]
@sandrobonazzola  I don't understand something. The original (now missing) page discusses SPICE, VNC and RDP protocols:
https://www.ovirt.org/documentation/admin-guide/virt/console-client-resources/

I don't see any of that mentioned at the page you say now includes that content: https://ovirt.org/documentation/vmm-guide/chap-Additional_Configuration.html

**Comment by duck-rh** [comment]
@sandrobonazzola I agree with @stoobie , I could not find the previous content about all available clients and how to use them anywhere.

**Comment by sandrobonazzola** [comment]
I can see a "Configuring Console Options" section on that page.

**Comment by sandrobonazzola** [comment]
Restoring the original page in #2352

**Comment by sandrobonazzola** [comment]
fixed by #2352
