### ISSUE TITLE
Issue: /

### ISSUE THREAD

**Issue by chierici** [oVirt/ovirt-site#2275]
### Description of the problem
No email received trying to sign up for the forum

#### Type of problem?
I tried several times to register a new account to get access to the user forum but I never receive the confirmation email. I tried both with a gmail account and a corporate one.
Please fix it asap

**Comment by sandrobonazzola** [comment]
Hi, I suppose you're trying to subscribe through https://lists.ovirt.org/admin/lists/users.ovirt.org/
I don't see any subscription request pending there, did you succeed?
Subscription to mailing list require approval for reducing the spam, it takes a while (usually less than a day) between the subscription request and its approval.

**Comment by chierici** [comment]
I've tried several times, the page I'm trying to subscribe from is:
https://lists.ovirt.org/accounts/signup/?next=%2Fadmin%2Flists%2Fusers.ovirt.org%2F

If I try to subscribe again, I get an error because email/user is already registered, then I get a screen with a warning about a confirmation email that has been sent to my address, but I don't get any message at all. So basically I'm stuck.
Can you provide any help on that?

**Comment by duck-rh** [comment]
@chierici I saw two accounts that could be you in the database and they are already verified (meaning the email address was checked). Now you just need to login here (https://lists.ovirt.org/accounts/login/) first before being able to subscribe to a list.

If you forgot your password there is a `Forgot Password?` link on the same page.

I would also point out you need to be careful about which of the email address you use, since there is no way to merge separate accounts unfortunately.

**Comment by chierici** [comment]
Sorry but it's not working. I've never received the confirmation email and hence I couldn't confirm the account. Trying to log in I keep beeing redirected to the page asking me to verify my email.  (Confirmation e-mail sent to axxxx@gmail.com).
Why is it so difficult??!!

**Comment by sandrobonazzola** [comment]
@chierici we are using hyperkitty software there and as all sofware it may have bugs or crashes. We are looking into what's going on. As @duck-rh said, on hyperkitty database everything looks fine so it may be an issue with the mailer program. Please let us investigate and have the time to fix the issue.

**Comment by chierici** [comment]
Something finally happened, even old confirmation emails started to arrive. Now I was able to sign-in. Thanks a lot guys! Didn't mean to be rude atall!

**Comment by sandrobonazzola** [comment]
Glad to see this has been solved. Closing the ticket.

**Comment by duck-rh** [comment]
@chierici thanks to another bug report which is totally unrelated I was able to find a problem on the server, sorry.
