### ISSUE TITLE
Issue: /documentation/upgrade_guide/

### ISSUE THREAD

**Issue by BrianSipos** [oVirt/ovirt-site#2287]
#### Documentation issue

Within the section "Migrating hosts and virtual machines from oVirt 4.3 to 4.4" there is discussion about installing a fresh CentOS 8 and then re-enrolling the host in the cluster, and the next section discusses how to migrate local storage data. But there is no mention anywhere in the document about upgrading hosts which serve gluster bricks to volumes used as storage domains.

My naive interpretation of the upgrade with bricks present is that the old bricks would need to be completely replaced by new bricks (on the new CentOS 8 gluster peer), which would result in high network traffic as the new bricks replicate the data. But is there a recommended way to re-add the gluster peer with the same peer UUID and re-use the existing bricks?
My suspicion is that backing-up-and-restoring the `/var/lib/glusterd` tree will accomplish this, but obviously this would need to be verified to work properly before it becomes a recommended procedure. And there may be more nuance than this that I'm overlooking.

Can the gluster peer be fully restored (along with its existing bricks) by simply restoring the `/var/lib/glusterd` tree?

**Comment by sandrobonazzola** [comment]
@gobindadas can you please have a look?

**Comment by gobindadas** [comment]
@sandrobonazzola Soon will send patch.

**Comment by sandrobonazzola** [comment]
@gobindadas any update?

**Comment by emarcusRH** [comment]
This content is now live in the oVirt documentation portal - https://www.ovirt.org/documentation/upgrade_guide/index.html#Upgrading_hypervisor_preserve_gluster_storage
