### ISSUE TITLE
Issue: /release/4.3.10/

### ISSUE THREAD

**Issue by BSipos-RKF** [oVirt/ovirt-site#2288]
### Description of the problem
oVirt 4.3.10 release notes indicate it is usable on CentOS 7.7 but actual packages require CentOS 7.8 on host.

#### Type of problem?
Content issue

The text at the top of the 4.3.10 indicates that it is compatible with CentOS 7.7 but when I try to install on a 7.7 host I get a failed dependency from vdsm to lvm2 package. I see from the release notes at <https://lists.ovirt.org/archives/list/announce@ovirt.org/message/XKYRNKUUVGRG3H3QLIS5BCLEFCR4SOOG/> that the compatibility is really CentOS 7.8, which seems to have all proper dependencies.

Should the release notes be updated to say 7.8 instead?

**Comment by sandrobonazzola** [comment]
Thanks for reporting, fixing

**Comment by sandrobonazzola** [comment]
Fixed by #2290
