### ISSUE TITLE
Issue: /404.html

### ISSUE THREAD

**Issue by AlbanVidalenche** [oVirt/ovirt-site#2317]
I got a 404 error when I clicked on "oVirt Metrics Store Installation Guide"
 
In the bottom of this page : https://www.ovirt.org/develop/release-management/features/metrics/metrics-store-all-in-one.html
If you click on "oVirt Metrics Store Installation Guide", it takes you to:
https://www.ovirt.org/documentation/metrics-install-guide/metrics-install-guide 
This page doesn't exist.

The right URL seems to be https://www.ovirt.org/documentation/metrics-install-guide/metrics_store_installation_guide.html

**Comment by sandrobonazzola** [comment]
Fixed by #2327
