### ISSUE TITLE
kubernetes.io oVirt topic to be removed

### ISSUE THREAD

**Issue by celestehorgan** [oVirt/ovirt-site#2329]
### Description of the problem

oVirt documentation on kubernetes.io is about to be removed in https://github.com/kubernetes/website/pull/23500. If your team wants to, migrate the content [in this file](https://github.com/kubernetes/website/blob/fc3a6220bf81957dfdc5f78577d212fb3404665a/content/en/docs/setup/production-environment/on-premises-vm/ovirt.md) to your own documentation website.

#### Type of problem?
Documentation issue | Content issue | Formatting issue | 404 | **something else**

Hello oVirt docs maintainers!

The Kubernetes documentation currently has a page, [oVirt](https://v1-18.docs.kubernetes.io/docs/setup/production-environment/on-premises-vm/ovirt/), which documents using oVirt Cloud Provider to add VMs as nodes to a k8s cluster. We have [a pull request open to remove this content](https://github.com/kubernetes/website/pull/23500), which will be approved and merged shortly. We are opening this issue to give you information on why this is happening, and what you can do if you'd like to keep that content around. 

Recently we approved and implemented [a policy about not including third party content in our docs](https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content). Kubernetes is huge, and many for-profit companies were using our documentation as free advertisement. We wanted to remove the opportunity for companies to do this, but to be fair to the entire Kubernetes community and reduce ambiguity in the policy, this also means we need to remove content about "third party" open source projects like oVirt too :(

This policy is no longer up for discussion. However, there were concerns from our docs maintainers about whether or not valuable content would be lost. Thus, we wanted to give your team the opportunity to migrate this content over to your own site, if you feel it's of value. 

#### Help needed from (use @mention to request assistance)

No specific help needed. You can choose to migrate this content or not migrate this content, and close this issue as required.

-- Much love,
Kubernetes SIG Docs

**Comment by sandrobonazzola** [comment]
@gekorob, @Gal-Zaidman, @eslutsky, @rgolangh is this still relevant?

**Comment by Gal-Zaidman** [comment]
> @gekorob, @Gal-Zaidman, @eslutsky, @rgolangh is this still relevant?

Well, we can add a section in the ovirt docs for OCP/k8s related content,
Don't think this is a high priority since we have docs on the OCP project.

**Comment by sandrobonazzola** [comment]
@stoobie anyone in doc team willing to pick this task?

**Comment by sandrobonazzola** [comment]
Closing, didn't get any attention or interest in a year.
