### ISSUE TITLE
Issue: /documentation/upgrade_guide/

### ISSUE THREAD

**Issue by prstaniforth** [oVirt/ovirt-site#2332]
#### Type of problem?
Documentation issue

in the upgrade guide in the Prerequisites section it has 4.4-Beta instead of 4.4
Ensure your environment meets the requirements for oVirt 4.4-beta. For a complete list of prerequisites, see the Planning and Prerequisites Guide.

**Comment by sandrobonazzola** [comment]
Thanks for reporting!
