### ISSUE TITLE
Allow cloning a VM in the VM Portal

### ISSUE THREAD

**Issue by nkovacne** [oVirt/ovirt-site#2389]
#### Description of the problem

The feature of cloning a VM was available in the old User Portal and it's not supported anymore by the newer VM Portal (since oVirt 4.3). In our case, oVirt is used by hundreds of students who deploy their machines, and this feature was useful to them since they deploy cluster, HA topologies and so and they earned a lot of them cloning the VMs instead of deploying a big number of them.

Could the VM cloning option be implemented in the new VM Portal?

#### Type of problem?
Feature request

**Comment by sandrobonazzola** [comment]
Please report this to bugzilla.redhat.com, this issue tracker is for the oVirt website content

**Comment by nkovacne** [comment]
Added as https://bugzilla.redhat.com/show_bug.cgi?id=1897175
