### ISSUE TITLE
bad numbering on Hosted Engine host operating system upgrade Howto

### ISSUE THREAD

**Issue by didib** [oVirt/ovirt-site#243]
Now noticed that the numbering on [1] is different from [2], which is the same page but rendered using github.

E.g. "Migrate VMs as needed to the new host" is numbered "7" in [2] but '1' in [1]. Likely something in the markdown causes the renderer to exit the list, and start a new one, where in github it's a single long list as it should be.

[1] https://www.ovirt.org/documentation/how-to/hosted-engine-host-OS-upgrade/
[2] https://github.com/oVirt/ovirt-site/blob/master/source/documentation/how-to/hosted-engine-host-OS-upgrade.html.md

**Comment by sandrobonazzola** [comment]
@garrett any hint on what's causing the different numbering?

**Comment by garrett** [comment]
The site does not use GitHub markdown, but Kramdown. Perhaps the indentation is not quite right?

Here are the specific docs on using lists in Kramdown: http://kramdown.gettalong.org/quickref.html#lists

In most cases, the Markdown flavors are close enough, but they're not exactly the same thing. (There is no one Markdown, only many flavors.) Eventually, there will be [CommonMark](http://commonmark.org/), but it's basically in an **xkcd 927** state at the moment.

[![xkcd 927](https://imgs.xkcd.com/comics/standards.png)](https://xkcd.com/927/)

**Comment by garrett** [comment]
Please check the commit with the explanation of what I did as well as a diff with all the changes @ https://github.com/oVirt/ovirt-site/commit/0c84f649898856101763ba20672cf38dec63d5c7.
