### ISSUE TITLE
Issue: /getting 500 internal server error 

### ISSUE THREAD

**Issue by surendra10125** [oVirt/ovirt-site#2495]
after update the packages in engine gui it restarted and then it is showing 500 internal server error

**Comment by sandrobonazzola** [comment]
Please open a bug report at https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine including as many details as possible.

**Comment by duck-rh** [comment]
@surendra10125 here is the place for the website and documentation, not the Engine UI.
