### ISSUE TITLE
oVirt blog header does not handle responsiveness well

### ISSUE THREAD

**Issue by janosdebugs** [oVirt/ovirt-site#2524]
### Description of the problem

The oVirt blog header doesn't handle tablet sizes correctly. This has been fixed on the main site.

#### Type of problem?

Formatting issue

![image](https://user-images.githubusercontent.com/86970079/124737053-2137c400-df07-11eb-9008-6755d42b1051.png)

**Comment by sandrobonazzola** [comment]
@jasonbrooks can you help with this one?

**Comment by sandrobonazzola** [comment]
Closing wontfix,didn't got attention over the past year, not going to be handled.
