### ISSUE TITLE
Issue: /develop/release-management/features/storage/backup-restore-disk-snapshots.html

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2533]
### Description of the problem

- ./_site/develop/release-management/features/storage/backup-restore-disk-snapshots.html
  *  External link https://github.com/oVirt/ovirt-engine-sdk/blob/master/sdk/examples/download_disk_snapshots.py failed: 404 No error

#### Type of problem?
404

**Comment by danielerez** [comment]
Should be replaced with:
https://github.com/oVirt/ovirt-engine-sdk/blob/master/sdk/examples/download_all_disk_snapshots.py

**Comment by danielerez** [comment]
PR: https://github.com/oVirt/ovirt-site/pull/2539

**Comment by sandrobonazzola** [comment]
Closed via #2539
