### ISSUE TITLE
Issue: /develop/release-management/features/network/networking-api-security-groups.html

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2534]
### Description of the problem

- ./_site/develop/release-management/features/network/networking-api-security-groups.html
  *  External link http://www.openvswitch.org/support/dist-docs/ovn-nb.5.html failed: 404 No error

#### Type of problem?
404

**Comment by almusil** [comment]
After the ovs/ovn split they moved it moved to https://www.ovn.org/support/dist-docs/ovn-nb.5.html I will create PR for it.
