### ISSUE TITLE
New Download page proposal

### ISSUE THREAD

**Issue by sstagnaro** [oVirt/ovirt-site#2559]
### Description of the problem
Both **Download** page and **Alternate Downloads** page are currently an abstract of the Installation guides. This can lead to confusion because they don't provides sufficient details.

#### Proposal
The new download page could be re-designed with a chained combo box filled with simple questions, in order to discover the desired architecture and provide the link to the correct Installation Guide.

I've drew a very basic mock-up in order to show how it should work.

How the Download page should appears at first:
![oVirt org Download Mockup](https://user-images.githubusercontent.com/15886238/130102067-40c04e92-6961-4ef2-a900-5b161ae5aa7b.png)

Second question in case of Self Hosted Engine:
![oVirt org Download Mockup (1)](https://user-images.githubusercontent.com/15886238/130102109-6558467c-1e20-4dae-b7ca-b8ff35a6d832.png)

Second question in case of Stand-alone Engine:
![oVirt org Download Mockup (2)](https://user-images.githubusercontent.com/15886238/130102150-5690c3f7-7983-4e17-beb1-0e9f6459de22.png)

Link to the correct Installation Guide:
![oVirt org Download Mockup (4)](https://user-images.githubusercontent.com/15886238/130103052-a7d126b3-8052-4364-a4e7-083e43839ec0.png)

**Comment by sandrobonazzola** [comment]
@sstagnaro any chance you are also able to implement this?

**Comment by sandrobonazzola** [comment]
No capacity for implementing this, closing deferred. Feel free to reopen if you have capacity for working on this
