### ISSUE TITLE
ovirt go sdk

### ISSUE THREAD

**Issue by nzubarev122** [oVirt/ovirt-site#2563]
Hello.

I need help creating a virtual machine using https://github.com/oVirt/go-ovirt
I need set cmdline vm , Please help me

my create vm configuration, but cmd not set 

image.png

Vm(
   ovirtsdk4.NewVmBuilder().
      Name(*name).
      Console(
         ovirtsdk4.NewConsoleBuilder().
            Enabled(true).
            MustBuild()).

      Memory(ram2 * int64(1<<30)).
      MemoryPolicy(
         ovirtsdk4.NewMemoryPolicyBuilder().
            Guaranteed(int64(ram2) * int64(1<<30)).
            Max(int64(ram2) * 2 * int64(1<<30)).
            Ballooning(true).
            MustBuild()).

      //  Memory(int64(ram2) * int64(1<<30)).

      Os(
         ovirtsdk4.NewOperatingSystemBuilder().
            CustomKernelCmdline("qemu_cmdline").Cmdline("qemu_cmdline").Boot(
            ovirtsdk4.NewBootBuilder().
               DevicesOfAny(
                  ovirtsdk4.BOOTDEVICE_NETWORK,
                  ovirtsdk4.BOOTDEVICE_HD).
               MustBuild()).
            MustBuild()).

     

      HighAvailability(
         ovirtsdk4.NewHighAvailabilityBuilder().
            Enabled(true).
            MustBuild()).
      Cpu(
         ovirtsdk4.NewCpuBuilder().
            Topology(
               ovirtsdk4.NewCpuTopologyBuilder().
                  Cores(cpu2).
                  Sockets(1).
                  MustBuild()).
            MustBuild()).
      Cluster(
         ovirtsdk4.NewClusterBuilder().
            Name(Cluster).
            MustBuild()).
      Template(
         ovirtsdk4.NewTemplateBuilder().
            Name("Blank").
            MustBuild()).
      MustBuild()).
Send()

**Comment by nzubarev122** [comment]
here https://github.com/oVirt/ovirt-engine-sdk-go/issues/238

**Comment by sandrobonazzola** [comment]
@janosdebugs can you please review?

**Comment by janosdebugs** [comment]
Hello @nzubarev122,

What exactly are you trying to do? Can you show an example of what cmdline you would want to set?

Also note, that the go-ovirt SDK is auto-generated. Not every function that's in here actually works. We are working on a [better SDK with limited functionality](https://github.com/ovirt/go-ovirt-client). Feel free to open issues on that repository for features you need.

**Comment by sandrobonazzola** [comment]
closing as stale. If you still need help on interacting with oVirt using Go I would recommend to discuss on users@ovirt.org mailing list.

**Comment by nzubarev122** [comment]
hello. i need help .

i need to Extend size by Vm via GO sdk , please send example. And how can
i Extend size via ovirt api. Please help

[image: image.png]

ср, 12 янв. 2022 г. в 10:43, Sandro Bonazzola ***@***.***>:
