### ISSUE TITLE
Issue: Contributing guidelines should state prerequisites

### ISSUE THREAD

**Issue by stoobie** [oVirt/ovirt-site#2599]
I am not able to preview the site locally by following these instructions in CONTRIBUTING.MD:

```
rvm use 2.7
./setup.sh && ./run-server.sh
```
### Description of the problem
I do not have rvm or Ruby 2.7 installed by default, and I am having other issues as well, and I'm still not able to successfully preview my changes.

#### Type of problem?
Documentation issue

**Comment by gocallag** [comment]
@sandrobonazzola  is this still a valid issue given we now use the docker container method?
