### ISSUE TITLE
Issue: Default "master" branch > "main"

### ISSUE THREAD

**Issue by apinnick** [oVirt/ovirt-site#2605]
As part of its conscious language initiative, Red Hat recommends calling the default branch "main" instead of "master".

**Comment by duck-rh** [comment]
@sandrobonazzola sorry I must have missed your (now dated) reply:-/. I'll work on it then.

**Comment by sandrobonazzola** [comment]
Thanks

**Comment by duck-rh** [comment]
I switched the branch to `main` and updated all references in  #3005. GH takes care of updating the PRs. Previews are working well.

The production builder was also updated: https://gerrit.ovirt.org/c/infra-ansible/+/118490

Please reopen this ticket is you see any problem.
