### ISSUE TITLE
Need guidelines on how to contribute to oVirt documentation.

### ISSUE THREAD

**Issue by stoobie** [oVirt/ovirt-site#2632]
### Description of the problem

The community requires guidelines on how to contribute to oVirt documentation.

#### Type of problem?
Documentation issue, Content issue

Need to provide details on what info is required in a PR description.

We can also leverage the OpenShift guidelines:
https://github.com/openshift/openshift-docs#contributing-to-openshift-documentation

**Comment by sandrobonazzola** [comment]
Closed by #2633
