### ISSUE TITLE
Cockpit installation is no longer supported. Need to update website

### ISSUE THREAD

**Issue by stoobie** [oVirt/ovirt-site#2668]
### Description of the problem

The Cockpit hosted-engine installation is no longer supported, and the Cockpit hosted-engine installation guide was removed. Need to update the website and the various projects to stop referring to this installation method.

#### Type of problem?
Content issue

#### Details
Pages that I found so far that need to be updated:

- [ovirt-web-ui README](https://github.com/oVirt/ovirt-web-ui#readme)
- [The oVirt site Downloads page](https://ovirt.org/download/)

I didn't do an exhaustive check across all the different oVirt sites, so someone needs to do that.

**Comment by sgratch** [comment]
@stoobie can we close this as DONE?

**Comment by stoobie** [comment]
@sgratch @emarcusRH You definitely addressed the specific occurrences I noticed and pointed out in the description.

However, the issue also states **I didn't do an exhaustive check across all the different oVirt sites, so someone needs to do that.**

If that hasn't yet been done, then you should create a new issue or leave this one open. @sandrobonazzola What do you think?

**Comment by emarcusRH** [comment]
I checked everything in the over-site repo at the root level - not only documentation. 
Aside from old release notes and dev notes, there is no longer any mention of the SHE Cockpit install 
feel free to close this issue

**Comment by stoobie** [comment]
This issue applies to github.com/ovirt, not just /ovirt/ovirt-site. But I don't see a way to add an issue to /ovirt.

**Comment by sandrobonazzola** [comment]
Let's consider this done for ovirt-site. We'll open an issue on the specific projects which will still mention cockpit installation.

**Comment by emarcusRH** [comment]
> Let's consider this done for ovirt-site. We'll open an issue on the specific projects which will still mention cockpit installation.

AS far as I could find at this time, the only place that still had a link to the old SHE via Cockpit installation was the web admin portal - the login or welcome page, and according to Sharon Gratch, they managed to get it into the RHV 4.4.10 release.
