### ISSUE TITLE
Travis build fails for merged ovirt-site content

### ISSUE THREAD

**Issue by mwperina** [oVirt/ovirt-site#267]
Travis build fails for already merged ovirt-site content with following error:

== Request: /develop/release-management/features/sla/deploy-hosted-engine-hosts-via-engine/index.html

       error  build/develop/release-management/features/sla/deploy-hosted-engine-hosts-via-engine/index.html

undefined method `split' for nil:NilClass

@jasonbrooks could you please take a look?

**Comment by mykaul** [comment]
@rgolangh  - Roy, can it be related to:
commit 291afd50c292fcb718c8d8c5da02302b8005679e
Author: Roy Golan <royg21@gmail.com>
Date:   Wed May 25 12:42:50 2016 +0300

    Create deploy-hosted-engine-hosts-via-engine.md

**Comment by jasonbrooks** [comment]
@mwperina It was missing frontmatter, see discussion in #268

**Comment by mscherer** [comment]
I guess this issue can be closed, since #268 is closed.
