### ISSUE TITLE
ovirt-documentation automatically tagged before PR is ready for peer review

### ISSUE THREAD

**Issue by stoobie** [oVirt/ovirt-site#2688]
### oVirt documentation PRs should be reviewed first by SME and only after technical review is completed, by ovirt-documentation team.

This functionality occurs because ovirt-documentation is tagged in CODEOWNERS for /source/documentation.

Two possible ways to deal with this problem:
* oVirt documentation team does not review the PR until after SME has reviewed it.
* Remove ovirt-documentation from CODEOWNERS, to disable the automatic tagging and avoid confusion. Depend on contribution guidelines to direct community contributors to manually tag ovirt-documentation.

**Comment by sandrobonazzola** [comment]
Fixed via #2689
