### ISSUE TITLE
asciidoctor reports invalid part within upgrade guide

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2693]
#### Type of problem?
Documentation issue
```
         Rendering: documentation/upgrade_guide/index.adoc
  Pre-Render Hooks: documentation/upgrade_guide/index.adoc
  Rendering Markup: documentation/upgrade_guide/index.adoc
asciidoctor: ERROR: index.adoc: line 40: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
  Rendering Layout: documentation/upgrade_guide/index.adoc
```

**Comment by apinnick** [comment]
Sandro, which log has this error? Is it a GitHub action? Local build?

**Comment by sandrobonazzola** [comment]
@apinnick noticed it while running local build as github actions were under outage

**Comment by apinnick** [comment]
If it showed up in your local build but it is not showing up in the GitHub actions logs, you don't need to worry about it. 

RHV docs have some odd things that cause Asciidoctor errors but the docs still build. As long as the docs build on gh-pages, the site is fine.

It will take a while to align the docs with current Asciidoc requirements.

**Comment by apinnick** [comment]
@sandrobonazzola 
I reran the GitHub actions for your PR. The Asciidoc error message appeared in the log but the site built successfully. 

Since the error message is not blocking the build, I think we can close this issue.
