### ISSUE TITLE
[RFE]  Added a mini TOC for feature pages. 

### ISSUE THREAD

**Issue by fbacchella** [oVirt/ovirt-site#270]
Some page can be quit long:

http://www.ovirt.org/develop/release-management/features/storage/importstoragedomain/

A mini-TOC for this page should be generated, so it's possible to know the important part in it. It will make easer to the reader to found that there is API documentation in it for example.

**Comment by mureinik** [comment]
This was already requested by Issue #181. Closing so we can track it in one place only.
