### ISSUE TITLE
Documentation inaccurate for installing oVirt on RHEL

### ISSUE THREAD

**Issue by rwmjones** [oVirt/ovirt-site#2709]
### Type of problem?
Documentation issue

### Description of the problem

https://www.ovirt.org/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.html#Enabling_the_Red_Hat_Virtualization_Manager_Repositories_install_RHVM

The documentation starts by saying you must enable `javapackages-tools` module, but this doesn't work on RHEL 8 out of the box.  The first step on RHEL is to enable various subscription-manager repos.

Assuming the machine is registered already with RHN, you will need to run these commands first, before proceeding with the dnf commands:

```
subscription-manager repos --enable=advanced-virt-for-rhel-8-x86_64-rpms
subscription-manager repos --enable=advanced-virt-crb-for-rhel-8-x86_64-rpms 
subscription-manager repos --enable=codeready-builder-for-rhel-8-x86_64-rpms
```

**Comment by Conan-Kudo** [comment]
I'm not sure if advanced-virt is going to be required with RHEL 8.6? I've seen the rebases normally going into AV landing in CentOS Stream 8 proper...

**Comment by rwmjones** [comment]
Yes that is true.  However `codeready-builder-for-rhel-8-x86_64-rpms` is still needed.

**Comment by Conan-Kudo** [comment]
Yup, that's true.

**Comment by apinnick** [comment]
@sandrobonazzola @rwmjones 
Does this issue apply only to oVirt? Or should we open a Bugzilla for RHV?

**Comment by sandrobonazzola** [comment]
It's ovirt only.

**Comment by apinnick** [comment]
> It's ovirt only.

In that case, do you object to my creating a label called 'upstream' so that we know that it only applies to upstream docs? Then we can tag the other upstream issue (P&P) guide as well.

**Comment by sandrobonazzola** [comment]
ok for me using upstream label

**Comment by apinnick** [comment]
Great. If we ever need a downstream label to indicate that the issue has to have a BZ created for RHV, I can create one. Should make it easier for us to keep the issues separate and to make sure they are triaged.

**Comment by rwmjones** [comment]
I only tried oVirt, don't know if it applies to RHV or not.

**Comment by apinnick** [comment]
> I only tried oVirt, don't know if it applies to RHV or not.

Good point. It's worth looking at the installation guides to see whether this documentation is there as well. I will follow up on it.

**Comment by sandrobonazzola** [comment]
Adding instructions with oVirt 4.5.0 beta in pr #2821
