### ISSUE TITLE
Review requirement makes TWs less effective

### ISSUE THREAD

**Issue by apinnick** [oVirt/ovirt-site#2726]
#### Type of problem?

Permissions issue 

The review requirement for all PRs makes the RHV documentation team less effective. Can you create an exception for our team? We are in different time zones and have different weeks. That means that sometimes no one is available if we need to apply an urgent fix. It is also annoying if we need to fix a typo.

No other upstream documentation repository does this. OpenShift-docs allows a few senior writers to merge PRs because they have 40+ writers, but those with merge rights can merge their own PRs. 

Please remove the review requirement for PRs created by the RHV docs team so that we can work more effectively. Also, it will mean a lot less work for the reviewers. We will need to make hundreds of updates soon in order to comply with the new publication platform. (This will not affect oVirt docs in any way. The changes involve metadata and following updated Asciidoc conventions.)

**Comment by janosdebugs** [comment]
Hey @apinnick there is, as far as I know, no way to remove the review requirement for a single team, it would remove the review requirement for all changes. If that's OK, @sandrobonazzola has permissions to remove this from the branch protection.

The alternative would be to remove the review requirement, but create a GitHub Action that checks the permission level of a user and the presence of a review. However, I currently don't have time to work on such a feature.

**Comment by apinnick** [comment]
@janosdebugs Thanks, Janos. I agree that creating a GH action to check a user's permission level is way too much work.

@sandrobonazzola Could you remove the review requirement for all changes? I assume that you don't give maintainer or contributor rights to hundreds of people. Most projects trust their maintainers to make intelligent choices about merging. 

We have a peer review process for Red Hat documentation, which is a safeguard against merging a bad PR. So our substantive PRs are reviewed by someone else before they are merged. However, we also need the freedom to make changes quickly if we see that something needs to be fixed.

**Comment by sandrobonazzola** [comment]
The doc team can now bypass the review requirements, please let me know if it works for you.

**Comment by janosdebugs** [comment]
@sandrobonazzola what change did you do?

**Comment by sandrobonazzola** [comment]
I changed Settings -> Branches -> Branch protection rules -> master -> Allow specified actors to bypass pull request requirements -> Added "oVirt/ovirt-documentation" team.

**Comment by janosdebugs** [comment]
Oh, that's new, I didn't know that. Thanks!

**Comment by janosdebugs** [comment]
However, that means the docs team can also merge if CI doesn't pass, right? @apinnick docs folks have to be careful then.

**Comment by apinnick** [comment]
Yes, that is true. I will caution them and make sure that they check the status of the checks. I will also check whether they know how to revert a merge and I can help with troubleshooting if someone has problems. 

I want to create a small PR to test this.

Thanks so much!

**Comment by apinnick** [comment]
@sandrobonazzola  I still get a blocked PR: https://github.com/oVirt/ovirt-site/pull/2727

**Comment by sandrobonazzola** [comment]
I see it's still running CI, I think the bypass is only on the review requirement. Let's wait for Ci to finish.

**Comment by apinnick** [comment]
@sandrobonazzola @janosdebugs 
YES! It works. The weird thing is that the UI looks like it is blocking a merge. But when I clicked the **red** "Squash and merge" button, there was a check box to merge with my Admin privileges. So I will update the team on what to expect and make sure that they understand that they must wait for the checks to finish AND check the PR preview build.

Thank-you!
