### ISSUE TITLE
Table of content has wrong tree rooted on "oVirt Key Components"

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2783]
### Description of the problem

Table of content has wrong tree rooted on "oVirt Key Components" on https://ovirt.org/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.html 
![image](https://user-images.githubusercontent.com/937860/158768245-d117612a-12fd-4dd9-85a0-cf58d4055e12.png)

I would have expected "oVirt Key Components" to be at same level of "Installation Overview"

#### Type of problem?
Formatting issue

**Comment by apinnick** [comment]
Fixed.
