### ISSUE TITLE
wrong link to host requirements

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2786]
#### Type of problem?
Documentation issue 

https://ovirt.org/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.html#Installing_Red_Hat_Virtualization_Hosts_SM_localDB_deploy

![image](https://user-images.githubusercontent.com/937860/158778160-0c9ce815-cba4-43c0-a5a1-eb960f871430.png)

[host requirements](https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/planning_and_prerequisites_guide/index#host-requirements). ponts to Red Hat docs instead of https://ovirt.org/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.html#host-requirements

**Comment by ctomasko** [comment]
Docs team backlog. https://issues.redhat.com/browse/RHV-45352
