### ISSUE TITLE
Banner proposal for 4.5.0 GA

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2797]
#### Type of problem?
Content issue 

Proposing banners for 4.5.0 GA
Website:
![Site Banner](https://user-images.githubusercontent.com/937860/159287738-362a4ee9-c86e-4524-b8e0-e7326d16d79f.png)

Twitter:
![Twitter Banner](https://user-images.githubusercontent.com/937860/159287609-515e75dd-f5b4-405c-9749-f1eb77ee84d0.png)

Reddit:
![Reddit Banner](https://user-images.githubusercontent.com/937860/159287826-c2028bb5-e980-4544-bc92-d9baa240b5fc.png)

Facebook:
![Facebook Banner](https://user-images.githubusercontent.com/937860/159287894-9b687677-8336-4935-a9b5-a305d406c4d4.png)

Linkedin:
![LinkedIn Banner](https://user-images.githubusercontent.com/937860/159287934-005f1a82-70e8-42a0-a642-03c31f645b81.png)

**Comment by sandrobonazzola** [comment]
Sources:

![Facebook Banner](https://user-images.githubusercontent.com/937860/159288385-dfe1e66d-2468-4895-ace0-7274fe747d02.svg)
![LinkedIn Banner](https://user-images.githubusercontent.com/937860/159288387-68c243ed-e26a-497b-96a6-f0cc8184e7a8.svg)
![Reddit Banner](https://user-images.githubusercontent.com/937860/159288389-50fb93cc-69b5-45b7-bfab-ea08dadc7661.svg)
![Site Banner](https://user-images.githubusercontent.com/937860/159288391-c37b7c3a-8d55-456f-9a34-069e9993cbdb.svg)
![Twitter Banner](https://user-images.githubusercontent.com/937860/159288392-0da1530a-b5fe-41f7-8d88-994f4a2c43a8.svg)

**Comment by sandrobonazzola** [comment]
@oVirt/developers any comment?

**Comment by erav** [comment]
I vote for the one with the 'download now' text

**Comment by michalskrivanek** [comment]
our download's always a little more complicated than for many other projects, i'd be happy with just "4.5 has been released!":)

**Comment by nirs** [comment]
If I understand correctly, this PR propose multiple banners for the ovirt side, twitter, facebook, reddit and linked in.

The banners use different font families and weights (e.g "4.5" is sometimes bold and sometimes not). Is this intended?

**Comment by sandrobonazzola** [comment]
Thanks for the feedback! I'll try to uniform font sizing and styling. About the download button I also got feedback that cyrcles needs better alignment. I agree with @barpavel , pointing to somewhere with instructions on how to download make sense here.

**Comment by sandrobonazzola** [comment]
Second round: didn't touch the Reddit banner.

Site:
![Site Banner](https://user-images.githubusercontent.com/937860/161108631-ff70e2f5-0ece-48e7-aee5-483e45090df7.png)

Facebook:
![Facebook Banner](https://user-images.githubusercontent.com/937860/161108711-8fc9894f-574c-46d0-a120-cd335ad46201.png)

Linkedin:
![LinkedIn Banner](https://user-images.githubusercontent.com/937860/161108828-4678b4f3-6ed1-4c4f-8bcc-fd3a14bcc49b.png)

Twitter:
![Twitter Banner](https://user-images.githubusercontent.com/937860/161108901-b194ea95-2446-4c1c-b48f-6997b1d2541b.png)

Sources:
![Facebook Banner](https://user-images.githubusercontent.com/937860/161109097-53e8c38c-f63b-4174-a1ba-402b2bd059ea.svg)
![LinkedIn Banner](https://user-images.githubusercontent.com/937860/161109100-191d7472-80f1-4c21-980a-67c58a75ce5a.svg)
![Site Banner](https://user-images.githubusercontent.com/937860/161109101-88fade08-d97b-48cc-861b-afcf8b6b66df.svg)
![Twitter Banner](https://user-images.githubusercontent.com/937860/161109102-ec1796ba-95c4-45a5-bba3-3e203fb43024.svg)

**Comment by nirs** [comment]
Looks good now :+1:

**Comment by barpavel** [comment]
LGTM :)

**Comment by erav** [comment]
in the image before last the 'download now!' is larger than the blue button. otherwise LGTM
