### ISSUE TITLE
Add "Blog" tab in top navbar and switch Develop/Community tabs

### ISSUE THREAD

**Issue by thatdocslady** [oVirt/ovirt-site#28]
The Blog tab should link to a page that contains the "archives" of the blog posts (same page that is accessible when you click "more news" from the Home page).

After the reorg, the top navbar should read:

Home
Blog
Download
Documentation
Develop
Community
Search

**Comment by garrett** [comment]
That's controlled from https://github.com/oVirt/ovirt-site/blob/master/data/navigation.yml

I'll make a PR with this fixed, even though it's quite a lot of navigation links. :wink:
