### ISSUE TITLE
Document the need for mod_auth_openidc module

### ISSUE THREAD

**Issue by didib** [oVirt/ovirt-site#2834]
With the integration of keycloak, we need, on the engine machine:
```
dnf module enable -y mod_auth_openidc:2.3
```

Not sure about RHV, perhaps it should be conditional.
As a first approximation for the list of locations that need to be changed, you can search for 'pki-deps'.

**Comment by arso** [comment]
Yes, for RHV this should be fully optional.

**Comment by arso** [comment]
there is another dependency ovirt-engine-extensions-misc but this one is 'required' by ovirt-engine-keycloak so it effectively gets installed. IMO there is no need to mention it in the docs.

**Comment by sandrobonazzola** [comment]
@didib @arso, can we close this as fixed by PR #2835 ?
