### ISSUE TITLE
Upgrade guide is not correctly oVirt branded

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2837]
#### Type of problem?
Documentation issue

Upgrade guide is not correctly oVirt branded, see as example:

![image](https://user-images.githubusercontent.com/937860/162233928-e5e3b55d-3e3c-4459-9f2f-88f163b759b8.png)

Link: https://ovirt.org/documentation/upgrade_guide/#Red_Hat_Virtualization_Upgrade_Overview

**Comment by emarcusRH** [comment]
Opened PR2840 to fix this

**Comment by emarcusRH** [comment]
fixed, published
