### ISSUE TITLE
'About' link is dead (from main page)

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#287]
Leads to http://www.ovirt.org/about/#about which is not found.

**Comment by garrett** [comment]
To fix this, someone working on content would need to one of the following:

1. make the content for an about page
2. move http://www.ovirt.org/documentation/introduction/about-ovirt/ to /about/ (and polish up that page)
3. change the footer link to point to /documentation/introduction/about-ovirt/ (and polish up that page)

(I've listed the options in the order of preference.)

So, someone who could make this decision: what should be done?

**Comment by garrett** [comment]
Closing as duplicate of #152
