### ISSUE TITLE
Issue: /develop/networking/infiniband.html

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#2972]
#### Type of problem?
404

At https://ovirt.org/develop/networking/infiniband.html

Within:
> [Cannot read more than 812 bytes from NFS server file](https://bugzilla.redhat.com/show_bug.cgi?id=1046011): The bug can occur between kernels 3.7 and 3.13. It should be fixed with [this commit](http://article.gmane.org/gmane.linux.nfs/60953)

there's a link to http://article.gmane.org/gmane.linux.nfs/60953 but gmane.org is no longer available.

**Comment by sandrobonazzola** [comment]
@bennyz @nirs @ahadas can you help with this?

**Comment by nirs** [comment]
I looked here but this page was not archived:
https://web.archive.org/web/*/http://article.gmane.org/gmane.linux.nfs/60953

Since this is an issue for very old kernels (3.7 - 3.13) I think we can safely delete
this content.
