### ISSUE TITLE
ovirt-doc team can no longer merge PRs without outside reviewer

### ISSUE THREAD

**Issue by apinnick** [oVirt/ovirt-site#3064]
The Ovirt-doc team used to be able to merge PRs without an outside reviewer. This is necessary in order forthe writers to do quick fixes such as typos, updating RN, or to publish urgent documents. Ovirt-doc used to have this ability. However, the feature seems to have been removed recently.

**Comment by sandrobonazzola** [comment]
checking

**Comment by sandrobonazzola** [comment]
According to GitHub config the doc team should be able to bypass the review requirements on the PRs:
![Schermata da 2022-09-15 12-06-22](https://user-images.githubusercontent.com/937860/190377191-1da4e486-a206-4cc0-a70c-46fc07411dfa.png)

@apinnick can you please provide an example of PR where the doc team can't merge?

**Comment by apinnick** [comment]
I don't mean that the doc team can't merge a PR. I mean that the person who **created** the PR can't merge it. I will try to create a PR to show you.

**Comment by sandrobonazzola** [comment]
You should have something like:
![Schermata da 2022-09-15 12-12-40](https://user-images.githubusercontent.com/937860/190378364-9a044403-e46b-4a31-9441-bb7ad5bb06bf.png)

**Comment by sandrobonazzola** [comment]
Just check the checkbox and you should be able to merge your own PRs bypassing the review requriement.

**Comment by apinnick** [comment]
I know that is how it is **supposed** to work. I have used it in the past. Recently I could not do that. I'm checking it now with a PR.

**Comment by apinnick** [comment]
This is what appears. There is no option to merge without waiting for requirements to be met. [PR](https://github.com/oVirt/ovirt-site/pull/3066) 
![image](https://user-images.githubusercontent.com/31725355/190382741-50682bd1-248e-497b-a4b4-6220c695eddb.png)

**Comment by apinnick** [comment]
@janosdebugs This is not a one-off problem. I noticed it a couple weeks ago when I had a PR for the REST API.

**Comment by apinnick** [comment]
I noticed that Eli's [PR](https://github.com/oVirt/ovirt-site/pull/2987) was also stuck in this state.  I submitted a 'test' review and it allowed me to merge. So the end result is the same -- no reviewer, no merge.

**Comment by sandrobonazzola** [comment]
I'l try adding doc team members one by one instead of adding the group.

**Comment by emarcusRH** [comment]
this behavior seems to have popped up recently - sometime around the beginning of September. All of my PRs in the last 2 weeks have been behaving like this - no option to merge without an additional reviewer - and even approval by authorized Dev reviewers, like Yedidyah, did not open the PR for merging.

**Comment by sandrobonazzola** [comment]
check now

**Comment by apinnick** [comment]
> check now

I see no changes in my PR. I'll try pushing a change to rerun the checks.

**Comment by sandrobonazzola** [comment]
@michalskrivanek any change done in global config over the past few weeks?

**Comment by michalskrivanek** [comment]
no, nothing I'm aware of

**Comment by michalskrivanek** [comment]
i do not see a history, but currently the project is set up so that it requires one review

**Comment by apinnick** [comment]
> i do not see a history, but currently the project is set up so that it requires one review

The ovirt-doc team is supposed to be an exception, so that we can do quick fixes that do not require review.

**Comment by apinnick** [comment]
> check now

No change. My PR still requires a reviewer.

**Comment by apinnick** [comment]
> @apinnick I just checked and this seems to be a change on GitHub's side and we can't really do anything about it apart from removing the review requirements completely.

Unfortunate..... Thanks for checking.

**Comment by michalskrivanek** [comment]
I've got similar report from other repos, there as no config change and AFAICT from settings these people (https://github.com/orgs/oVirt/teams/ovirt-documentation/members) can merge without reviews.
Looks like yet another github outage/bug...
