### ISSUE TITLE
Install guide needs an update for oVirt Engine on EL9

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#3098]
#### Type of problem?
Documentation issue

Installation guide at https://ovirt.org/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.html#Installing_RHEL_for_RHVM_SM_localDB_deploy says:

> The oVirt Engine must run on Enterprise Linux 8. For detailed installation instructions, see ...

This is not true anymore, oVirt Engine can now run on Enterprise Linux 9 as well.

**Comment by sandrobonazzola** [comment]
@emarcusRH , @apinnick any suggestion on how to phrase the change?
CC @mwperina

**Comment by apinnick** [comment]
In theory, the version should be described in only one section, [Operating system requirements](https://ovirt.org/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.html#operating-system-requirements_SM_localDB_deploy). 

The other parts of the doc should not specify a specific version.

**Comment by sandrobonazzola** [comment]
> In theory, the version should be described in only one section, [Operating system requirements](https://ovirt.org/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.html#operating-system-requirements_SM_localDB_deploy).
> 
> The other parts of the doc should not specify a specific version.

This section needs update as well as it requires EL 8.6 but oVirt 4.5.4 is now requiring EL 8.7 as minimum while RHV requires 8.6 EUS.

**Comment by apinnick** [comment]
> > In theory, the version should be described in only one section, [Operating system requirements](https://ovirt.org/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.html#operating-system-requirements_SM_localDB_deploy).
> > The other parts of the doc should not specify a specific version.
> 
> This section needs update as well as it requires EL 8.6 but oVirt 4.5.4 is now requiring EL 8.7 as minimum while RHV requires 8.6 EUS.

I created a supported RHEL version attribute. It looks like I will need to create min/max supported version attributes.

**Comment by sandrobonazzola** [comment]
> I created a supported RHEL version attribute. It looks like I will need to create min/max supported version attributes.

can't attribute contain a string? If it can I would use "8.6" for RHV and "8.7 or newer" for oVirt

**Comment by apinnick** [comment]
> > I created a supported RHEL version attribute. It looks like I will need to create min/max supported version attributes.
> 
> can't attribute contain a string? If it can I would use "8.6" for RHV and "8.7 or newer" for oVirt

Absolutely! I will update the PR.
