### ISSUE TITLE
Forum menu link is broken on home page

### ISSUE THREAD

**Issue by ghost** [oVirt/ovirt-site#3158]
### Description of the problem

main page (https://ovirt.org) menu item "Forum" navigates to https://lists.ovirt.org/archives/, which throws an HTTP 500 error

#### Type of problem?
something else

Enter details ...
dead link

**Comment by duck-rh** [comment]
Quack,

Sorry, memcached was down and that broken the UI. The list was still working fine though. It's fixed now.

Regards.
\\_o<
