### ISSUE TITLE
Issue: /dropped/admin-guide/virt/console-client-resources.html

### ISSUE THREAD

**Issue by J-C-P** [oVirt/ovirt-site#3159]
### Description of the problem
Link is not working.

#### Type of problem?
Content issue
The link to http://virt-manager.org/download/ is broken. The last character is not needed.
Replace
http://virt-manager.org/download/ by
http://virt-manager.org/download 
and solve the issue.

**Comment by sandrobonazzola** [comment]
Fixed by @gocallag via #3173
