### ISSUE TITLE
Ovirt Mirror/Resources is Down !?

### ISSUE THREAD

**Issue by akashsemil** [oVirt/ovirt-site#3165]
Ovirt Mirror is down: https://mirrorlist.ovirt.org/
Ovirt Resources is down: https://resources.ovirt.org/

Mirror shows the default Apache Webpage!

![image](https://github.com/oVirt/ovirt-site/assets/53996344/5cd9a4b8-309b-4b7c-ad1a-dc6eb46f87fd)

Resources don't even respond.

**Comment by sipani909** [comment]
I am seeing the same for the last 48 hours. Unable to download any packages. Is someone looking at this?

**Comment by michalskrivanek** [comment]
resources.ovirt.org works for me.
@merlyel can you please take a look at mirrorlist?

**Comment by akashsemil** [comment]
Seems like resources is back now and mirrorlist is still down.
I have been looking into these URL couple of days and they are kind of fluctuating

**Comment by duck-rh** [comment]
Quack,

resources works for me now.

mirrorlist works too, you're just not supposed to use it this way.
When DNF uses this feature it constructs a specific URL, for example `https://mirrorlist.ovirt.org/mirrorlist?dist=9-stream`.
which then gives you a list of URLs for the different mirrors.
We could redirect the main page but since it's not meant for users and there's no default $dist that would satisfy everyone, that would not be very useful.

@merlyel is there any network problem on the hosting side? The host's uptime is fine but it could be a network problem.

\\_o<

**Comment by TheQueasle** [comment]
It seems that both the mirror list and the resources urls are down again.

I’ve tried from a couple locations with the same results.

Seems like the problems are intermittent because last week I was able to hit at least the resources url.

**Comment by duck-rh** [comment]
Quack folks,

I was able to check and experience the problem and that helped a lot debug. Thanks @TheQueasle for pinging us.

It happens that the machine itself is working fine but the local DNS servers are mostly timeouting. I'm trying to get to the right person to get this fixed asap.

Regards
\\_o<

**Comment by gocallag** [comment]
This seems to be working to me:
$ curl https://mirrorlist.ovirt.org/mirrorlist?dist=9-stream
https://resources.ovirt.org/pub/ovirt-@VERSION@/rpm/@DIST@/
http://mirrors.ibiblio.org/ovirt/ovirt-@VERSION@/rpm/@DIST@/
http://ftp.plusline.net/ovirt/ovirt-@VERSION@/rpm/@DIST@/
http://mirrors.rit.edu/ovirt/ovirt-@VERSION@/rpm/@DIST@/
http://mirror.slu.cz/ovirt/ovirt-@VERSION@/rpm/@DIST@/
http://ftp.nluug.nl/os/Linux/virtual/ovirt/ovirt-@VERSION@/rpm/@DIST@/
http://ovirt.repo.nfrance.com/ovirt-@VERSION@/rpm/@DIST@/
http://mirror.rackspace.com/ovirt/ovirt-@VERSION@/rpm/@DIST@/
http://ftp.snt.utwente.nl/pub/software/ovirt/ovirt-@VERSION@/rpm/@DIST@/
http://ovirt.mirror.garr.it/ovirt-@VERSION@/rpm/@DIST@/
https://mirrors.nju.edu.cn/ovirt/ovirt-@VERSION@/rpm/@DIST@/

and 
https://resources.ovirt.org/ is returning the folders 

I'd say this is fixed and can be closed?

**Comment by sandrobonazzola** [comment]
closing as per @gocallag comment
