### ISSUE TITLE
Clean install of oVirt 4.4 on Rocky Linux 8.9: manager not working, grafana is.

### ISSUE THREAD

**Issue by NWMrTim** [oVirt/ovirt-site#3174]
Thank you in advance for any help you can provide!

### Description of the problem
When following the documentation for installing oVirt standalone manager on Enterprise Linux 
https://www.ovirt.org/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases

specifically "RedHat derivitives" - specific to Rocky Linux
https://www.ovirt.org/download/install_on_rhel.html

I have found I get through installing and running "engine-setup" successfully without errors.   The manager web site errors on "500 internal server error" but the Grafana site works without a problem

#### Type of problem
Documentation issue | Installation Process issue | Configuration issue..?
I followed the steps to the best of my ability.  I'm working with slightly older hardware so therefore I am sticking to el8 based, but the latest version of.  Rocky Linux 8.9 and oVirt 4.4.10

Here are the specific steps I took:
installed Rocky Linux - minimal install, added server tools
when that boots up I run these commands in this order:
dnf distro-sync --nobest
dnf install https://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm
dnf module -y enable javapackages-tools
dnf module -y enable pki-deps
dnf module -y enable postgresql:12
dnf module -y enable mod_auth_openidc:2.3
dnf module -y enable nodejs:14
dnf install -y https://resources.ovirt.org/pub/ovirt-4.4/rpm/el8/x86_64/ovirt-engine-appliance-4.4-20220308105414.1.el8.x86_64.rpm
dnf install ovirt-engine -y
engine-setup

I found the documentation says to run adding repos first them install release 4.4 RPM but the Java repo errors out, so I install the RPM first.   I could do that last and enable Java afterwards like this:
... everything else...
dnf install https://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm
dnf module -y enable nodejs:14

I have followed the documentation to the best of my ability and it always fails on 500s on trying to launch the manager.

On the same system I can install CentOS 7.9 and oVirt 4.3.10.  It succeeds and works flawlessly.

I seem to be missing one step or one configuration.  Like I was saying the Grafana site comes up fine, but oVirt manager does not.

**Comment by sandrobonazzola** [comment]
oVirt 4.4 is EOL, please reopen if you can reproduce with 4.5/nightly
