### ISSUE TITLE
Installing on RHEL 9.0 or derivatives Specific to RHEL only: package not found

### ISSUE THREAD

**Issue by rednet1** [oVirt/ovirt-site#3180]
Installing on RHEL 9.0 or derivatives
Specific to RHEL only:

rpm -i --justdb --nodeps --force "http://mirror.stream.centos.org/9-stream/BaseOS/$(rpm --eval '%_arch')/os/Packages/centos-stream-release-9.0-12.el9.noarch.rpm"

centos-stream-release-9.0-12.el9.noarch.rpm NOT FOUND

**Comment by crossfiredeluxxe** [comment]
Tested when attempting new migration to ovirt with RHEL 9.4 hosts: and receives same. Attempted with latest steam-release-9 and deployment fails

**Comment by sandrobonazzola** [comment]
Did you check if a newer version is there?
Looking at https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/ I see:

https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/centos-stream-release-9.0-26.el9.noarch.rpm
