### ISSUE TITLE
broken link in 4.0.0 release notes

### ISSUE THREAD

**Issue by didib** [oVirt/ovirt-site#338]
In [1], there is a link with text "Migration Guide", linking at a non-existent page [2]. The source at that point is:

```
[Migration Guide](http://www.ovirt.org/documentation/migration-engine-3.6-to-4.0/)
```

which looks ok to me, no idea why it's changed during site building (or otherwise broken).

[1] http://www.ovirt.org/release/4.0.0/
[2] http://www.ovirt.org/release/4.0.0/documentation/migration-engine-3.6-to-4.0/

**Comment by sandrobonazzola** [comment]
@garrett can you have a look?

**Comment by garrett** [comment]
Remove the dots from the filename. IIRC, it confuses Middleman, as it expects file extensions. 

(Not sure if there's a workaround or other solution, but this would certainly fix it.)

**Comment by sandrobonazzola** [comment]
pr #540 should solve this.
