### ISSUE TITLE
Blog page needs different layout

### ISSUE THREAD

**Issue by thatdocslady** [oVirt/ovirt-site#34]
Currently the Blog page shows a list of sub-pages: http://beta-ovirtweb.rhcloud.com/blog/

Is there a way to make it look more like the case-studies page: http://beta-ovirtweb.rhcloud.com/community/user-stories/user-stories/

*But* only showing one column (not two, like in the case-studies), similar to your standard Tumblr/Wordpress blog layouts?

**Comment by garrett** [comment]
Normally, it would look more like https://www.rdoproject.org/blog/ — I guess the indexer overrides that for some reason (not sure why). I can look into this next week (it may take some time to debug/fix, so it's not half-past-5pm-on-Friday-after-a-long-week material).

**Comment by thatdocslady** [comment]
Yes, that would be great, thank you! We have more time now :)

**Comment by garrett** [comment]
Just like the front page, /blog/ will look better once there's content in the blog post. (And /blog/ will also list multiple blog posts with summaries, with pagination too.)
