### ISSUE TITLE
update QuickStart guide for 4.0

### ISSUE THREAD

**Issue by jekader** [oVirt/ovirt-site#340]
Currently, lots of places in the QuickStart guide have outdated versions of CentOS/Fedora as well as old oVirt releases present:
https://github.com/oVirt/ovirt-site/blob/master/source/documentation/quickstart/quickstart-guide.html.md

This should be updated. I can help with this, but first we need to agree on the supported list of platforms and oVirt versions since that changed a lot in 4.0. Should there be mentions of older OS and oVirt versions? IMHO the QuickStart should focus on the latest release only and add as little confusion as possible.

**Comment by sandrobonazzola** [comment]
Updated. @jekader can you please review again and open new issue if something else needs to be updated there?

**Comment by jekader** [comment]
Sandro, thank you for updating the doc! I see several more things to improve but will try to submit a pull request myself to save you the extra effort.

note to myself:
* release RPM download commands are corrupted across the site since the URL is enclosed in <> for some reason
* Configure oVirt section contains screenshots of old Admin Portal and instructions to browse the tree pane which no longer exists
* List of power management devices is corrupted
* Create Virtual Machines section is missing the High Performance VM type
* there is no mention of Glance images in the guide while it's much easier than getting an ISO domain set up
* we might want to add a section covering non-admin user creation

**Comment by sandrobonazzola** [comment]
Thanks @jekader feel free to add me as reviewer to your PRs.
