### ISSUE TITLE
Warning about multiple sources when running bundle install

### ISSUE THREAD

**Issue by mureinik** [oVirt/ovirt-site#344]
Running `bundle install` issues a warning about multiple sources:

```
amureini@mureinik ~/src/git/ovirt-site [manage-connections *] $ bundle install
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rails-assets.org/..
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rails-assets.org/..
Fetching dependency metadata from https://rubygems.org/..
[snipped]
```

The site eventually launches, so I guess it's not critical, but it's probably worth cleaning up.

**Comment by duck-rh** [comment]
It's not critical even if it would be better to use blocks to be sure we have the version we expect.
As long as you trust a repository, then this repository could publish alternatives for gems already in the others, so the security problem is in the repository choice and not in the Gemfile. An author could decide legitimately to publish at multiple locations. If one is compromised, limiting in blocks would not help much.

**Comment by mureinik** [comment]
@duck-rh makes sense. Should this issue be dismissed then?

**Comment by mureinik** [comment]
Dismissing the issue as per @duck-rh's comment.
