### ISSUE TITLE
broken links to migration guide

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#366]
http://www.ovirt.org/documentation/migration-engine-3.6-to-4.0/ link get broken when seen on website from 4.0.0 and 4.0.1 release notes.

**Comment by bproffitt** [comment]
@garrett I went in to the release notes to fix the links, and the actual code goes to the right link, but renders to the wrong place. What gives?

**Comment by sandrobonazzola** [comment]
I thought to have fixed this with PR #540 but looks like it wasn't enough. On local instance the patch was working fine.

**Comment by sandrobonazzola** [comment]
@garrett any other hint?

**Comment by sandrobonazzola** [comment]
@garrett never mind, fixed using relative URLs.
