### ISSUE TITLE
Documentation home page has duplicate embedded videos

### ISSUE THREAD

**Issue by drtwisted** [oVirt/ovirt-site#387]
Home documentation page http://www.ovirt.org/documentation/ contains two embedded videos: "Installing oVirt on a single machine" and "Creating and migrating VMs". Second video is the same as the first one, though. The correct link should lead to this video (https://www.youtube.com/watch?v=C4gayV6dYK4), I guess.

**Comment by bproffitt** [comment]
Fixed with PR #388 . Thanks, @drtwisted !
