### ISSUE TITLE
Dead links to jenkins on Node page

### ISSUE THREAD

**Issue by er2** [oVirt/ovirt-site#428]
Almost all the links at the bottom of this page are dead: [https://www.ovirt.org/node/#releases](https://www.ovirt.org/node/#releases)

**Comment by mureinik** [comment]
@fabiand @irosenzw  Doesn't PR #430 fix this issue?

**Comment by fabiand** [comment]
Yes, the jobs got renamed, but with PR #430 this is fixed (I just verified).
