### ISSUE TITLE
http://www.ovirt.org/community/get-involved/report-a-bug/ has wrong instruction

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#464]
### Steps to reproduce
1. Go to http://www.ovirt.org/community/get-involved/report-a-bug/
2. Try to open a bug following instructions
3. You end up trying to open a bug on Community instead of on oVirt classification

**Comment by tigert** [comment]
(These are easy to do btw: Just go to the page in question, click on the "Edit this page on github" link on the bottom, and fix the issue. You have a preview tab to verify your Markdown is correct. Once happy, click save and it leads you through making a pull request.

**Comment by mureinik** [comment]
@sandrobonazzola Now that PR #499 is merged (thanks @tigert btw!), can this issue be closed?
