### ISSUE TITLE
Features missing features name on /develop/release-management/features/

### ISSUE THREAD

**Issue by mscherer** [oVirt/ovirt-site#5]
On https://beta-ovirtweb.rhcloud.com/develop/release-management/features/ , there is several page, listed in subpage, who do not have a proper title.

Looking at the HTML code, this is likely the subcategory where we have only 1 directory, like cloud ( since the html code is: 

    <a href='/develop/release-management/features/cloud/'></a>

**Comment by garrett** [comment]
Ah, so the category pages were kind of a quick WIP that listed pages that are in the category, similar to MediaWiki. I guess in the website's context — especially with the feature browser — it sort of renders the feature category redundant. Perhaps it should really be handled differently in this instance?
