### ISSUE TITLE
http://www.ovirt.org/blog/2016/08/up-and-running-with-ovirt-4-0-and-gluster-storage/

### ISSUE THREAD

**Issue by SayBeano** [oVirt/ovirt-site#504]
### Description of the problem

Link for Jason's gdeploy is broken
### Steps to reproduce
1. run `yum install -y https://copr-be.cloud.fedoraproject.org/results/jasonbrooks/gdeploy/epel-7-x86_64/00442697-gdeploy/gdeploy-2.0-0.noarch.rpm`
2. install fails

**Comment by SayBeano** [comment]
Correct link

https://copr-be.cloud.fedoraproject.org/results/jasonbrooks/gdeploy/epel-7-x86_64/00442607-gdeploy/gdeploy-2.0-0.noarch.rpm

**Comment by lgh2** [comment]
I can submit a fix for this issue.

**Comment by mureinik** [comment]
@lgh2 That would be cool - please do!

**Comment by gregsheremeta** [comment]
there is a 4.2 version of this post. other than that, wont-fix
