### ISSUE TITLE
Broken links due to wrong URL rewriting

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#518]
### Description of the problem

http://www.ovirt.org/develop/infra/testing/test-cases/ is rewritten as http://www.ovirt.org/develop/release-management/features/os-support/fedora-24-support/develop/infra/testing/test-cases/

It shouldn't.

### Steps to reproduce

1.Go to http://www.ovirt.org/develop/release-management/features/os-support/fedora-24-support/

2.Try to follow "Test Case" link in Testing section

**Comment by sandrobonazzola** [comment]
@garrett  any hint on hoow to solve?

**Comment by garrett** [comment]
Sorry — I was on vacation for a week and then got sick the week following. (I'm actually still pretty sick, but a good deal better and trying to work through the illness today.)

Why are you using `http://www.ovirt.org` in that link? I bet that's the problem. Remove that, and it will probably work as intended. You should *never* refer to a page with an absolute link that references the resource and hostname, on any site, ever. It's a really bad idea for all sorts of reasons, with the most important being that it breaks testing locally or on alternate servers (such as staging sites, for example).

**Comment by garrett** [comment]
I've submitted a simple patch that removes `http://www.ovirt.org` from the link, and have verified that it works locally.
