### ISSUE TITLE
Features main page seems broken

### ISSUE THREAD

**Issue by mureinik** [oVirt/ovirt-site#520]
### Description of the problem

The "Features" main page (http://ovirt.org/develop/release-management/features/) seems broken. It has links that start at 3.1 and go up to "proposed 3.6 features" (no 4.0 or 4.1 content), and clicking through on those links brings up empty pages.

By inspecting the source of `source/develop/release-management/features/index.html.md` it seems like a remnant from the old wiki.
Can this page be redone to somehow automatically collect the `feature_status` header from the feature pages?
### Steps to reproduce
1. Navigate to http://www.ovirt.org/develop/release-management/features/

**Comment by sandrobonazzola** [comment]
In the old website features were classified by target release. http://ovirt.org/develop/release-management/features/ was imported from the future category page which linked all the release classes.
We need to decide how to classify the features in the new website.

**Comment by mureinik** [comment]
Let's start a thread on the mailing list?

**Comment by sandrobonazzola** [comment]
@mureinik the http://www.ovirt.org/develop/release-management/features/ has been reworked and is now pretty nice, except for an annoying error in the feature layout code which assumes that also the toc page is a feature. @duck-rh and @eldan can you please help getting the annoying error "No feature info available. Please contact Jon Choate or Sandro Bonazzola to fix." and possibly expand the toc by default in this page?

**Comment by eldan** [comment]
I don’t understand the problem.
There is a category in the left that toggle on / off the categories.
What is the problem?
Can u send me a screen shot?
Eldan

**Comment by duck-rh** [comment]
![ovirt_features_annoying_message](https://user-images.githubusercontent.com/19259504/34330765-c68c2a56-e963-11e7-9261-e2c11ee29ac1.png)

**Comment by duck-rh** [comment]
I see 183 pages with such a message. For example: https://www.ovirt.org/develop/release-management/features/virt/ovmf/
It seems legitimate error though and we need to be sure to keep the error messages for them. I guess we could fill another ticket for this.

**Comment by duck-rh** [comment]
Please confirm it's all fixed by #1461 

Also please consider the problem I raised about the 183 other pages (opening another issue in the case).
