### ISSUE TITLE
Privacy policy of the project is inadequate

### ISSUE THREAD

**Issue by mscherer** [oVirt/ovirt-site#55]
Since @thatdocslady  did ask me for a new bug report, let's restart the discussion from #3 here.

So basically, the reuse of the RH privacy policy is inadequate for ovirt.org for several reasons, and i will list just the 2 main ones for now to not overload the issue:

First, it states that RH do not give the information except to partner that signed a confidentiality agreement, law enforcement or in case of merger/acquisition. 

Since we have community members who would have access to various informations, we are already breaching the privacy policy, and I think it should be amended, like did the one of Fedora.

Second point, the part about remarketing is something we are not doing, and there is people who would see that weird, me being the first. 

So I think we should first have a list of our existing practice regarding private informations, then see which one we are supposed to do or not, and the impact. Then once we have this, we can go to Legal see what can be done to fix the policy to make it correspond to what we do, or if we need to stop doing something (example, logwatch on public list).

**Comment by 0xABAB** [comment]
Informations is not a word, just so you know.
