### ISSUE TITLE
Editing documentation using github, should show the page as it would be rendered

### ISSUE THREAD

**Issue by mbghsource** [oVirt/ovirt-site#592]
### Description of the problem
Preview after editing a documentation page doesn't show how it would actually look on the website.
This makes it difficult to make useful contribution to documentation.

### Steps to reproduce

1. Using chrome browser visit https://www.ovirt.org/community/get-involved/wiki-rules-and-etiquette/

2.  Observe the last section at the bottom of the page titled "Using Special:Watchlist". 
Here is screenshot of how it looks
https://drive.google.com/file/d/0B9LV8Sb_qIEUSk9veUd5d2R4X1U/view?usp=sharing

3. Click on the edit on github link at the bottom of the page, and preview without making any edits.
Here is a screenshot of how it looks
https://drive.google.com/file/d/0B9LV8Sb_qIEUYXdBQnVlYVp0eW8/view?usp=sharing

### Help needed from (use @mention to request assistance)
Perhaps I am using the wrong tools, being a beginner.
If there is a preferred way to edit documentation please let me know.
Thank You.

**Comment by mbghsource** [comment]
Perhaps fixing the broken link - "Editing this wiki"  on http://www.ovirt.org/documentation/ with instructions might help guide people like me.

**Comment by garrett** [comment]
That's outdated information (from when the content was in MediaWiki) and should be removed.

(This is related to issue #42.)

**Comment by gregsheremeta** [comment]
the site is edited with PRs to https://github.com/oVirt/ovirt-site
test locally by cloning the repo and running the local middleman server.
