### ISSUE TITLE
Reporting a bug doesn't guide the user

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#61]
In http://beta-ovirtweb.rhcloud.com/documentation/ Reporting a BUG link just point to the oVirt classification bugzilla without saying what to add to the report (like log-collector report, sos report, single log file). It would be better to add a page explaining how to create a useful bug report, with instructions about ovirt teams, projects, components, attachments.

**Comment by garrett** [comment]
This already exists @ http://beta-ovirtweb.rhcloud.com/community/get-involved/report-a-bug/

**Comment by garrett** [comment]
The pull request is pending, but it needs some assistance to correct some of the Bugzilla queries. I don't know what they're supposed to do exactly, and both the old and modified links for a few of them just don't work. I've commented on the ones that are broken.
