### ISSUE TITLE
Quick start guide should not mention only 4.0

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#687]
### Description of the problem
Currently it mentions anything from 3.3 to 3.6 - need to remove all this information and add 4.0 information.

Specifically, the paragraph below needs to be changed:

The oVirt Engine must be configured to receive updates from the oVirt project's software repository, as provided by the ovirt-release package matching your OS distribution:
oVirt 3.3
oVirt 3.4.
oVirt 3.5.
oVirt 3.6.

**Comment by sandrobonazzola** [comment]
Quick Start Guide has been rewritten for 4.2, closing this issue.
