### ISSUE TITLE
ovirt.org leads to redirect loop

### ISSUE THREAD

**Issue by jelkosz** [oVirt/ovirt-site#69]
If trying to reach the page as ovirt.org (without the www.) it leads to redirect loop

**Comment by david-caro** [comment]
This should be solved now, it should redirect to the www once and load the new site, please verify and close if ok

**Comment by david-caro** [comment]
For reference, the change has been done in the linode01.ovirt.org machine

**Comment by jelkosz** [comment]
yes, works now, thanx
