### ISSUE TITLE
Live merge flow diagram

### ISSUE THREAD

**Issue by mureinik** [oVirt/ovirt-site#717]
### Description of the problem
[The Live Merge feature page](http://www.ovirt.org/develop/release-management/features/storage/live-merge/) states that:

> This diagram is a bit out-dated. Please bear with the developers until they can update it. 

We should really update that.

### Help needed from
@alhino

**Comment by mureinik** [comment]
@tnisan I'd really like to clear up my open issues on GitHub. Can someone take a look at this please?

**Comment by tnisan** [comment]
@shenitzky , can you please take over?

**Comment by gregsheremeta** [comment]
Feature pages now have a warning that they may be out of date. Makes this a non-issue in my opinion. Closing.
