### ISSUE TITLE
Feature page: oVirt Scheduler API needs to be updated

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#719]
### Description of the problem
Document URL: http://wiki.ovirt.org/Features/oVirtSchedulerAPI#REST

Section Number and Name: Current Status

Describe the issue: 
It is not clear if the REST api is a new 3.5 feature or the whole oVirtSchedulerAPI is a new 3.5 feature. If the only new part is rest api please split the feature page accordingly.
The feature page doesn't show a target release.
The status of the feature is marked as Status: design  while the feature is marked as completed in  http://goo.gl/4SuYdE and Bug #1108602 is on qa

Suggestions for improvement: 
Please also use feature template: http://www.ovirt.org/Feature_template
Please add test cases to the feature page, can't find them also in http://www.ovirt.org/OVirt_3.5_TestDay. You can use http://www.ovirt.org/QA:TestCase_Hosted_Engine_Tagged_VLAN_Support as template

Moved from https://bugzilla.redhat.com/show_bug.cgi?id=1142846

### Help needed from (use @mention to request assistance)
@mwperina

**Comment by gregsheremeta** [comment]
Feature pages now have a warning that they may be out of date.
