### ISSUE TITLE
Feature page: Support blkio SLA features needs to be updated

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#720]
### Description of the problem
Document URL: http://www.ovirt.org/Features/blkio-support

Section Number and Name: Current status

Describe the issue: 
Status: implementation while the feature is marked as not completed in  http://goo.gl/4SuYdE and Bug #1085049 is on qa
It is not clear if the status is completed or not.

Suggestions for improvement: 
Please also use feature template: http://www.ovirt.org/Feature_template
Please add test cases to the feature page, can't find them also in http://www.ovirt.org/OVirt_3.5_TestDay. You can use http://www.ovirt.org/QA:TestCase_Hosted_Engine_Tagged_VLAN_Support as template

Moved from https://bugzilla.redhat.com/show_bug.cgi?id=1142822

### Help needed from (use @mention to request assistance)
@doron-fediuck

**Comment by gregsheremeta** [comment]
Feature pages now have a warning that they may be out of date.
