### ISSUE TITLE
Feature page: Custom Fencing needs to be updated

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#721]
### Description of the problem
Document URL: http://www.ovirt.org/Custom_Fencing

Describe the issue: the page looks more like an administration guide addendum than a feature page.
Please ensure the page is linked from the oVirt guide and create a feature page for the changes introduced in oVirt 3.5.

Suggestions for improvement: 
Please use feature template: http://www.ovirt.org/Feature_template
Please add test cases to the feature page, can't find them also in http://www.ovirt.org/OVirt_3.5_TestDay. You can use http://www.ovirt.org/QA:TestCase_Hosted_Engine_Tagged_VLAN_Support as template

Moved from https://bugzilla.redhat.com/show_bug.cgi?id=1142665 

### Help needed from (use @mention to request assistance)
@mwperina

**Comment by gregsheremeta** [comment]
Feature pages now have a warning that they may be out of date.
