### ISSUE TITLE
Feature page: PMHealthCheck needs to be updated

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#722]
### Description of the problem
Document URL: http://www.ovirt.org/Features/PMHealthCheck

Section Number and Name: Current status

Describe the issue: 
Current status and target version are not listed in the page.
The page doesn't point to the detailed description which has a different URL: http://www.ovirt.org/Features/Design/DetailedPMHealthCheck
The detailed description says that the feature is targeted to 3.5 but the status is design while the feature is marked as completed in  http://goo.gl/4SuYdE and Bug #1090800 is marked as verified.
Lot of sections have N/A as text.

Suggestions for improvement:
Please consider to merge the 2 feature pages in a single page and delete the other one.
Please also use feature template: http://www.ovirt.org/Feature_template
Please add test cases to the feature page, can't find them also in http://www.ovirt.org/OVirt_3.5_TestDay. You can use http://www.ovirt.org/QA:TestCase_Hosted_Engine_Tagged_VLAN_Support as template 

Moved from https://bugzilla.redhat.com/show_bug.cgi?id=1142662

### Help needed from (use @mention to request assistance)
@mwperina

**Comment by gregsheremeta** [comment]
Feature pages now have a warning that they may be out of date.
