### ISSUE TITLE
Feature page: DetailedHostPMProxyPreferences needs to be updated

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#723]
### Description of the problem
Document URL: http://www.ovirt.org/Features/Design/DetailedHostPMProxyPreferences

Section Number and Name: Current status

Describe the issue: 
 - Target Release: 3.2
 - Status: Design
 - Last updated date: Nov 4 2012 

While the feature is marked as completed for 3.5 in http://goo.gl/4SuYdE and Bug #1054778 is marked as verified.

Suggestions for improvement: 
Please also use feature template: http://www.ovirt.org/Feature_template
If a part of the feature is delayed to a later release please split the feature keeping there only things included in 3.5.0 and create a new one for 3.6 including the missing bits.
Please add test cases to the feature page, can't find them also in http://www.ovirt.org/OVirt_3.5_TestDay. You can use http://www.ovirt.org/QA:TestCase_Hosted_Engine_Tagged_VLAN_Support as template

Moved from https://bugzilla.redhat.com/show_bug.cgi?id=1142652

### Help needed from (use @mention to request assistance)
@mwperina

**Comment by gregsheremeta** [comment]
Feature pages now have a warning that they may be out of date.
