### ISSUE TITLE
Subprojects page needs some styling

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#726]
### Description of the problem
http://www.ovirt.org/subprojects/ is really ugly and difficult to read.
It's outdated, missing several incubation projects and reporting obsolete data.
it's formatted with tables without lines which make it really difficult for reading.

It would  be nice to get fresh information about maintainers directly from gerrit, avoiding data duplication.

**Comment by sandrobonazzola** [comment]
@eldan can you help with this?

**Comment by sandrobonazzola** [comment]
@duck-rh maybe you can help too

**Comment by duck-rh** [comment]
Similarly to what the old dashboard did, I would suggest a script in crontab fetching the necessary information and outputting a YAML file. The page would then read it and format it.

I can help with the Ansible deployment and some review, but I do not have time to code the whole thing.

**Comment by eldan** [comment]
Yes indeed ugly.
Also lots of dead links.
I will create a whole new template for this page.
I think it should be a launching page for each of the groups.
I will also prepare a group page with basic info. Each group will maintenance it's page later on. 
Thought?

**Comment by gregsheremeta** [comment]
> I think this page should be deleted

deleted
