### ISSUE TITLE
New oVirt User Case Study needed - Florida State University

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#741]
### Description of the problem
http://www.ovirt.org/community/user-stories/users-and-providers/ is missing a user story from Florida State University, see ~~https://rcc.fsu.edu/news/rcc-adopts-ovirt-virtualizationac~~
https://rcc.fsu.edu/news/rcc-adopts-ovirt-virtualization

**Comment by bproffitt** [comment]
That link is a 404.

**Comment by rollandf** [comment]
here is the link:
https://rcc.fsu.edu/news/rcc-adopts-ovirt-virtualization

**Comment by doron-fediuck** [comment]
@sandrobonazzola this is very old now. Is there a quick way to update and merge?

**Comment by sandrobonazzola** [comment]
It would be nice to get in touch with Florida State University and get an update from them. I guess situation evolved since this issue was opened.

**Comment by sandrobonazzola** [comment]
This has been added here: http://ovirt.org/community/user-stories/RCC-case-study and referenced in home page at https://ovirt.org/#florida-state-university-rcc
