### ISSUE TITLE
Need to update http://www.ovirt.org/develop/developer-guide/vdsm/hook/hugepages/

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#742]
### Description of the problem
1. There's some data missing there (in what is added to libvirt.XML)
2. I'm not sure it is up-to-date / relevant.

**Comment by sandrobonazzola** [comment]
The hook was removed in oVirt 4.2, specifically within vdsm-4.20.1 with https://gerrit.ovirt.org/#/c/66398/
@michalskrivanek , @ahadas how do you want to proceed?
Drop the page? Keep it for reference but fix it?

**Comment by michalskrivanek** [comment]
4.2 is old enough, we can drop it. it doesn't really provide much historical value either.
