### ISSUE TITLE
Wiki redirects are not working anymore

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#765]
### Description of the problem
Wiki redirects are not working anymore
Quoting from user mailing list: http://lists.ovirt.org/pipermail/users/2017-February/079415.html

links in release notes are broken ( https://www.ovirt.org/release/4.1.0/ )
They are going to https://www.ovirt.org/release/4.1.0/Hosted_Engine_Howto , but docs for 4.1.0 are absent.

**Comment by duck-rh** [comment]
The redirection config says "Hosted Engine Howto" redirects to 'howto/hosted-engine' (in 'source/redirects.yaml'). Unfortunately, this path does not exist.

In commit 67eca9e229 the path 'source/howto' was renamed to 'source/documentation/how-to', so this is the source of your problem. This was in november 2015, so it is quite disturbing it went unnoticed…

So I guess the redirects should be fixed, but I leave the editorial decisions to you.

**Comment by sandrobonazzola** [comment]
Maybe we should get rid of the wiki redirects and just fix the links to match website structure.
Is there a way to add a check in travis to fail if a change add or modify a link or modify a file path breaking linking?

**Comment by duck-rh** [comment]
I wonder why it was done this way instead of rewriting from the start (as the URL most probably differed anyway). I'll give it a look after the Configuration Management Camp.

I think Garrett suggested something similar. I'm not up-to-date on the tools to do that, but I've added it to the todolist.

**Comment by sandrobonazzola** [comment]
Thanks @duck-rh !

**Comment by duck-rh** [comment]
Happily, all ancient wiki-related things were purged in #1071
