### ISSUE TITLE
PDF links return 404

### ISSUE THREAD

**Issue by didib** [oVirt/ovirt-site#77]
Most of the "Slides" links in e.g. [1], e.g. [2], return "page not found".

I can't find any pdf files in the git repo.

Nor can I find how these ":Media:" links are supposed to work, in case I want to fix some of them...

[1] http://www.ovirt.org/community/events/archives/fosdem-2014/
[2] http://www.ovirt.org/community/events/archives/fosdem-2014/:Media:Fosdem-hosted-engine.pdf

**Comment by thatdocslady** [comment]
@garrett - any idea why this is happening?

**Comment by garrett** [comment]
Yep. PDFs are not hosted in the site (nor should they be, really). As the links point to a non-existing URL, the links are broken.

**Comment by garrett** [comment]
I'd suggest hosting content like PDFs in the same place as ISOs and RPMs, if possible.

**Comment by thatdocslady** [comment]
So where were they hosted before the migration? I assume they're still
sitting somewhere, waiting to be linked...

**Comment by didib** [comment]
They were disguised as images. Specifically, in the above case, the link in [1] is to [2].

I see the reasoning in putting them on our files server (resources.ovirt.org), but this will be a high barrier to pass for contributors - and not sure it makes sense from the "content" pov.

What do other middleman sites do?

Is there a technical problem to just push commits adding these files and link to them? Or is it just a matter of policy?

[1] http://old.ovirt.org/FOSDEM_2014
[2] http://old.ovirt.org/images/d/d5/Fosdem-hosted-engine.pdf

**Comment by garrett** [comment]
It's a bit messy to put binary files in git, and a better policy is to host them elsewhere and link them. @mscherer has something implemented for ManageIQ (iirc) for large binary files... but I think that's more for ISOs.

How many are there and how large are they?

Also: I'm pretty sure I didn't see them in the images.

**Comment by mscherer** [comment]
So for manageiq, I have 2 things:
- the iso are uploaded to the rackspace CDN
- the pdf were download and placed on /pdf manually, until we decide on a better process. it seems this didn't happened at all once the issue was fixed with a hack.

And yeah, each big file we had in git is a big file we need to download for a git rebase or clone. A few would be fine, like image, but if we start adding more and more, it will just become a burden, slow down the build and clone and annoy people.

**Comment by sandrobonazzola** [comment]
@mscherer @garrett @thatdocslady ok, so: where should we upload slides and pdf files? How could we upload them?.

**Comment by mscherer** [comment]
So either we upload them "as is" to the gears (but then, we need to make a backup somewhere), or we get a second gears with "static.ovirt.org", or get a VM, or upload to a CDN. There is a ton of option, so the biggest question is:
- who should be allowed to upload, and how do we decide what is uploaded.

Without more informations on the workflow we want for upload, it is hard to design a solution.

**Comment by sandrobonazzola** [comment]
with oldovirt wiki whoever had a wiki account could upload images / slides / pdf.
Is there a solution somewhere for allowing upload after github authentication?

**Comment by doron-fediuck** [comment]
@thatdocslady we really need to solve this as feature pages should have a screenshot of the relevant change in the user interface.
We can open a temporary dropbox account to temporary host images and slides included in a PR.
Once accepted they should be uploaded to a persisted storage by the maintainer.

So the flow is:
1. Contributor push a PR with relevant files uploaded to temporary dropbox. 
2. Maintainer to review a PR. Once it's ready to be merged the maintainer uploads the images to the persisted storage and asks the Contributor to update the image URL.
3. Contributor updates the PR.
4. Maintainer Merges the change.

**Comment by duck-rh** [comment]
Why would we use another third-party and non-free service?

Is httpd + ftpd gears not sufficient? or ftpd + CDN sync ?

**Comment by doron-fediuck** [comment]
For our purposes Dropbox is free. We only need it as a temporary storage
for the review process.
Using httpd is irrelevant since you need a temporary storage which is loosely moderated
so people can upload their files for review. Once accepted (or rejected) the files should be
removed from the temporary storage (we can script it).

**Comment by duck-rh** [comment]
I was speaking about non-Free with "Free as in free speech".

And I talked about FTP for this function, httpd is only if we distribute the moderated assets directly on the same host. And "mv" is clearly much more simple than scripting a web API, even if I'm pretty sure there's many libs for all languages around.

**Comment by mscherer** [comment]
well, I do not think we need to have a specific process for temporary stuff. If people want to use their server, that work fine as well as dropbox. So just say "people give a url to the content before being reviewed" and that should be sufficient.

The real problem is how to push things to openshift, how to do backup, audit access, etc.

**Comment by duck-rh** [comment]
Why not. In this case people can just pop on the ML and give an URL hosted anywhere. So there is track of it and people can comment before it is pushed to the real location.

On the OpenShift side, the httpd/etc/conf.d/ directory seems customizable, so we could have a specific out-of-openshift operations directory we could sync, and alias it in the Apache configuration.

As for the storage, I don't know the infra well yet, but seems there is a lot of assets on resources.ovirt.org, so why not use the same system? I don't know how people push things in, SCP?

Are these assets already backed-up on backup.phx.ovirt.org? If not I guess it should.

**Comment by didib** [comment]
I now downloaded all the static ('File:' or 'Media:') files from the old site, and they are 90MB in size.

I think it will be ok to just add them to the git repo.

Another option is to maintain them in a separate git repo, say oVirt/ovirt-site-static, or ovirt-site-files etc. I'd hope for such a system to be semi-automatic, with the actual URLs part of the configuration of the site and not hard-coded in each link.

**Comment by doron-fediuck** [comment]
We still need a temporary storage for the review phase. 
So far I didn't see any concrete suggestion to this need.

**Comment by didib** [comment]
The temporary storage is just like for any text change - a branch in the clone the user did.

**Comment by doron-fediuck** [comment]
We cannot rely on github for large files support, and the general limitation is around 1GB for a repo.
See: 
https://github.com/blog/1533-new-file-size-limits
https://help.github.com/articles/what-is-my-disk-quota/

Hence we need to separate the storage for images / videos / etc to resources.ovirt.org or similar.
And yes, we still need a temporary storage for the review phase.

**Comment by didib** [comment]
I'd say that if in 4.5 years we needed 90MB, 1GB will be ok for some time to go.
We should ask people to keep their files small when reviewing pull requests.
Videos can imo be put on youtube or some such. Also, I currently mainly care about the existing files. New files might be discussed separately.

**Comment by doron-fediuck** [comment]
The point is that source control (and git and github) are not meant for binary files.
So let's do this the right way instead of forcing people to clone a huge repo for no good reason.

**Comment by duck-rh** [comment]
I agree with Garrett and doron-fediuck this is not a good place.

Garrett talked about the ISO place, and I asked about resources.ovirt.org (which may be the same place), but nobody replied on this.

Should we raise a more wide discussion on the ML?

**Comment by didib** [comment]
Do we want a single place/process for both past (old site) binary files and future ones?

If not, we can copy them once to resources.ovirt.org and then fix the links here. And then think about future ones, if/when there is enough pressure for this (which I admit I currently do not feel).

**Comment by didib** [comment]
Now uploaded them to [1]. Didn't publish yet anywhere, so can move/rename if we want, e.g.:

/website-files
    /old-site
    /2016
Or whatever other scheme we can think of.

These files are a result of running this:

for tag in File Media; do cat ./* | sed -n "s/.*\[\[:*${tag}: *\([a-zA-Z_0-9 ().-]*\).*\]\].*/\1/p"; done | sed 's;^;http://old.ovirt.org/File:;' > /tmp/file-urls

wget -i /tmp/file-urls

for f in *; do sed -n 's;.*>current<.*href="\(/images/[^"]*\)".*;http://old.ovirt.org/\1;p' < $f; done | sort -u > /tmp/urls

wget -i /tmp/urls

A quick glance shows that this includes also some files that _were_ migrated, including images - some of them even converted (or at least renamed) from jpg to png. So properly creating a patch probably requires patching only those that are still missing now.

[1] http://resources.ovirt.org/old-site-files/

**Comment by mmirecki** [comment]
Could we have the files on resources.ovirt.org and just have a list of link here?

**Comment by sandrobonazzola** [comment]
Is this still an issue?

**Comment by didib** [comment]
Seems like it was solved by #650 for existing links, and apparently we collectively gave up on an organized solution for new content.

**Comment by sandrobonazzola** [comment]
Thanks @didib , closing this issue. On the organized solution for new content let's discuss it on a new issue.
