### ISSUE TITLE
Add anchors to titles

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#775]
### Description of the problem
Currently titles within the pages on the website are missing anchors.
Please add them. Looks like it shouldn't be difficult:
http://blog.davydovanton.com/2016/05/14/middleman-add-title-anchors/

**Comment by duck-rh** [comment]
I totally agree this would be nice to have.

As for the implementation, I did not test it yet, but I can already say the permalink generation is far too simplistic. Currently if you reorder or insert chapters, then your link would not go where you expect it to go… it should be generated in relation to the title; maybe we could patch this ourselves.

**Comment by duck-rh** [comment]
Why reopening? Any problem with the feature?

**Comment by JohnMarksRH** [comment]
@sandrobonazzola @duck-rh 
I have reservations about this feature, mainly from a UX perspective. I think we should check with a UI expert and get his feedback.

**Comment by duck-rh** [comment]
Ok, so what are you reservations then?

As for the feature itself, it is very common on various website.

It is implemented in the less obstructive way I found. Also I'm using only jQuery which is already in use, and there is no additional dependency.

**Comment by JohnMarksRH** [comment]
@duck-rh can you share some examples of product websites that use this feature?

**Comment by duck-rh** [comment]
Some examples:

- all readthedocs documents, like http://treeherder.readthedocs.io/testcases.html
- official Python doc, like https://docs.python.org/3/howto/curses.html
- the trac ticketing system, like https://trac.edgewall.org/

You still did not explain your concerns; it would help address them if you did.

**Comment by rollandf** [comment]
Hi @duck-rh ,
I think this feature is much needed, but may need some tuning.
In all the sites you mentioned, I noticed that:
- The anchor links are not visible until the mouse go over it
- The anchor links are positioned on the right side of the titles.

IMHO, seeing the anchor links all the time is distracting.

What do you think ?

**Comment by duck-rh** [comment]
@rollandf I agree.

I had a look into the result and found out it did not match what I tested with the live server. This is due to the CSS not being loaded when the site is built (but the CSS file is found when using the live server). I'm preparing a patch for this.

Changing sides seems also better, I will prepare a patch for this too.

**Comment by JohnMarksRH** [comment]
@duck-rh thanks for examples @rollandf Fred - my thoughts exactly (visibility and positioning)

**Comment by duck-rh** [comment]
ok, fine. So please review the linked PRs above which should address your concerns.

**Comment by rollandf** [comment]
@duck-rh Looks great !! I think we can close this issue.

**Comment by duck-rh** [comment]
@JohnMarksRH are you ok with the fixes?

**Comment by JohnMarksRH** [comment]
@duck-rh @rollandf LGTM Thanks
