### ISSUE TITLE
Case studies links are broken

### ISSUE THREAD

**Issue by rollandf** [oVirt/ovirt-site#795]
Most of the case studies links are broken.
https://www.ovirt.org/community/user-stories/users-and-providers/

For example :
Go to :
https://www.ovirt.org/community/user-stories/users-and-providers/
Under 'Brussels Airport'
Click 'case study'

Same for other sections under this page.

**Comment by bproffitt** [comment]
Fixed with PR #796

**Comment by rollandf** [comment]
Thanks !!
