### ISSUE TITLE
RHV procedures are listed in oVirt documentation

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#819]
### Description of the problem
RHV procedures are listed in oVirt documentation.
One example is "# subscription-manager repos --enable=rhel-7-server-rhv-4-mgmt-agent-rpms" suggested in http://www.ovirt.org/documentation/self-hosted/chap-Maintenance_and_Upgrading_Resources/ 

We need to do a review of the documentation ensuring it's consistent with oVirt workflow.

**Comment by sandrobonazzola** [comment]
cc @dyaniv

**Comment by bproffitt** [comment]
@sandrobonazzola Ah, I thought I caught all of these. I must have missed some. Will review.

**Comment by sandrobonazzola** [comment]
Fixed with #823
