### ISSUE TITLE
[URGENT] Website is not updating pages

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#833]
### Description of the problem
I updated 4.1.1 release notes last week with pull request #832 but the website still shows previous version

**Comment by garrett** [comment]
This appears to be a build and/or deploy issue, especially since only a markdown doc was changed. Please contact @duck-rh and/or @mscherer.

Meanwhile, I'll building this locally just to double check.

**Comment by garrett** [comment]
BTW: Also, it does check out fine in CI (which does a clean build), so that's a strong sign it's a deploy issue.

Also, I checked to make sure master builds; it does. I'm working on merging the change and will build again with the PR changes. (I expect it will, as CI works, so this is most likely a bit redundant.)

**Comment by mscherer** [comment]
So, it seems the VM building things is paused, for some reason.

Usually, that mean that the disk is full, or someone did on purpose.

**Comment by mscherer** [comment]
I restarted the VM, let's see how it go.

**Comment by mscherer** [comment]
So we have 2 Vm for that, 1 on os1 (that was shutdown), 1 on osas infra, who was paused.

I restarted the external one, since we should get out of os1.

**Comment by mscherer** [comment]
So after discussing with Duck on irc, I stopped the external one, and restarted the internal one. We however still need to move them out of os1.

**Comment by duck-rh** [comment]
It's not ready yet but WIP and well in sight in the todolist.

**Comment by sandrobonazzola** [comment]
@duck-rh @mscherer @garrett looks like it's working now, do you need this ticket kept open or can we close this?

**Comment by mscherer** [comment]
We can close, IMHO, since this is working.

**Comment by sandrobonazzola** [comment]
Closing as per @mscherer comment.
