### ISSUE TITLE
Links are all FUBAR'd? e.g: Guest Agent page

### ISSUE THREAD

**Issue by otheus** [oVirt/ovirt-site#853]
### Description of the problem

Many or all of the links on the page "/documentation/internal/guest-agent/understanding-guest-agents-and-other-tools/" are broken.  I wanted to fix this with a fork, but realized that so many are broken, it can only be considered a design error.

### Steps to reproduce

1. Go to http://www.ovirt.org/documentation/internal/guest-agent/understanding-guest-agents-and-other-tools/ 

2.  Click on a link

**Comment by bproffitt** [comment]
Merged #854
