### ISSUE TITLE
Broken Image Links in oVirt Quick Start Guide

### ISSUE THREAD

**Issue by leni1** [oVirt/ovirt-site#879]
### Description of the problem
The images in the oVirt Quick Start Guide do not display when the page is loaded. Instead the alternative text for the images appears and right-clicking on the text produced a 'Not Found' error. 

### Steps to reproduce

1. Open a web browser

2. Go to [www.ovirt.org](http://www.ovirt.org/)

3. Click on [**Documentation**](http://www.ovirt.org/documentation/)

4. Under **Primary Documentation**, click on [**Quick Start Guide**](http://www.ovirt.org/documentation/quickstart/quickstart-guide/)

5. Page loads without images accompanying the instructions. The alternate text e.g. "Figure 1. Administration Portal Features" in the section **Connect to oVirt Engine** appears instead.

**Comment by rollandf** [comment]
Fixed in PR #880
