### ISSUE TITLE
Broken links in release notes

### ISSUE THREAD

**Issue by alhino** [oVirt/ovirt-site#884]
### Description of the problem
Following links are broken in the release notes:
- Hosted_Engine_Howto#Upgrade_Hosted_Engine (broken link is: https://www.ovirt.org/release/4.1.0/Hosted_Engine_Howto#Upgrade_Hosted_Engine)
- Hosted_Engine_Howto#Fresh_Install  (broken link is: https://www.ovirt.org/release/4.1.0/Hosted_Engine_Howto#Fresh_Install)

### Steps to reproduce
Click on each link

### Help needed from (use @mention to request assistance)
@JohnMarksRH 
@bproffitt 
@mykaul

**Comment by gregsheremeta** [comment]
outdated
