### ISSUE TITLE
Wrong link in 4.1 release notes

### ISSUE THREAD

**Issue by alhino** [oVirt/ovirt-site#885]
### Description of the problem
Link to Self Hosted Engine Guide points to customer portal guide - https://access.redhat.com/documentation/en/red-hat-virtualization/4.0/paged/self-hosted-engine-guide/

Should point to the corresponding oVirt guide.

### Steps to reproduce
Click the link

### Help needed from (use @mention to request assistance)
@JohnMarksRH 
@bproffitt 
@mykaul

**Comment by sandrobonazzola** [comment]
Fixed in #1256
