### ISSUE TITLE
Add table of content to release notes

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#898]
### Description of the problem
In the old wiki we had a table of content on top of the release notes page to easily move between sections.
It would be nice to have it as well with the new website.

### Help needed from (use @mention to request assistance)
@garrett , @bproffitt

**Comment by bproffitt** [comment]
We would need to create a static template that can be edited each time you update the release notes. There is no good way that I am aware of to do this automatically in static files.

**Comment by sandrobonazzola** [comment]
Closing this issue, since now we have TOC in release notes.
The solution was adding:
  layout: toc
in the header.
