### ISSUE TITLE
./run-server.sh fails (on F25)

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#904]
### Description of the problem
./setup.sh succeeded.
Freshening oVirt dashboard data: 100% ##########################################################################################################################################################################

bundler: failed to load command: middleman (/usr/local/bin/middleman)
LoadError: libruby.so.2.2: cannot open shared object file: No such file or directory - /usr/local/lib64/gems/ruby/nokogiri-1.6.6.2/nokogiri/nokogiri.so
  /usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:29:in `require'
  /usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:29:in `rescue in <top (required)>'
  /usr/local/share/gems/gems/nokogiri-1.6.6.2/lib/nokogiri.rb:25:in `<top (required)>'
  /usr/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
  /usr/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
  /usr/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
  /usr/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
  /usr/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
  /usr/share/gems/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
  /usr/share/gems/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
  /usr/local/share/gems/gems/middleman-core-3.3.10/lib/middleman-core/load_paths.rb:37:in `setup_load_paths'
  /usr/local/share/gems/gems/middleman-core-3.3.10/bin/middleman:10:in `<top (required)>'
  /usr/local/bin/middleman:23:in `load'
  /usr/local/bin/middleman:23:in `<top (required)>'
[ykaul@ykaul ovirt-site]$ 

[ykaul@ykaul ovirt-site]$ bundle show |grep nok
  * nokogiri (1.6.6.2)

Manually updated nokogiri (via 'bundle update nokogir'), but there was another issue with 'oj'.
Manually updated oj, but there was another issue with 'therubyracer'
Manually update therubyracer, but there was another issue with 'curb'. 

Surely our Ruby gem deps are not up-to-date, inaccurate, not fit for F25?

Or setup.sh is not installing the gems?

Updated all gems in my system, it failed on ruby_http_parser missing.

installed it, it still fails:
bundler: failed to load command: middleman (/usr/local/bin/middleman)
LoadError: libruby.so.2.2: cannot open shared object file: No such file or directory - /usr/local/lib64/gems/ruby/http_parser.rb-0.6.0/ruby_http_parser.so
  /usr/local/share/gems/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `require'
  /usr/local/share/gems/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `<top (required)>'
  /usr/local/share/gems/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `require'
  /usr/local/share/gems/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `<top (required)>'
  /usr/local/share/gems/gems/em-websocket-0.5.1/lib/em-websocket/handshake.rb:1:in `require'

[ykaul@ykaul http_parser.rb-0.6.0]$ file /usr/local/lib64/gems/ruby/http_parser.rb-0.6.0/ruby_http_parser.so
/usr/local/lib64/gems/ruby/http_parser.rb-0.6.0/ruby_http_parser.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b1fa1b164e2794a8c5d875bf15dc7aa9840140a2, not stripped

**Comment by mykaul** [comment]
@duck-rh - trying to run the middleman server fails for me. Any idea? I've tried to clone from scratch again, but who knows, perhaps my system is a bit dirty already?

**Comment by duck-rh** [comment]
So, first, we use a Gemfile.lock with versions which are tested to work together, so yes indeed it is not particularly fresh because the goal is to have it stable unless we need some feature or fix.

setup.sh is doing a bundle install so it seem ok to me.

I'm using the same nokogiri version here.

I just purged _vendor/_ and reinstalled without any problem. I'm on Debian unstable so I would need to retest it on a F25 system.

What puzzles me in your traces is the path _/usr/local/share/gems_. This should not happen if you're running the setup as a non-root user. I see _ykaul@_ so it should install in _vendor/bundle/_ (only the yum/apt part of _setup.sh_ is run with sudo). So maybe you installed gems globally as root before. Could you check and maybe remove (or reinstall it if you need it)?

**Comment by mykaul** [comment]
Cleaned my whole system from all gems, reinstalled, now it works. Closing.
