### ISSUE TITLE
http://www.ovirt.org/develop/dev-process/working-with-gerrit/ is a mess

### ISSUE THREAD

**Issue by mykaul** [oVirt/ovirt-site#91]
Something in the move did not go well. It is unreadable and is a very important page.

**Comment by mureinik** [comment]
@mykaul seems like the angular brackets in <username>.id.fedoraproject.org were not correctly escaped, which broke the md to html conversion.
See proposed patch.

**Comment by sandrobonazzola** [comment]
Thanks Allon, can you verify it's ok so we can close the issue?

**Comment by mureinik** [comment]
The merged fix indeed handles the brunt of the issue, but upon further inspection, it seems to have been a partial solution.

The new PR (with patch 	2522ea0) should solve the remaining issues.

**Comment by mureinik** [comment]
Both PRs are merged now, and the page looks fine. How can I close this issue?
(@mykaul - should you do this? )

**Comment by mykaul** [comment]
Closing, thanks!
