### ISSUE TITLE
Documentation > Release Notes Housekeeping

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#920]
Some housekeeping is required for the links under Documentation > Release Notes
http://www.ovirt.org/documentation/#release-notes

### What needs to be done?
- Remove links to all versions no longer relevant to users
- Add links to version 4.1.1, 4.0.0 (if relevant)

**Comment by mykaul** [comment]
We already have 4.0.6 there, I believe we should add latest 4.1.1.

**Comment by JohnMarksRH** [comment]
@mykaul @sandrobonazzola add 4.1.1. OK. What can we delete?

**Comment by sandrobonazzola** [comment]
The documentation page only links current stable release and previous one, pointing the user to separate list for searching older releases. Closing fixed.
