### ISSUE TITLE
developer documentation > Outdated roadmaps

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#927]
### Description of the problem
- The links are to old roadmaps. Can we delete them all?
http://www.ovirt.org/develop/#developer-documentation

- Is there a relevant roadmap that we can publish?

Help needed from @mykaul @sandrobonazzola

**Comment by sandrobonazzola** [comment]
I think old roadmaps have been already removed, can't see them.
Latest plans are available on http://www.ovirt.org/develop/release-management/releases/4.1.z/release-management/ as soon as the website will be updated with github content.

**Comment by JohnMarksRH** [comment]
@sandrobonazzola @mykaul Yes removed. There was a separate PR about it 
https://github.com/oVirt/ovirt-site/pull/928
Regarding 4.1.z, these are also past dates. Is it relevant to anyone?

**Comment by sandrobonazzola** [comment]
I'd keep them for record but I've no strong feelings on this.

**Comment by sandrobonazzola** [comment]
Any final decision on keeping 4.1.z roadmaps or deleting them?

**Comment by sandrobonazzola** [comment]
Closing this issue, keeping 4.1.z roadmaps for record
