### ISSUE TITLE
Release Management page - outdated 

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#938]
### Description
I would like to propose some changes to the release management page:
http://www.ovirt.org/develop/release-management/releases/

1. Remove all links to old releases, keeping just 4.1.Z
2. For simplicity, remove links to release notes. There are clear links to the release notes on the documentation page
3. Change the main link text >> [Release management](http://www.ovirt.org/develop/release-management/releases/) to >> [Release timeline](http://www.ovirt.org/develop/release-management/releases/) or/ [Release schedule](http://www.ovirt.org/develop/release-management/releases/). 

### Input would be appreciated from @sandrobonazzola @mykaul

**Comment by sandrobonazzola** [comment]
http://www.ovirt.org/develop/release-management/releases/ currenlty shows only:

# Releases
All information about oVirt releases

**Comment by sandrobonazzola** [comment]
closing this as the initial reported issue is not there anymore.
