### ISSUE TITLE
Documentation Tab Restructure Proposal

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#939]
### Description of the problem
In a bid to make the content under the [oVIrt Documentation](https://www.ovirt.org/documentation/) tab more user-friendly and easier to navigate, I propose to remove a lot of duplicated links / content and make some changes to its structure.

Proposals:
- **Developer Documentation** Remove it from this page. All this content exists under Developer tab
- **Community Documentation**: Remove it from this page. Here is what will happen to links:
1. Guidelines for community activity - Remove. Content exists under Community tab page
2. Communicating via Mailing lists and IRC - Remove. Links exist under community tab
3. Reporting a Bug - Remove. Links exist under Community tab. Can also be added to Developer documentation where it is more relevant.
4. Community activity - What is the purpose of this page? Description is “follows via RSS, but links are either to Gerrit or don’t work
5. Outreach - Move under Community Tab. 
6. oVirt Global Workshops - Move under Community Tab

Here is a link to a google doc with proposed new layout.

https://docs.google.com/document/d/1hvpumnt9MJATEbT03Ac4R6o56ylQTMNfflDGVPS1oTw/edit#

**Comment by sandrobonazzola** [comment]
@eldan refreshed the look of the documentation page. Is this issue still valid or can we close it @JohnMarksRH ?

**Comment by eldan** [comment]
Hi, the redo of the Documentation page is only a part of the changes. I don’t think we can close the issue yet.
E

**Comment by gregsheremeta** [comment]
fixed
