### ISSUE TITLE
middleman is not working on Fedora 26

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#952]
### Description of the problem

middleman is not working on Fedora 26 so it will be difficult for contributors to verify the patch before submitting

### Steps to reproduce

1. git clone ovirt-site on Fedora 26

2. run setup.sh

3. Get error:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/sbonazzo/.gem/ruby/gems/json-1.8.3/ext/json/ext/generator
/usr/bin/ruby -r ./siteconf20170512-14061-unoh6t.rb extconf.rb
Ignoring curb-0.8.8 because its extensions are not built.  Try: gem pristine curb --version 0.8.8
Ignoring eventmachine-1.2.0.1 because its extensions are not built.  Try: gem pristine eventmachine --version 1.2.0.1
Ignoring eventmachine-1.0.7 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.7
Ignoring ffi-1.9.14 because its extensions are not built.  Try: gem pristine ffi --version 1.9.14
Ignoring ffi-1.9.8 because its extensions are not built.  Try: gem pristine ffi --version 1.9.8
Ignoring hitimes-1.2.4 because its extensions are not built.  Try: gem pristine hitimes --version 1.2.4
Ignoring hitimes-1.2.2 because its extensions are not built.  Try: gem pristine hitimes --version 1.2.2
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Ignoring json-2.0.3 because its extensions are not built.  Try: gem pristine json --version 2.0.3
Ignoring json-1.8.2 because its extensions are not built.  Try: gem pristine json --version 1.8.2
Ignoring nokogiri-1.6.8.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8.1
Ignoring nokogiri-1.6.6.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.6.2
Ignoring oj-2.17.4 because its extensions are not built.  Try: gem pristine oj --version 2.17.4
Ignoring oj-2.12.2 because its extensions are not built.  Try: gem pristine oj --version 2.12.2
Ignoring rainbow-2.2.1 because its extensions are not built.  Try: gem pristine rainbow --version 2.2.1
Ignoring therubyracer-0.12.2 because its extensions are not built.  Try: gem pristine therubyracer --version 0.12.2
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
Ignoring unf_ext-0.0.6 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.6
creating Makefile

current directory: /home/sbonazzo/.gem/ruby/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean
rm -f 
rm -f generator.so  *.o  *.bak mkmf.log .*.time

current directory: /home/sbonazzo/.gem/ruby/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -DJSON_GENERATOR    -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong
--param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic -fPIC -m64 -o generator.o -c generator.c
generator.c: In function ‘generate_json’:
generator.c:861:25: error: ‘rb_cFixnum’ undeclared (first use in this function); did you mean ‘mFixnum’?
     } else if (klass == rb_cFixnum) {
                         ^~~~~~~~~~
                         mFixnum
generator.c:861:25: note: each undeclared identifier is reported only once for each function it appears in
generator.c:863:25: error: ‘rb_cBignum’ undeclared (first use in this function); did you mean ‘rb_cFixnum’?
     } else if (klass == rb_cBignum) {
                         ^~~~~~~~~~
                         rb_cFixnum
make: *** [Makefile:243: generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/sbonazzo/.gem/ruby/gems/json-1.8.3 for inspection.
Results logged to /home/sbonazzo/.gem/ruby/extensions/x86_64-linux/2.4.0/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

**Comment by duck-rh** [comment]
First, @garrett is not working on oVirt anymore.

As for this error, I guess we would probably need to upgrade the gems used to work well with the newer libs in the distro, but I'm not totally sure about the consequences for older distros versions.

You could try to do a 'bundler update' and see if it goes further. If ok then checking the newly generated Gemfile.lock still works for F25 would be needed.

Happily F26 is not released so we still have some time to work on this.

Could you keep us posted on this ticket?

**Comment by sandrobonazzola** [comment]
On Fedora 26:
 $ bundle update
 $ bundle install
worked fine. Then running run-server.sh:

== Administration is at http://0.0.0.0:4567/admin/
bundler: failed to load command: middleman (/home/sbonazzo/bin/middleman)
LoadError: cannot load such file -- ruby_http_parser
  /home/sbonazzo/.gem/ruby/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `require'
  /home/sbonazzo/.gem/ruby/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `<top (required)>'
  /home/sbonazzo/.gem/ruby/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `require'
  /home/sbonazzo/.gem/ruby/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `<top (required)>'
  /home/sbonazzo/.gem/ruby/gems/em-websocket-0.5.1/lib/em-websocket/handshake.rb:1:in `require'
  /home/sbonazzo/.gem/ruby/gems/em-websocket-0.5.1/lib/em-websocket/handshake.rb:1:in `<top (required)>'
  /home/sbonazzo/.gem/ruby/gems/em-websocket-0.5.1/lib/em-websocket.rb:15:in `require'
  /home/sbonazzo/.gem/ruby/gems/em-websocket-0.5.1/lib/em-websocket.rb:15:in `block in <top (required)>'
  /home/sbonazzo/.gem/ruby/gems/em-websocket-0.5.1/lib/em-websocket.rb:14:in `each'
  /home/sbonazzo/.gem/ruby/gems/em-websocket-0.5.1/lib/em-websocket.rb:14:in `<top (required)>'
  /home/sbonazzo/.gem/ruby/gems/middleman-livereload-3.4.6/lib/middleman-livereload/reactor.rb:1:in `require'
  /home/sbonazzo/.gem/ruby/gems/middleman-livereload-3.4.6/lib/middleman-livereload/reactor.rb:1:in `<top (required)>'
  /home/sbonazzo/.gem/ruby/gems/middleman-livereload-3.4.6/lib/middleman-livereload/extension_3_1.rb:2:in `require'
  /home/sbonazzo/.gem/ruby/gems/middleman-livereload-3.4.6/lib/middleman-livereload/extension_3_1.rb:2:in `<top (required)>'
  /home/sbonazzo/.gem/ruby/gems/middleman-livereload-3.4.6/lib/middleman-livereload.rb:5:in `require'
  /home/sbonazzo/.gem/ruby/gems/middleman-livereload-3.4.6/lib/middleman-livereload.rb:5:in `block in <top (required)>'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/extensions.rb:41:in `load'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/extensions.rb:103:in `activate'
  /NotBackedUp/sbonazzo/upstream/ovirt-site/config.rb:218:in `block in initialize'
  /home/sbonazzo/.gem/ruby/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'
  /home/sbonazzo/.gem/ruby/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'
  /home/sbonazzo/.gem/ruby/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'
  /home/sbonazzo/.gem/ruby/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'
  /home/sbonazzo/.gem/ruby/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in `evaluate_callback'
  /home/sbonazzo/.gem/ruby/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in `execute_callback'
  /home/sbonazzo/.gem/ruby/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in `block in run'
  /home/sbonazzo/.gem/ruby/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `each'
  /home/sbonazzo/.gem/ruby/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `inject'
  /home/sbonazzo/.gem/ruby/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `run'
  /home/sbonazzo/.gem/ruby/gems/hooks-0.4.1/lib/hooks.rb:55:in `run_hook_for'
  /home/sbonazzo/.gem/ruby/gems/hooks-0.4.1/lib/hooks/instance_hooks.rb:6:in `run_hook'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/extensions.rb:166:in `initialize'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/data.rb:33:in `initialize'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/application.rb:204:in `initialize'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:56:in `new'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/core_extensions/request.rb:56:in `inst'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/preview_server.rb:107:in `new_app'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/preview_server.rb:24:in `start'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/cli/server.rb:81:in `server'
  /home/sbonazzo/.gem/ruby/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /home/sbonazzo/.gem/ruby/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /home/sbonazzo/.gem/ruby/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/sbonazzo/.gem/ruby/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:72:in `method_missing'
  /home/sbonazzo/.gem/ruby/gems/thor-0.19.4/lib/thor/command.rb:29:in `run'
  /home/sbonazzo/.gem/ruby/gems/thor-0.19.4/lib/thor/command.rb:126:in `run'
  /home/sbonazzo/.gem/ruby/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /home/sbonazzo/.gem/ruby/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /home/sbonazzo/.gem/ruby/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:20:in `start'
  /home/sbonazzo/.gem/ruby/gems/middleman-core-3.3.12/bin/middleman:18:in `<top (required)>'
  /home/sbonazzo/bin/middleman:23:in `load'
  /home/sbonazzo/bin/middleman:23:in `<top (required)>'

**Comment by duck-rh** [comment]
Are you sure there was no error or warning during install? Sometimes it seems to go on even it something happens and you need to check the logs.

In fact *ruby_http_parser.so* is part of the *http_parser* gem which is itself calling for the lib, so they are both in the same gem and clearly is not built or installed properly.

**Comment by sandrobonazzola** [comment]
So,after changing #993 I'm able to run on Fedora 26 with the following changes in the Gemfile.lock: https://gist.github.com/sandrobonazzola/a2302901f79f14c5b4953937bb3e2a54

**Comment by duck-rh** [comment]
quite some updates… I guess the only way to see if there's regressions is to create a PR with these changes and see if the CI is happy. We can also try on our personal machines. It is easy to revert in case the builder is unhappy about it. Could you prepare one?

**Comment by sandrobonazzola** [comment]
Sent PR #995

**Comment by sandrobonazzola** [comment]
If it may help, just checking out current ovirt-site repo and running "bundle update" before ./runserver.sh now works on Fedora 26.

**Comment by duck-rh** [comment]
I made a fix in 992271354 a little while ago and forgot to reference this BR.

The problem with `bundle update ` is that is updates *all* gems, and then you're running on a totally different version of softwares, and you may have new bugs, solved bugs, different rendering… So I would strongly advise against it.

Could you check if the previously referenced fix does not solve the problem? If you just throw aside you `vendor/bundle/` directory and install from scratch it should work (or that's what I got by testing on a fresh F26 image).

**Comment by sandrobonazzola** [comment]
works for me on Fedora 27, closing
