### ISSUE TITLE
Release notes broken Bugzilla links

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#957]
#### This is related to PR#956

All the release note links to Bugzilla are all broken
I corrected the links in 4.1.1 by adjusting the link format to:
[BZ 1371111]followed by no space (https://bugzilla.redhat.com/1371111 "1371111")

**Comment by sandrobonazzola** [comment]
@JohnMarksRH Is this still an issue?

**Comment by JohnMarksRH** [comment]
@sandrobonazzola It's fine now.
