### ISSUE TITLE
4.1.1 intro links, possible typo 

### ISSUE THREAD

**Issue by JohnMarksRH** [oVirt/ovirt-site#961]
### Description of the problem
In 4.1.1 a few issues:
Under the  https://www.ovirt.org/release/4.1.1/#ovirt-hosted-engine heading there are two broken links:

Hosted_Engine_Howto#Fresh_Install
Hosted_Engine_Howto#Upgrade_Hosted_Engine

Under the https://www.ovirt.org/release/4.1.1/#epel heading:
First sentence is TL;DR Don't enable all of EPEL on oVirt machines. Typo? Intentional?

**Comment by mykaul** [comment]
I'm failing to see the typo...

**Comment by JohnMarksRH** [comment]
@mykaul 
I don't understand this
TL;DR Don't enable

TL;DR - too long, didn't review? Don't understand the context

**Comment by mykaul** [comment]
http://lmgtfy.com/?q=tl%3Bdr

 ;-)
