### ISSUE TITLE
Release notes conversion is incomplete

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#98]
Comparing http://www.ovirt.org/release/3.6.3/ and OVirt_3.6.3_Release_Notes I mirrored locally before the switch to the new site, I see that the table of contents is missing (just annoying) and all references to the bugs have been lost (real issue).

In older site I had:
- BZ 1191514 - Missing gluster error codes

with the BZ linked to the bugzilla url. It used a macro/template {{BZ|1191514}}
in new site I only see:
- Missing gluster error codes

Can this be fixed?

**Comment by thatdocslady** [comment]
@garrett can you please check what happened to BZ links during the conversion?

**Comment by garrett** [comment]
Well, there's nothing set up to handle that. I might be able to extend things to support it... but I'm not sure.

(Worst case scenario is that we can use regular expressions to rewrite the content of the pages if it's not easily possible to handle that.)

**Comment by sandrobonazzola** [comment]
Progress on this?

**Comment by gregsheremeta** [comment]
closing old issues
