### ISSUE TITLE
I want to install overt-live from cd....but I can't..  

### ISSUE THREAD

**Issue by umhahahahapu** [oVirt/ovirt-site#987]
### Steps to reproduce

1. prepare overt-live burned cd 

2. booting from cd on HP Server

3. after , install to hard drive (icon) double click ...but don't work.. 
  And I commanded install /usr/xxx/xxxx .. start install but errors come me..
  "GLib.Error: g-io-error-quark: Error calling startservicebyname for org.freedesktop xxxxxxxxxxxxx no such unit....

 How can I install hard drive??

**Comment by mykaul** [comment]
Hi @umhahahahapu - can you please ask the question on the ovirt users mailing list? This issue tracker is for the ovirt website.

Thanks in advance,
Y.
