### ISSUE TITLE
Previous site pages are unreachable

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-site#99]
Even if from the new website the previous website page are referenced, they're not reachable anymore so if something gone wrong with the conversion you can't reach the correct one to compare with.

**Comment by thatdocslady** [comment]
Can you provide some examples?

**Comment by sandrobonazzola** [comment]
http://www.ovirt.org/download/ovirt-live/ has a link to http://ovirt.org/OVirt_Live which just redirect to http://www.ovirt.org/download/ovirt-live/ so you can't check if something is missing.

Same for http://www.ovirt.org/release/3.6.3/ which has a link to http://ovirt.org/OVirt_3.6.3_Release_Notes which is Not found :(

**Comment by thatdocslady** [comment]
@garrett @jasonbrooks can one of you help here?

**Comment by jasonbrooks** [comment]
It looks like all those old wiki page links need to get `old.` appended. So, `http://ovirt.org/OVirt_Live` should become `http://old.ovirt.org/OVirt_Live`, an so on...

**Comment by sandrobonazzola** [comment]
Thanks, fixed.
